/* v195 — couche runtime consolidée: agendas, filtres, actions et pilotage */
/* v196 — une occurrence récurrente est globale; les FI ne gèrent que présences/reporting */
function occurrenceGlobalChangeV196(o){return (db.changes||[]).find(ch=>+ch.template_version_id===+o.version?.id&&ch.old_date===(o.originalDate||o.date)&&['cancelled','postponed'].includes(ch.action))}
const virtualOccurrencesBaseV196=virtualOccurrences;
virtualOccurrences=function(start,end){const base=virtualOccurrencesBaseV196(start,end),out=[];for(const o of base){const ch=occurrenceGlobalChangeV196(o);if(!ch){out.push(o);continue}if(ch.action==='cancelled'){out.push({...o,globalStatus:'cancelled',globalReason:ch.reason});continue}if(ch.action==='postponed'&&ch.new_date){const nd=new Date(ch.new_date+'T12:00');if(nd>=start&&nd<=end)out.push({...o,date:ch.new_date,originalDate:o.date,globalStatus:'postponed',globalReason:ch.reason})}}return out}
function occurrenceChangeFormV196(tid,date,action){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return alert('Séance introuvable.');const post=action==='postponed',pretty=new Date(date+'T12:00').toLocaleDateString('fr-FR');modalForm(post?'Reporter la séance':'Annuler la séance',`<div class="notice"><b>${t.family_type} · ${esc(v.title||t.name)}</b><br>Séance du ${pretty} · Cette action concerne toutes les ${t.family_type}.</div>${post?`<label>Nouvelle date *<input id="changeNewDate" type="date" value="${date}"></label>`:''}<label>Motif *<textarea id="changeReason" rows="5" placeholder="Indiquez clairement le motif..."></textarea></label><small class="muted">Le modèle hebdomadaire reste inchangé. La modification concerne cette séance globale, jamais une FI isolée.</small>`,async()=>{const reason=changeReason.value.trim();if(!reason)throw Error('Le motif est obligatoire.');const newDate=post?changeNewDate.value:null;if(post&&(!newDate||newDate===date))throw Error('Choisissez une nouvelle date différente de la date initiale.');let q=await sb.from('schedule_changes').insert({template_version_id:v.id,action,old_date:date,new_date:newDate,reason});if(q.error)throw q.error;for(const m of db.meetings.filter(m=>+m.template_version_id===+v.id&&(m.original_scheduled_date===date||m.scheduled_date===date))){const patch={status:action==='cancelled'?'cancelled':'postponed'};if(newDate)patch.scheduled_date=newDate;q=await sb.from('meetings').update(patch).eq('id',m.id);if(q.error)throw q.error}})}
function globalOccurrenceActionsV196(o){if(!isDirection())return'';if(o.globalStatus)return'<span class="pill">'+(o.globalStatus==='cancelled'?'ANNULÉE':'REPORTÉE')+'</span>';const date=o.originalDate||o.date;return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();openTemplate('+o.template.id+')">Modifier</button><button class="ghost" onclick="event.stopPropagation();occurrenceChangeFormV196('+o.template.id+',\''+date+'\',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();occurrenceChangeFormV196('+o.template.id+',\''+date+'\',\'cancelled\')">Annuler</button></div>'}
async function openFamilyOccurrenceToolV196(tid,date,fid,tool){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return;const o={date,type:t.family_type,title:v.title||t.name,time:(v.start_time||'').slice(0,5),template:t,version:v};try{const m=await ensureMeeting(o,+fid);tool==='attendance'?openAttendance('meeting',m.id):openReporting(m.id)}catch(e){alert(e.message||'Action impossible.')}}
function familyOccurrenceToolsV196(o,f){const ph=agendaPhase(o.date,o.date,o.globalStatus),can=canWorkFamily(f.id)||isDirection();if(!can||o.globalStatus==='cancelled')return'';if(ph==='current')return '<button class="primary" onclick="event.stopPropagation();openFamilyOccurrenceToolV196('+o.template.id+',\''+(o.originalDate||o.date)+'\','+f.id+',\'attendance\')">Présences</button>';if(ph==='past')return '<button class="ghost" onclick="event.stopPropagation();openFamilyOccurrenceToolV196('+o.template.id+',\''+(o.originalDate||o.date)+'\','+f.id+',\'reporting\')">Reporting</button>';return''}

let agendaMeetingPhase='upcoming',agendaMeetingPeriod='month',agendaMeetingKind='all';
let agendaProgramPhase='upcoming',agendaProgramPeriod='month',agendaProgramKind='all';
let familyAgendaPhase='upcoming',familyAgendaPeriod='month',familyAgendaKind='all';

function agendaSeasonBounds(){
  const now=dateISO(new Date()), seasons=(typeof fiExtra!=='undefined'&&fiExtra.seasons)||[];
  const s=seasons.find(x=>x.active&&x.starts_on<=now&&x.ends_on>=now)||seasons.filter(x=>x.active).sort((a,b)=>b.starts_on.localeCompare(a.starts_on))[0];
  return s?[new Date(s.starts_on+'T00:00:00'),new Date(s.ends_on+'T23:59:59')]:periodBounds('year');
}
function agendaBounds(period){return period==='season'?agendaSeasonBounds():periodBounds(period)}
function agendaPhase(start,end,status){
  if(status==='cancelled')return'past';
  const today=dateISO(new Date()), last=end||start;
  return last<today?'past':start>today?'upcoming':'current';
}
function phaseTabs(value,setter,pluralF){
  const labs=pluralF?[['past','Passées'],['current','En cours'],['upcoming','À venir']]:[['past','Passés'],['current','En cours'],['upcoming','À venir']];
  return '<div class="meeting-subtabs-v180">'+labs.map(([v,l])=>'<button class="'+(value===v?'active':'')+'" onclick="'+setter+"('"+v+"')"+'">'+l+'</button>').join('')+'</div>';
}
function periodSelect(value,setter,week=true){
  const opts=(week?[['week','Semaine']]:[]).concat([['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année']]);
  return '<label>Période<select onchange="'+setter+'(this.value)">'+opts.map(([v,l])=>'<option value="'+v+'" '+(value===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label>';
}
async function occurrenceActionV195(tid,date,fid,action){
  const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return;
  let m=materializedFor({date,template:t,version:v},fid);
  if(!m)m=await ensureMeeting({date,type:t.family_type,title:v.title||t.name,time:(v.start_time||'').slice(0,5),template:t,version:v},fid);
  if(!m)return;
  if(action==='edit'&&typeof editMeetingOccurrenceV7==='function')return editMeetingOccurrenceV7(m.id);
  openScheduleChangeSheetV195('meeting',m.id,action);
}
function meetingActionsV195(m){
  const can=isDirection()||(typeof canManageOccurrenceV7==='function'&&canManageOccurrenceV7(m));if(!can)return'';
  return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();'+(m.template_id&&typeof editMeetingOccurrenceV7==='function'?'editMeetingOccurrenceV7('+m.id+')':'openMeeting('+m.id+')')+'">Modifier</button><button class="ghost" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'meeting\','+m.id+',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'meeting\','+m.id+',\'cancelled\')">Annuler</button></div>';
}
function virtualActionsV195(o,fid){
  if(!isDirection()&&typeof canActionV6==='function'&&!canActionV6(o.type==='FIJ'?'meetings.fij.manage':'meetings.fi.manage',fid))return'';
  return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();occurrenceActionV195('+o.template.id+',\''+o.date+'\','+fid+',\'edit\')">Modifier</button><button class="ghost" onclick="event.stopPropagation();occurrenceActionV195('+o.template.id+',\''+o.date+'\','+fid+',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();occurrenceActionV195('+o.template.id+',\''+o.date+'\','+fid+',\'cancelled\')">Annuler</button></div>';
}
function programActionsV195(p){
  if(!isDirection())return'';
  return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();editProgramV193('+p.id+')">Modifier</button><button class="ghost" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'program\','+p.id+',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'program\','+p.id+',\'cancelled\')">Annuler</button></div>';
}
function setAgendaMeetingPhase(v){agendaMeetingPhase=v;render()} function setAgendaMeetingPeriod(v){agendaMeetingPeriod=v;render()} function setAgendaMeetingKind(v){agendaMeetingKind=v;render()}
function meetingsPage(){
  const [s,e]=agendaBounds(agendaMeetingPeriod),si=dateISO(s),ei=dateISO(e),rows=[];
  virtualOccurrences(s,e).forEach(o=>rows.push({date:o.date,phase:agendaPhase(o.date,o.date),kind:'weekly',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openOccurrenceBy('+o.template.id+',\''+(o.originalDate||o.date)+'\')"><div><b>'+esc(o.title)+'</b><div class="muted">'+new Date(o.date+'T12:00').toLocaleDateString('fr-FR')+' · '+(o.time||'Horaire à préciser')+' · Toutes les '+o.type+(o.globalStatus==='cancelled'?' · Annulée':o.originalDate?' · Reportée':'')+'</div></div><span class="pill '+o.type.toLowerCase()+'">'+o.type+'</span></div>'+globalOccurrenceActionsV196(o)+'</div>'}));
  db.meetings.filter(m=>m.scheduled_date>=si&&m.scheduled_date<=ei&&!m.template_version_id).forEach(m=>rows.push({date:m.scheduled_date,phase:agendaPhase(m.scheduled_date,m.scheduled_date,m.status),kind:'exceptional',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openMeeting('+m.id+')"><div><b>'+esc(m.title)+'</b><div class="muted">'+new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+' · '+esc(familyName(m.family_id))+' · Rencontre exceptionnelle</div></div><span class="pill">'+statusLabel(m.status)+'</span></div>'+meetingActionsV195(m)+'</div>'}));
  const out=rows.filter(x=>x.phase===agendaMeetingPhase&&(agendaMeetingKind==='all'||x.kind===agendaMeetingKind)).sort((a,b)=>(agendaMeetingPhase==='past'?-1:1)*a.date.localeCompare(b.date));
  return '<div class="card page-card"><div class="toolbar"><div><h2>Rencontres</h2><p class="muted">Rencontres FI/FIJ uniquement.</p></div><button class="primary" onclick="formMeeting()">＋ Rencontre exceptionnelle</button></div>'+phaseTabs(agendaMeetingPhase,'setAgendaMeetingPhase',true)+'<div class="compact-filters-v180">'+periodSelect(agendaMeetingPeriod,'setAgendaMeetingPeriod',true)+'<label>Classement<select onchange="setAgendaMeetingKind(this.value)"><option value="all">Toutes</option><option value="weekly" '+(agendaMeetingKind==='weekly'?'selected':'')+'>Hebdomadaires</option><option value="exceptional" '+(agendaMeetingKind==='exceptional'?'selected':'')+'>Exceptionnelles</option></select></label></div>'+out.map(x=>x.html).join('')+(out.length?'':'<p class="muted">Aucune rencontre pour ces filtres.</p>')+'</div>';
}
function setAgendaProgramPhase(v){agendaProgramPhase=v;render()} function setAgendaProgramPeriod(v){agendaProgramPeriod=v;render()} function setAgendaProgramKind(v){agendaProgramKind=v;render()}
function programsPage(){
  const [s,e]=agendaBounds(agendaProgramPeriod),si=dateISO(s),ei=dateISO(e),types=[...new Set(db.programs.map(p=>p.kind).filter(Boolean))].sort();
  const rows=db.programs.filter(p=>p.scheduled_date<=ei&&(p.end_date||p.scheduled_date)>=si).filter(p=>agendaPhase(p.scheduled_date,p.end_date,p.status)===agendaProgramPhase).filter(p=>agendaProgramKind==='all'||p.kind===agendaProgramKind).sort((a,b)=>(agendaProgramPhase==='past'?-1:1)*a.scheduled_date.localeCompare(b.scheduled_date));
  return '<div class="card page-card"><div class="toolbar"><div><h2>Programmes & événements</h2><p class="muted">Classement par état, période et type.</p></div>'+(isDirection()?'<button class="primary" onclick="formProgram()">＋ Nouveau</button>':'')+'</div>'+phaseTabs(agendaProgramPhase,'setAgendaProgramPhase',false)+'<div class="compact-filters-v180">'+periodSelect(agendaProgramPeriod,'setAgendaProgramPeriod',false)+'<label>Type<select onchange="setAgendaProgramKind(this.value)"><option value="all">Tous les types</option>'+types.map(t=>'<option value="'+esc(t)+'" '+(agendaProgramKind===t?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label></div>'+rows.map(p=>'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openProgram('+p.id+')"><div><b>'+esc(p.title)+'</b><div class="muted">'+new Date(p.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+(p.end_date&&p.end_date!==p.scheduled_date?' → '+new Date(p.end_date+'T12:00').toLocaleDateString('fr-FR'):'')+' · '+esc(p.kind||'Programme')+'</div></div><span class="pill">'+statusLabel(p.status)+'</span></div>'+programActionsV195(p)+'</div>').join('')+(rows.length?'':'<p class="muted">Aucun programme pour ces filtres.</p>')+'</div>';
}
function setFamilyAgendaPhase(v){familyAgendaPhase=v;refreshFamilyAgendaV195()} function setFamilyAgendaPeriod(v){familyAgendaPeriod=v;refreshFamilyAgendaV195()} function setFamilyAgendaKind(v){familyAgendaKind=v;refreshFamilyAgendaV195()}
function familyAgendaV195(f){
  const [s,e]=agendaBounds(familyAgendaPeriod),si=dateISO(s),ei=dateISO(e),rows=[];
  virtualOccurrences(s,e).filter(o=>o.type===f.family_type).forEach(o=>rows.push({date:o.date,phase:agendaPhase(o.date,o.date),kind:'weekly',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195"><div><b>'+esc(o.title)+'</b><div class="muted">'+new Date(o.date+'T12:00').toLocaleDateString('fr-FR')+' · '+(o.time||'Horaire à préciser')+' · Rencontre globale '+o.type+'</div></div><span class="pill">'+o.type+'</span></div><div class="row-actions">'+familyOccurrenceToolsV196(o,f)+'</div></div>'}));
  familyMeetings(f.id).filter(m=>!m.template_version_id&&m.scheduled_date>=si&&m.scheduled_date<=ei).forEach(m=>rows.push({date:m.scheduled_date,phase:agendaPhase(m.scheduled_date,m.scheduled_date,m.status),kind:'exceptional',html:meetingSpaceRow(m,agendaPhase(m.scheduled_date,m.scheduled_date,m.status)==='current')}));
  db.programs.filter(p=>programTargetFamilies(p).some(z=>+z.id===+f.id)&&p.scheduled_date<=ei&&(p.end_date||p.scheduled_date)>=si).forEach(p=>rows.push({date:p.scheduled_date,phase:agendaPhase(p.scheduled_date,p.end_date,p.status),kind:'program',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openProgram('+p.id+')"><div><b>'+esc(p.title)+'</b><div class="muted">'+new Date(p.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+' · '+esc(p.kind||'Programme')+'</div></div><span class="pill">'+statusLabel(p.status)+'</span></div>'+programActionsV195(p)+'</div>'}));
  const out=rows.filter(x=>x.phase===familyAgendaPhase&&(familyAgendaKind==='all'||x.kind===familyAgendaKind)).sort((a,b)=>(familyAgendaPhase==='past'?-1:1)*a.date.localeCompare(b.date));
  return '<div class="card"><div class="toolbar"><div><h3>Agenda</h3><p class="muted">Rencontres, programmes et événements de cette '+f.family_type+'.</p></div></div>'+phaseTabs(familyAgendaPhase,'setFamilyAgendaPhase',true)+'<div class="compact-filters-v180">'+periodSelect(familyAgendaPeriod,'setFamilyAgendaPeriod',true)+'<label>Classement<select onchange="setFamilyAgendaKind(this.value)"><option value="all">Tout</option><option value="weekly" '+(familyAgendaKind==='weekly'?'selected':'')+'>Rencontres hebdomadaires</option><option value="exceptional" '+(familyAgendaKind==='exceptional'?'selected':'')+'>Rencontres exceptionnelles</option><option value="program" '+(familyAgendaKind==='program'?'selected':'')+'>Programmes & événements</option></select></label></div><div id="familyAgendaV195">'+out.map(x=>x.html).join('')+(out.length?'':'<p class="muted">Aucun élément pour ces filtres.</p>')+'</div></div>';
}
function refreshFamilyAgendaV195(){const f=db.families.find(x=>+x.id===+window.familyAgendaIdV195),body=document.getElementById('familySpaceBody');if(f&&body)body.innerHTML=familyAgendaV195(f)}
const familySpaceBaseV195=familySpace;
familySpace=function(id,tab='overview'){if(tab==='programs')tab='meetings';window.familyAgendaIdV195=+id;familySpaceBaseV195(+id,tab);if(tab==='meetings'){const f=db.families.find(x=>+x.id===+id),body=document.getElementById('familySpaceBody');if(f&&body){try{body.innerHTML=familyAgendaV195(f)}catch(e){console.error('Agenda FI',e);body.innerHTML='<div class="card"><h3>Agenda</h3><p class="muted">Impossible de charger l’agenda. Rechargez la page.</p></div>'}}}}
function pilotControlsV12(s,e){
  const label={week:'Semaine',month:'Mois',quarter:'Trimestre',semester:'Semestre',season:'Saison FI',year:'Année',custom:'Personnalisée'}[statsPeriod]||'Période';
  return '<div class="card pilot-head-v195"><div class="pilot-toolbar-v189"><div><h2>Pilotage & statistiques</h2><p class="muted">'+label+' · '+s+' → '+e+'</p></div><div class="pilot-actions-v189"><button class="ghost" onclick="document.getElementById(\'pilotFiltersV195\').classList.toggle(\'hidden\')">☰ Filtres</button><button class="ghost" onclick="exportPilotageExcel()">Excel</button><button class="ghost" onclick="exportPilotagePDF()">PDF</button></div></div><div id="pilotFiltersV195" class="pilot-filter-panel-v189 hidden"><label>Période<select onchange="setStatsPeriod(this.value)">'+[['week','Semaine'],['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année'],['custom','Personnalisée']].map(([v,l])=>'<option value="'+v+'" '+(statsPeriod===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label class="compare-toggle-v12"><input type="checkbox" '+(statsCompare?'checked':'')+' onchange="statsCompare=this.checked;render()"> Comparer à la période précédente</label><div id="customStats" class="'+(statsPeriod==='custom'?'':'hidden')+'"><input id="statsStart" type="date" value="'+(statsCustomStart||s)+'"><input id="statsEnd" type="date" value="'+(statsCustomEnd||e)+'"><button class="primary" onclick="setCustomStats()">Appliquer</button></div></div>'+pilotCompareLabelV12(s,e)+'<div class="pilot-nav-wrap-v189">'+pilotTabsV12()+'</div></div>';
}
function openScheduleChangeSheetV195(kind,id,action){
  const obj=db[kind==='meeting'?'meetings':'programs'].find(x=>+x.id===+id);if(!obj)return;const cancel=action==='cancelled';
  modal.innerHTML='<div class="modal-card wide schedule-sheet-v183"><button class="close" onclick="closeModal()">×</button><div class="report-hero"><div><p class="eyebrow">'+(cancel?'ANNULATION':'REPORT')+'</p><h2>'+(cancel?'Annuler':'Reporter')+' — '+esc(obj.title)+'</h2><p class="muted">Date actuelle : '+new Date(obj.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+'</p></div></div><div class="report-section"><h3>'+(cancel?'Informations sur l’annulation':'Nouvelle programmation')+'</h3>'+(cancel?'':'<div class="form-row"><label>Nouvelle date *<input id="scNewDate" type="date" value="'+obj.scheduled_date+'"></label>'+(kind==='program'?'<label>Nouvelle date de fin<input id="scNewEnd" type="date" value="'+(obj.end_date||obj.scheduled_date)+'"></label>':'')+'</div>')+'<label>Motif *<select id="scReasonType"><option value="">Choisir un motif</option><option>Indisponibilité des responsables</option><option>Lieu indisponible</option><option>Contrainte d’organisation</option><option>Conflit de calendrier</option><option>Faible disponibilité des participants</option><option>Cas de force majeure</option><option>Autre</option></select></label><label>Précisions *<textarea id="scReason" rows="4"></textarea></label><label>Consigne / information à communiquer<textarea id="scNote" rows="3"></textarea></label></div><div class="report-savebar"><button class="ghost" onclick="closeModal()">Retour</button><button class="'+(cancel?'danger':'primary')+'" onclick="saveScheduleChangeV195(\''+kind+'\','+id+',\''+action+'\',this)">'+(cancel?'Confirmer l’annulation':'Confirmer le report')+'</button></div></div>';modal.classList.remove('hidden');
}
async function saveScheduleChangeV195(kind,id,action,btn){
  const obj=db[kind==='meeting'?'meetings':'programs'].find(x=>+x.id===+id),type=scReasonType.value,details=scReason.value.trim(),note=scNote.value.trim();if(!type||!details)return alert('Le motif et les précisions sont obligatoires.');
  const newDate=action==='postponed'?scNewDate.value:null,newEnd=action==='postponed'&&kind==='program'?scNewEnd.value:null;if(action==='postponed'&&!newDate)return alert('La nouvelle date est obligatoire.');if(newEnd&&newEnd<newDate)return alert('La date de fin ne peut pas précéder la date de début.');
  btn.disabled=true;try{const reason=type+' — '+details+(note?' — Information : '+note:'');let q=await sb.from('schedule_changes').insert({[kind+'_id']:id,action,old_date:obj.scheduled_date,new_date:newDate,reason});if(q.error)throw q.error;const patch={status:action==='cancelled'?'cancelled':'postponed'};if(newDate)patch.scheduled_date=newDate;if(kind==='program'&&newEnd)patch.end_date=newEnd;q=await sb.from(kind==='meeting'?'meetings':'programs').update(patch).eq('id',id);if(q.error)throw q.error;closeModal();await loadData();render()}catch(e){alert(e.message||'Modification impossible.')}finally{btn.disabled=false}
}
scheduleChange=function(kind,id,action){openScheduleChangeSheetV195(kind,id,action)}
