/* v195 — couche runtime consolidée: agendas, filtres, actions et pilotage */
/* v196 — une occurrence récurrente est globale; les FI ne gèrent que présences/reporting */
function occurrenceGlobalChangeV196(o){return (db.changes||[]).find(ch=>+ch.template_version_id===+o.version?.id&&ch.old_date===(o.originalDate||o.date)&&['cancelled','postponed'].includes(ch.action))}
function occurrenceGlobalEditV199(o){return (db.changes||[]).filter(ch=>+ch.template_version_id===+o.version?.id&&ch.old_date===(o.originalDate||o.date)&&ch.action==='modified').sort((a,b)=>String(b.changed_at||'').localeCompare(String(a.changed_at||'')))[0]}
const virtualOccurrencesBaseV196=typeof virtualOccurrences==='function'?virtualOccurrences:function(){return[]};
virtualOccurrences=function(start,end){const base=virtualOccurrencesBaseV196(start,end),out=[];for(const raw of base){const ed=occurrenceGlobalEditV199(raw),o=ed?{...raw,title:ed.new_title||raw.title,theme:ed.new_theme||null,time:ed.new_start?new Date(ed.new_start).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):raw.time,endTime:ed.new_end?new Date(ed.new_end).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):null,globalEdited:true}:raw;const ch=occurrenceGlobalChangeV196(o);if(!ch){out.push(o);continue}if(ch.action==='cancelled'){out.push({...o,globalStatus:'cancelled',globalReason:ch.reason});continue}if(ch.action==='postponed'&&ch.new_date){const nd=new Date(ch.new_date+'T12:00');if(nd>=start&&nd<=end)out.push({...o,date:ch.new_date,originalDate:o.date,globalStatus:'postponed',globalReason:ch.reason})}}return out}
function occurrenceChangeFormV196(tid,date,action){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return alert('Séance introuvable.');const post=action==='postponed',pretty=new Date(date+'T12:00').toLocaleDateString('fr-FR');modalForm(post?'Reporter la séance':'Annuler la séance',`<div class="notice"><b>${t.family_type} · ${esc(v.title||t.name)}</b><br>Séance du ${pretty} · Cette action concerne toutes les ${t.family_type}.</div>${post?`<label>Nouvelle date *<input id="changeNewDate" type="date" value="${date}"></label>`:''}<label>Motif *<textarea id="changeReason" rows="5" placeholder="Indiquez clairement le motif..."></textarea></label><small class="muted">Le modèle hebdomadaire reste inchangé. La modification concerne cette séance globale, jamais une FI isolée.</small>`,async()=>{const reason=changeReason.value.trim();if(!reason)throw Error('Le motif est obligatoire.');const newDate=post?changeNewDate.value:null;if(post&&(!newDate||newDate===date))throw Error('Choisissez une nouvelle date différente de la date initiale.');let q=await sb.from('schedule_changes').insert({template_version_id:v.id,action,old_date:date,new_date:newDate,reason});if(q.error)throw q.error;for(const m of db.meetings.filter(m=>+m.template_version_id===+v.id&&(m.original_scheduled_date===date||m.scheduled_date===date))){const patch={status:action==='cancelled'?'cancelled':'postponed'};if(newDate)patch.scheduled_date=newDate;q=await sb.from('meetings').update(patch).eq('id',m.id);if(q.error)throw q.error}})}
function editGlobalOccurrenceV199(tid,date){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return;const base={date,type:t.family_type,title:v.title||t.name,time:(v.start_time||'').slice(0,5),template:t,version:v},ed=occurrenceGlobalEditV199(base),start=ed?.new_start?new Date(ed.new_start).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):(v.start_time||'').slice(0,5),end=ed?.new_end?new Date(ed.new_end).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):(v.end_time||'').slice(0,5);modalForm('Modifier cette rencontre',`<p class="muted">Cette modification concerne uniquement la rencontre du ${new Date(date+'T12:00').toLocaleDateString('fr-FR')} pour toutes les ${t.family_type}. Le modèle hebdomadaire reste inchangé.</p><label>Titre<input id="goTitleV199" value="${esc(ed?.new_title||v.title||t.name)}"></label><label>Thème<input id="goThemeV199" value="${esc(ed?.new_theme||'')}" placeholder="Thème de cette rencontre"></label><div class="form-row"><label>Début<input id="goStartV199" type="time" value="${start}"></label><label>Fin<input id="goEndV199" type="time" value="${end}"></label></div><label>Précisions et orientations<textarea id="goReasonV199" rows="3" placeholder="Précisions utiles, orientation donnée, consignes particulières...">${esc(ed?.new_theme_description||'')}</textarea></label>`,async()=>{if(goStartV199.value&&goEndV199.value&&goEndV199.value<=goStartV199.value)throw Error('L’heure de fin doit être postérieure à l’heure de début.');const stamp=x=>x?new Date(`${date}T${x}:00`).toISOString():null,q=await sb.from('schedule_changes').insert({template_version_id:v.id,action:'modified',old_date:date,new_start:stamp(goStartV199.value),new_end:stamp(goEndV199.value),new_title:goTitleV199.value.trim()||v.title||t.name,new_theme:goThemeV199.value.trim()||null,new_theme_description:goReasonV199.value.trim()||null,reason:null,changed_by:session.user.id});if(q.error)throw q.error;const mats=db.meetings.filter(m=>+m.template_version_id===+v.id&&(m.original_scheduled_date===date||m.scheduled_date===date));for(const m of mats){const u=await sb.from('meetings').update({title:goTitleV199.value.trim()||m.title,theme:goThemeV199.value.trim()||null,theme_description:goReasonV199.value.trim()||null,planned_start:stamp(goStartV199.value),planned_end:stamp(goEndV199.value)}).eq('id',m.id);if(u.error)throw u.error}})}
function globalOccurrenceActionsV196(o){if(!isDirection())return'';if(o.globalStatus)return'<span class="pill">'+(o.globalStatus==='cancelled'?'ANNULÉE':'REPORTÉE')+'</span>';const date=o.originalDate||o.date;return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();editGlobalOccurrenceV199('+o.template.id+',\''+date+'\')">Modifier</button><button class="ghost" onclick="event.stopPropagation();occurrenceChangeFormV196('+o.template.id+',\''+date+'\',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();occurrenceChangeFormV196('+o.template.id+',\''+date+'\',\'cancelled\')">Annuler</button></div>'}
async function openFamilyOccurrenceToolV196(tid,date,fid,tool){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return;let o={date,type:t.family_type,title:v.title||t.name,time:(v.start_time||'').slice(0,5),endTime:(v.end_time||'').slice(0,5),template:t,version:v};const ed=occurrenceGlobalEditV199(o);if(ed)o={...o,title:ed.new_title||o.title,theme:ed.new_theme||null,time:ed.new_start?new Date(ed.new_start).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):o.time,endTime:ed.new_end?new Date(ed.new_end).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):o.endTime};try{const m=await ensureMeeting(o,+fid);if(ed){const patch={title:o.title,theme:ed.new_theme||null,theme_description:ed.new_theme_description||null,planned_start:ed.new_start||m.planned_start,planned_end:ed.new_end||m.planned_end};await sb.from('meetings').update(patch).eq('id',m.id);Object.assign(m,patch)}tool==='attendance'?openAttendance('meeting',m.id):openReporting(m.id)}catch(e){alert(typeof frenchError==='function'?frenchError(e):'Action impossible.')}}
function familyOccurrenceToolsV196(o,f){const ph=agendaPhase(o.date,o.date,o.globalStatus,o.time,o.endTime),can=canWorkFamily(f.id)||isDirection();if(!can||o.globalStatus==='cancelled')return'';if(ph==='current')return '<button class="primary" onclick="event.stopPropagation();openFamilyOccurrenceToolV196('+o.template.id+',\''+(o.originalDate||o.date)+'\','+f.id+',\'attendance\')">Présences</button>';if(ph==='past')return '<button class="ghost" onclick="event.stopPropagation();openFamilyOccurrenceToolV196('+o.template.id+',\''+(o.originalDate||o.date)+'\','+f.id+',\'reporting\')">Reporting</button>';return''}

function agendaStatusLabelV198(s){return {scheduled:'Prévue',in_progress:'En cours',completed:'Terminée',postponed:'Reportée',cancelled:'Annulée'}[s]||s||'Prévue'}
let agendaMeetingPhase='upcoming',agendaMeetingPeriod='month',agendaMeetingKind='all';
let agendaProgramPhase='upcoming',agendaProgramPeriod='month',agendaProgramKind='all';
let familyAgendaPhase='upcoming',familyAgendaPeriod='month',familyAgendaKind='all';

function agendaSeasonBounds(){
  const now=dateISO(new Date()), seasons=(typeof fiExtra!=='undefined'&&fiExtra.seasons)||[];
  const s=seasons.find(x=>x.active&&x.starts_on<=now&&x.ends_on>=now)||seasons.filter(x=>x.active).sort((a,b)=>b.starts_on.localeCompare(a.starts_on))[0];
  return s?[new Date(s.starts_on+'T00:00:00'),new Date(s.ends_on+'T23:59:59')]:periodBounds('year');
}
function agendaBounds(period){if(period==='all')return[new Date('2000-01-01T00:00:00'),new Date('2100-12-31T23:59:59')];return period==='season'?agendaSeasonBounds():periodBounds(period)}
function agendaPhase(start,end,status,startTime,endTime){
  if(status==='cancelled')return'past';
  const now=new Date();
  const sDate=start||end, eDate=end||start||sDate;
  if(!sDate)return'upcoming';
  const toDateTime=(d,t,fallbackEnd=false)=>{if(!d)return null;const tm=(t||'').slice(0,5);if(tm)return new Date(`${d}T${tm}:00`);return new Date(`${d}T${fallbackEnd?'23:59:59':'00:00:00'}`)};
  const s=toDateTime(sDate,startTime,false), e=toDateTime(eDate,endTime,true);
  if(now<s)return'upcoming';
  if(now<=e)return'current';
  return'past';
}
function phaseTabs(value,setter,pluralF){
  const labs=pluralF?[['past','Passées'],['current','En cours'],['upcoming','À venir']]:[['past','Passés'],['current','En cours'],['upcoming','À venir']];
  return '<div class="meeting-subtabs-v180" role="tablist">'+labs.map(([v,l])=>'<button type="button" role="tab" aria-selected="'+(value===v?'true':'false')+'" class="'+(value===v?'active':'')+'" data-phase="'+v+'" onclick="event.preventDefault();event.stopPropagation();'+setter+'(this.dataset.phase)">'+l+'</button>').join('')+'</div>';
}
function periodSelect(value,setter,week=true){
  const opts=(week?[['week','Semaine']]:[]).concat([['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année'],['all','Tout']]);
  return '<label>Période<select onchange="'+setter+'(this.value)">'+opts.map(([v,l])=>'<option value="'+v+'" '+(value===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label>';
}
async /* v237 — actions individuelles d'occurrence désactivées : une occurrence récurrente est globale. */
function occurrenceActionV195(){return alert('Cette occurrence est globale et ne peut pas être modifiée pour une FI individuellement.');}
function virtualActionsV195(){return '';}
async function deleteMeetingV203(id){if(!isDirection())return;const m=db.meetings.find(x=>+x.id===+id);if(!m)return;if(!confirm('Supprimer définitivement cette rencontre et toutes les données qui lui sont rattachées ? Cette action est irréversible.'))return;const q=await sb.from('meetings').delete().eq('id',id);if(q.error)return alert('Suppression impossible : '+q.error.message);await loadData();render()}
async function deleteProgramV203(id){if(!isDirection())return;const p=db.programs.find(x=>+x.id===+id);if(!p)return;if(!confirm('Supprimer définitivement ce programme et toutes les données qui lui sont rattachées ? Cette action est irréversible.'))return;const q=await sb.from('programs').delete().eq('id',id);if(q.error)return alert('Suppression impossible : '+q.error.message);await loadData();render()}
function meetingActionsV195(m){
  const can=isDirection()||(typeof canManageOccurrenceV7==='function'&&canManageOccurrenceV7(m));if(!can)return'';
  return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();'+(typeof editMeetingOccurrenceV7==='function'?'editMeetingOccurrenceV7('+m.id+')':'openMeeting('+m.id+')')+'">Modifier</button><button class="ghost" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'meeting\','+m.id+',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'meeting\','+m.id+',\'cancelled\')">Annuler</button>'+(isDirection()?'<button class="ghost danger" onclick="event.stopPropagation();deleteMeetingV203('+m.id+')">Supprimer</button>':'')+'</div>';
}
function virtualActionsV195(){return '';}

function programActionsV195(p){
  if(!isDirection())return'';
  return '<div class="row-actions agenda-actions-v195"><button class="ghost" onclick="event.stopPropagation();editProgramV193('+p.id+')">Modifier</button><button class="ghost" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'program\','+p.id+',\'postponed\')">Reporter</button><button class="ghost danger" onclick="event.stopPropagation();openScheduleChangeSheetV195(\'program\','+p.id+',\'cancelled\')">Annuler</button><button class="ghost danger" onclick="event.stopPropagation();deleteProgramV203('+p.id+')">Supprimer</button></div>';
}
function setAgendaMeetingPhase(v){agendaMeetingPhase=v;render()} function setAgendaMeetingPeriod(v){agendaMeetingPeriod=v;render()} function setAgendaMeetingKind(v){agendaMeetingKind=v;render()}
function meetingsPage(){
  const [s,e]=agendaBounds(agendaMeetingPeriod),si=dateISO(s),ei=dateISO(e),rows=[];let occ=[];try{occ=virtualOccurrences(s,e)||[]}catch(err){console.error('Rencontres récurrentes',err);occ=[]}
  occ.forEach(o=>rows.push({date:o.date,phase:agendaPhase(o.date,o.date,undefined,o.time,o.endTime),kind:'weekly',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openOccurrenceBy('+o.template.id+',\''+(o.originalDate||o.date)+'\')"><div><b>'+esc(o.title)+'</b><div class="muted">'+new Date(o.date+'T12:00').toLocaleDateString('fr-FR')+' · '+(o.time||'Horaire à préciser')+(o.endTime?' → '+o.endTime:'')+' · Toutes les '+o.type+(o.globalStatus==='cancelled'?' · Annulée':o.originalDate?' · Reportée':'')+'</div></div><span class="pill '+o.type.toLowerCase()+'">'+o.type+'</span></div>'+globalOccurrenceActionsV196(o)+'</div>'}));
  db.meetings.filter(m=>m.scheduled_date>=si&&m.scheduled_date<=ei&&!m.template_version_id).forEach(m=>rows.push({date:m.scheduled_date,phase:agendaPhase(m.scheduled_date,m.scheduled_date,m.status,m.planned_start?new Date(m.planned_start).toTimeString():null,m.planned_end?new Date(m.planned_end).toTimeString():null),kind:'exceptional',html:'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openMeeting('+m.id+')"><div><b>'+esc(m.title)+'</b><div class="muted">'+new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+' · '+esc(familyName(m.family_id))+' · Rencontre exceptionnelle</div></div><span class="pill">'+agendaStatusLabelV198(m.status)+'</span></div>'+meetingActionsV195(m)+'</div>'}));
  const out=rows.filter(x=>x.phase===agendaMeetingPhase&&(agendaMeetingKind==='all'||x.kind===agendaMeetingKind)).sort((a,b)=>(agendaMeetingPhase==='past'?-1:1)*a.date.localeCompare(b.date));
  return '<div class="card page-card"><div class="toolbar"><div><h2>Rencontres</h2><p class="muted">Rencontres FI/FIJ uniquement.</p></div><button class="primary" onclick="formMeeting()">＋ Rencontre exceptionnelle</button></div>'+phaseTabs(agendaMeetingPhase,'setAgendaMeetingPhase',true)+'<div class="compact-filters-v180">'+periodSelect(agendaMeetingPeriod,'setAgendaMeetingPeriod',true)+'<label>Type<select onchange="setAgendaMeetingKind(this.value)"><option value="all">Toutes les rencontres</option><option value="weekly" '+(agendaMeetingKind==='weekly'?'selected':'')+'>Rencontres hebdomadaires</option><option value="exceptional" '+(agendaMeetingKind==='exceptional'?'selected':'')+'>Rencontres exceptionnelles</option></select></label></div><div class="activity-list-v237">'+out.map(x=>x.html).join('')+(out.length?'':'<p class="muted">Aucune rencontre pour ces filtres.</p>')+'</div></div>';
}
function setAgendaProgramPhase(v){agendaProgramPhase=v;render()} function setAgendaProgramPeriod(v){agendaProgramPeriod=v;render()} function setAgendaProgramKind(v){agendaProgramKind=v;render()}
function programsPage(){
  const [s,e]=agendaBounds(agendaProgramPeriod),si=dateISO(s),ei=dateISO(e),types=[...new Set(['Programme','Programme de prière','Événement','Formation','Réunion',...db.programs.map(p=>p.kind).filter(Boolean)])];
  const rows=db.programs.filter(p=>p.scheduled_date<=ei&&(p.end_date||p.scheduled_date)>=si).filter(p=>agendaPhase(p.scheduled_date,p.end_date,p.status,p.planned_start?new Date(p.planned_start).toTimeString():null,p.planned_end?new Date(p.planned_end).toTimeString():null)===agendaProgramPhase).filter(p=>agendaProgramKind==='all'||p.kind===agendaProgramKind).sort((a,b)=>(agendaProgramPhase==='past'?-1:1)*a.scheduled_date.localeCompare(b.scheduled_date));
  return '<div class="card page-card"><div class="toolbar"><div><h2>Programmes & événements</h2><p class="muted">Classement par état, période et type.</p></div>'+(isDirection()?'<button class="ghost" onclick="fiTourForm()">＋ FI/FIJ Tour</button><button class="primary" onclick="formProgram()">＋ Nouveau</button>':'')+'</div>'+phaseTabs(agendaProgramPhase,'setAgendaProgramPhase',false)+'<div class="compact-filters-v180">'+periodSelect(agendaProgramPeriod,'setAgendaProgramPeriod',false)+'<label>Type<select onchange="setAgendaProgramKind(this.value)"><option value="all">Tous les types</option>'+types.map(t=>'<option value="'+esc(t)+'" '+(agendaProgramKind===t?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label></div>'+rows.map(p=>'<div class="family-row agenda-row-v195"><div class="agenda-main-v195 clickable" onclick="openProgram('+p.id+')"><div><b>'+esc(p.title)+'</b><div class="muted">'+new Date(p.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+(p.end_date&&p.end_date!==p.scheduled_date?' → '+new Date(p.end_date+'T12:00').toLocaleDateString('fr-FR'):'')+' · '+esc(p.kind||'Programme')+'</div></div><span class="pill">'+agendaStatusLabelV198(p.status)+'</span></div>'+programActionsV195(p)+'</div>').join('')+(rows.length?'':'<p class="muted">Aucun programme pour ces filtres.</p>')+'</div>';
}
function pilotControlsV12(s,e){
 return '<div class="card pilotage-head-v208"><div class="toolbar"><div><h2>Pilotage & statistiques</h2><p class="muted">'+s+' → '+e+'</p></div><div class="pilot-export-icons-v208"><button class="ghost pilot-icon-v208" title="Exporter Excel" aria-label="Exporter Excel" onclick="exportPilotageExcel()">▦</button><button class="ghost pilot-icon-v208" title="Exporter PDF" aria-label="Exporter PDF" onclick="exportPilotagePDF()">⇩</button></div></div><div class="pilot-filter-v208"><div class="period-tabs">'+[['week','Semaine'],['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année']].map(([v,l])=>'<button class="'+(statsPeriod===v?'active':'')+'" onclick="setStatsPeriod(\''+v+'\')">'+l+'</button>').join('')+'<button class="'+(statsPeriod==='custom'?'active':'')+'" onclick="statsPeriod=\'custom\';render()">Personnalisée</button></div><label class="pilot-compare-v208"><input type="checkbox" '+(statsCompare?'checked':'')+' onchange="statsCompare=this.checked;render()"> Comparer à la période précédente</label><div id="customStats" class="finder-search '+(statsPeriod==='custom'?'':'hidden')+'"><input id="statsStart" type="date" value="'+(statsCustomStart||s)+'"><input id="statsEnd" type="date" value="'+(statsCustomEnd||e)+'"><button class="primary" onclick="setCustomStats()">Appliquer</button></div></div>'+pilotCompareLabelV12(s,e)+'<div class="pilot-nav-wrap-v189">'+pilotTabsV12()+'</div></div>';
}
function openScheduleChangeSheetV195(kind,id,action){
  const obj=db[kind==='meeting'?'meetings':'programs'].find(x=>+x.id===+id);if(!obj)return;const cancel=action==='cancelled';
  modal.innerHTML='<div class="modal-card wide schedule-sheet-v183"><button class="close" onclick="closeModal()">×</button><div class="report-hero"><div><p class="eyebrow">'+(cancel?'ANNULATION':'REPORT')+'</p><h2>'+(cancel?'Annuler':'Reporter')+' — '+esc(obj.title)+'</h2><p class="muted">Date actuelle : '+new Date(obj.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+'</p></div></div><div class="report-section"><h3>'+(cancel?'Informations sur l’annulation':'Nouvelle programmation')+'</h3>'+(cancel?'':'<div class="form-row"><label>Nouvelle date *<input id="scNewDate" type="date" value="'+obj.scheduled_date+'"></label>'+(kind==='program'?'<label>Nouvelle date de fin<input id="scNewEnd" type="date" value="'+(obj.end_date||obj.scheduled_date)+'"></label>':'')+'</div>')+'<label>Motif *<select id="scReasonType"><option value="">Choisir un motif</option><option>Indisponibilité des responsables</option><option>Lieu indisponible</option><option>Contrainte d’organisation</option><option>Conflit de calendrier</option><option>Faible disponibilité des participants</option><option>Cas de force majeure</option><option>Autre</option></select></label><label>Précisions *<textarea id="scReason" rows="4"></textarea></label><label>Consigne / information à communiquer<textarea id="scNote" rows="3"></textarea></label></div><div class="report-savebar"><button class="ghost" onclick="closeModal()">Retour</button><button class="'+(cancel?'danger':'primary')+'" onclick="saveScheduleChangeV195(\''+kind+'\','+id+',\''+action+'\',this)">'+(cancel?'Confirmer l’annulation':'Confirmer le report')+'</button></div></div>';modal.classList.remove('hidden');
}
async function saveScheduleChangeV195(kind,id,action,btn){
  const obj=db[kind==='meeting'?'meetings':'programs'].find(x=>+x.id===+id),type=scReasonType.value,details=scReason.value.trim(),note=scNote.value.trim();if(!type||!details)return alert('Le motif et les précisions sont obligatoires.');
  const newDate=action==='postponed'?scNewDate.value:null,newEnd=action==='postponed'&&kind==='program'?scNewEnd.value:null;if(action==='postponed'&&!newDate)return alert('La nouvelle date est obligatoire.');if(newEnd&&newEnd<newDate)return alert('La date de fin ne peut pas précéder la date de début.');
  btn.disabled=true;try{const reason=type+' — '+details+(note?' — Information : '+note:'');let q=await sb.from('schedule_changes').insert({[kind+'_id']:id,action,old_date:obj.scheduled_date,new_date:newDate,reason});if(q.error)throw q.error;const patch={status:action==='cancelled'?'cancelled':'postponed'};if(newDate)patch.scheduled_date=newDate;if(kind==='program'&&newEnd)patch.end_date=newEnd;q=await sb.from(kind==='meeting'?'meetings':'programs').update(patch).eq('id',id);if(q.error)throw q.error;closeModal();await loadData();render()}catch(e){alert(e.message||'Modification impossible.')}finally{btn.disabled=false}
}
scheduleChange=function(kind,id,action){openScheduleChangeSheetV195(kind,id,action)}

/* Reporting — propriété consolidée dans app-final.js. */
