/* Application FI — couche finale consolidée. Aucun wrapper de version historique ne doit être chargé après ce fichier. */
(function(){
 window.statusLabel=function(s){return({scheduled:'Prévue',completed:'Terminée',cancelled:'Annulée',postponed:'Reportée',active:'Active'}[s]||s||'Prévue')};
 window.runSafeAction=async function(btn,work,label='Enregistrement…'){if(btn?.dataset.busy==='1')return;if(btn){btn.dataset.busy='1';btn.disabled=true;btn.dataset.oldText=btn.textContent;btn.textContent=label}try{return await work()}catch(e){console.error(e);alert(e?.message||'Une erreur est survenue.');throw e}finally{if(btn){btn.dataset.busy='0';btn.disabled=false;btn.textContent=btn.dataset.oldText||'Enregistrer'}}};
 const baseDashboard=dashboard;
 dashboard=function(){const people=typeof pilotPeopleStatsV12==='function'?pilotPeopleStatsV12('1900-01-01','2999-12-31'):{newcomers:[],visitors:[]};return `<div class="grid"><div class="card metric clickable" onclick="familyTab='FI';go('FI & FIJ')"><span>FI</span><strong>${db.families.filter(f=>f.family_type==='FI').length}</strong></div><div class="card metric clickable" onclick="familyTab='FIJ';go('FI & FIJ')"><span>FIJ</span><strong>${db.families.filter(f=>f.family_type==='FIJ').length}</strong></div><div class="card metric clickable" onclick="go('Membres')"><span>Membres</span><strong>${db.members.filter(m=>m.active!==false).length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Présences enregistrées</span><strong>${db.attendance.filter(a=>a.present).length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Nouveaux / sans rattachement</span><strong>${people.newcomers.length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Visiteurs</span><strong>${people.visitors.length}</strong></div></div><div class="section-grid"><div class="card"><h2>Modèles hebdomadaires</h2>${db.templates.map(t=>`<div class="family-row clickable" onclick="openTemplate(${t.id})"><div><b>${esc(t.name)}</b><div class="muted">Configurer et consulter l’historique</div></div><span class="pill ${t.family_type.toLowerCase()}">${t.family_type}</span></div>`).join('')}</div><div class="card clickable" onclick="go('Planning')"><h2>Planning</h2><p class="muted">Rencontres, programmes, événements et pauses.</p></div></div>`};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.busy==='1'){e.preventDefault();e.stopImmediatePropagation()}},true);
})();


/* Reporting — module canonique consolidé. */
/* v199 — reporting filtrable par état, période, FI/FIJ et type */
let reportingPhaseV198='pending',reportingPeriodV198='month',reportingFamilyV198='all',reportingTypeV199='all',reportingSelectionV223=new Set();
function setReportingPhaseV198(v){reportingPhaseV198=v;reportingSelectionV223.clear();render()} function setReportingPeriodV198(v){reportingPeriodV198=v;reportingSelectionV223.clear();render()} function setReportingFamilyV198(v){reportingFamilyV198=v;reportingSelectionV223.clear();render()} function setReportingTypeV199(v){reportingTypeV199=v;reportingSelectionV223.clear();render()}
function reportingPeriodSelectV240(value,setter){const opts=[['week','Semaine'],['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année']];return '<label>Période<select onchange="'+setter+'(this.value)">'+opts.map(([v,l])=>'<option value="'+v+'" '+(value===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label>'}

function canRemindReportingV223(fid){if(typeof isDirection==='function'&&isDirection())return true;return (typeof roles!=='undefined'?roles:[]).filter(r=>r.active!==false&&+r.family_id===+fid).some(r=>(typeof actionScopeV5==='function'?actionScopeV5(r.role,'notifications.reporting.remind'):'none')!=='none')}
function toggleReportingSelectV223(id,on){on?reportingSelectionV223.add(+id):reportingSelectionV223.delete(+id);render()}
async function remindReportingV223(id){try{const q=await sb.rpc('remind_reporting',{p_meeting:+id});if(q.error)throw q.error;alert(q.data?'Relance envoyée aux responsables concernés.':'Aucune relance nécessaire.')}catch(e){alert(typeof frenchError==='function'?frenchError(e):'Relance impossible.')}}
async function remindSelectedReportingV223(){const ids=[...reportingSelectionV223];if(!ids.length)return;if(!confirm('Envoyer une relance pour les Reporting sélectionnés ?'))return;let ok=0;for(const id of ids){const q=await sb.rpc('remind_reporting',{p_meeting:+id});if(!q.error)ok++}reportingSelectionV223.clear();alert(ok+' relance(s) traitée(s).');render()}
reportingPage=function(){
  const reports=Array.isArray(db.reports)?db.reports:[],meetings=Array.isArray(db.meetings)?db.meetings:[],programs=Array.isArray(db.programs)?db.programs:[],days=Array.isArray(db.programDays)?db.programDays:[];
  try{
    const nowDate=new Date(), now=Date.now();let from,to;switch(reportingPeriodV198){case 'week':{const d=new Date(nowDate);const day=(d.getDay()+6)%7;from=new Date(d.getFullYear(),d.getMonth(),d.getDate()-day);to=new Date(from);to.setDate(from.getDate()+6);break;}case 'quarter':{const q=Math.floor(nowDate.getMonth()/3);from=new Date(nowDate.getFullYear(),q*3,1);to=new Date(nowDate.getFullYear(),q*3+3,0);break;}case 'semester':{const m=nowDate.getMonth()<6?0:6;from=new Date(nowDate.getFullYear(),m,1);to=new Date(nowDate.getFullYear(),m+6,0);break;}case 'year':from=new Date(nowDate.getFullYear(),0,1);to=new Date(nowDate.getFullYear(),11,31);break;case 'season':{const seasons=(typeof fiExtra!=='undefined'&&fiExtra.seasons)||[];const s=seasons.find(x=>x.active&&x.starts_on<=dateISO(nowDate)&&x.ends_on>=dateISO(nowDate))||seasons.filter(x=>x.active).sort((a,b)=>b.starts_on.localeCompare(a.starts_on))[0];if(s){from=new Date(s.starts_on+'T00:00:00');to=new Date(s.ends_on+'T23:59:59')}else{from=new Date(nowDate.getFullYear(),0,1);to=new Date(nowDate.getFullYear(),11,31)}break;}default:from=new Date(nowDate.getFullYear(),nowDate.getMonth(),1);to=new Date(nowDate.getFullYear(),nowDate.getMonth()+1,0)}const si=dateISO(from),ei=dateISO(to);
    const meetingRows=meetings.filter(m=>m.reporting_required!==false&&m.status!=='cancelled'&&m.scheduled_date>=si&&m.scheduled_date<=ei).filter(m=>new Date(m.planned_end||m.planned_start||m.scheduled_date+'T23:59:59').getTime()<=now).map(m=>{const r=reports.find(x=>+x.meeting_id===+m.id),n=(db.attendance||[]).filter(a=>+a.meeting_id===+m.id&&a.present).length,remind=!r&&canRemindReportingV223(m.family_id);return{type:m.template_version_id?'weekly':'exceptional',date:m.scheduled_date,family_id:m.family_id,done:!!r,doneAt:r?.updated_at||r?.submitted_at||null,id:m.id,html:()=>'<div class="family-row reporting-row-v223">'+(remind?'<label onclick="event.stopPropagation()"><input type="checkbox" '+(reportingSelectionV223.has(+m.id)?'checked':'')+' onchange="toggleReportingSelectV223('+m.id+',this.checked)"></label>':'')+'<div class="clickable" onclick="'+(r?(permissionAllowsV207(reportingKeyV207(m,'create'),m.family_id)?'openReporting('+m.id+')':'openReportingReadV207('+m.id+')'):'openReporting('+m.id+')')+'"><b>'+esc(m.title||'Rencontre')+'</b><div class="muted">'+new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+' · '+esc(familyName(m.family_id))+' · '+n+' présent(s)'+(r?.submitted_at||r?.updated_at?' · enregistré le '+new Date(r.updated_at||r.submitted_at).toLocaleString('fr-FR'):'')+'</div></div><div class="reporting-actions-v223"><span class="pill">'+(r?.status||'À compléter')+'</span>'+(remind?'<button class="ghost" onclick="remindReportingV223('+m.id+')">Relancer</button>':'')+'</div></div>'}});
    const programRows=[];
    if(typeof isPrayerProgram==='function'&&typeof programTargetFamilies==='function')programs.filter(p=>p.status!=='cancelled').forEach(p=>{let prayer=false;try{prayer=!!isPrayerProgram(p)}catch(e){}if(!prayer)return;let fams=[];try{fams=programTargetFamilies(p)||[]}catch(e){fams=[]}const ds=days.filter(d=>+d.program_id===+p.id&&d.program_date>=si&&d.program_date<=ei);(ds.length?ds:[{id:null,program_date:p.scheduled_date,ends_at:null}]).forEach(d=>{const ended=d.ends_at?new Date(d.program_date+'T'+String(d.ends_at).slice(0,8)).getTime()<=now:d.program_date<dateISO(new Date());if(!ended)return;fams.forEach(f=>{const pr=typeof prayerData!=='undefined'&&Array.isArray(prayerData.reports)?prayerData.reports.find(r=>+r.program_id===+p.id&&(+r.program_day_id||0)===(+d.id||0)&&+r.family_id===+f.id):null,n=(db.attendance||[]).filter(a=>+a.program_id===+p.id&&+a.family_id===+f.id&&a.present&&(!d.id||+a.program_day_id===+d.id)).length;programRows.push({type:'program',date:d.program_date,family_id:f.id,done:!!pr,doneAt:pr?.updated_at||pr?.submitted_at||null,id:p.id,html:()=>'<div class="family-row clickable" onclick="openPrayerProgramReporting('+p.id+','+(d.id||'null')+','+f.id+')"><div><b>'+esc(p.title||'Programme')+'</b><div class="muted">'+new Date(d.program_date+'T12:00').toLocaleDateString('fr-FR')+' · '+esc(f.name||familyName(f.id))+' · '+n+' présent(s)'+(pr?.submitted_at||pr?.updated_at?' · enregistré le '+new Date(pr.updated_at||pr.submitted_at).toLocaleString('fr-FR'):'')+'</div></div><span class="pill">'+(pr?.status||'À compléter')+'</span></div>'})})})});
    const all=meetingRows.concat(programRows),fams=[...new Map(all.filter(x=>x.family_id).map(x=>[x.family_id,{id:x.family_id,name:familyName(x.family_id)}])).values()].sort((a,b)=>String(a.name).localeCompare(String(b.name),'fr')),rows=all.filter(x=>(reportingPhaseV198==='all'||(reportingPhaseV198==='done'?x.done:!x.done))&&(reportingFamilyV198==='all'||+x.family_id===+reportingFamilyV198)&&(reportingTypeV199==='all'||x.type===reportingTypeV199)).sort((a,b)=>(b.done-a.done)||(String(b.doneAt||'').localeCompare(String(a.doneAt||'')))||String(b.date).localeCompare(String(a.date)));
    return '<div class="card page-card"><div class="toolbar"><div><h2>Reporting</h2><p class="muted">Les Reporting complétés apparaissent en premier, avec leur date d’enregistrement.</p></div></div><div class="meeting-subtabs-v180"><button class="'+(reportingPhaseV198==='pending'?'active':'')+'" onclick="setReportingPhaseV198(\'pending\')">À compléter</button><button class="'+(reportingPhaseV198==='done'?'active':'')+'" onclick="setReportingPhaseV198(\'done\')">Complétés</button><button class="'+(reportingPhaseV198==='all'?'active':'')+'" onclick="setReportingPhaseV198(\'all\')">Tous</button></div><div class="compact-filters-v180">'+reportingPeriodSelectV240(reportingPeriodV198,'setReportingPeriodV198')+'<label>Type<select onchange="setReportingTypeV199(this.value)"><option value="all">Tous les types</option><option value="weekly">Rencontres hebdomadaires</option><option value="exceptional">Rencontres exceptionnelles</option><option value="program">Programmes</option></select></label><label>FI / FIJ<select onchange="setReportingFamilyV198(this.value)"><option value="all">Toutes</option>'+fams.map(f=>'<option value="'+f.id+'" '+(+reportingFamilyV198===+f.id?'selected':'')+'>'+esc(f.name)+'</option>').join('')+'</select></label></div>'+(reportingPhaseV198!=='done'?'<div class="reporting-bulk-v223"><button class="primary" '+(reportingSelectionV223.size?'':'disabled')+' onclick="remindSelectedReportingV223()">Relancer la sélection ('+reportingSelectionV223.size+')</button></div>':'')+(rows.map(x=>x.html()).join('')||'<p class="muted">Aucun Reporting pour ces filtres.</p>')+'</div>';
  }catch(e){console.error('[FI] Reporting render error',e);return '<div class="card page-card"><h2>Reporting</h2><p class="muted">Le module Reporting ne peut pas être affiché pour le moment.</p><button class="ghost" onclick="render()">Réessayer</button></div>';}
};
