/* Application FI — couche finale consolidée. Aucun wrapper de version historique ne doit être chargé après ce fichier. */
(function(){
 window.statusLabel=function(s){return({scheduled:'Prévue',completed:'Terminée',cancelled:'Annulée',postponed:'Reportée',active:'Active'}[s]||s||'Prévue')};
 window.runSafeAction=async function(btn,work,label='Enregistrement…'){if(btn?.dataset.busy==='1')return;if(btn){btn.dataset.busy='1';btn.disabled=true;btn.dataset.oldText=btn.textContent;btn.textContent=label}try{return await work()}catch(e){console.error(e);alert(e?.message||'Une erreur est survenue.');throw e}finally{if(btn){btn.dataset.busy='0';btn.disabled=false;btn.textContent=btn.dataset.oldText||'Enregistrer'}}};
 const baseDashboard=dashboard;
 dashboard=function(){const people=typeof pilotPeopleStatsV12==='function'?pilotPeopleStatsV12('1900-01-01','2999-12-31'):{newcomers:[],visitors:[]};return `<div class="grid"><div class="card metric clickable" onclick="familyTab='FI';go('FI & FIJ')"><span>FI</span><strong>${db.families.filter(f=>f.family_type==='FI').length}</strong></div><div class="card metric clickable" onclick="familyTab='FIJ';go('FI & FIJ')"><span>FIJ</span><strong>${db.families.filter(f=>f.family_type==='FIJ').length}</strong></div><div class="card metric clickable" onclick="go('Membres')"><span>Membres</span><strong>${db.members.filter(m=>m.active!==false).length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Présences enregistrées</span><strong>${db.attendance.filter(a=>a.present).length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Nouveaux / sans rattachement</span><strong>${people.newcomers.length}</strong></div><div class="card metric clickable" onclick="go('Pilotage')"><span>Visiteurs</span><strong>${people.visitors.length}</strong></div></div><div class="section-grid"><div class="card"><h2>Modèles hebdomadaires</h2>${db.templates.map(t=>`<div class="family-row clickable" onclick="openTemplate(${t.id})"><div><b>${esc(t.name)}</b><div class="muted">Configurer et consulter l’historique</div></div><span class="pill ${t.family_type.toLowerCase()}">${t.family_type}</span></div>`).join('')}</div><div class="card clickable" onclick="go('Planning')"><h2>Planning</h2><p class="muted">Rencontres, programmes, événements et pauses.</p></div></div>`};
 const attendanceCore=saveMeetingAttendance;
 saveMeetingAttendance=async function(id,live,btn){return runSafeAction(btn,()=>attendanceCore(id,live),'Enregistrement…')};
 const attendanceOpen=openAttendance;
 openAttendance=function(kind,id){attendanceOpen(kind,id);if(kind==='meeting'){const b=[...modal.querySelectorAll('button')].find(x=>x.textContent.includes('Enregistrer les présences'));if(b)b.onclick=()=>saveMeetingAttendance(id,attendanceWindow(db.meetings.find(x=>+x.id===+id)),b)}};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.busy==='1'){e.preventDefault();e.stopImmediatePropagation()}},true);
})();
