const SUPABASE_URL='https://uaxjqsocbegjappkjscs.supabase.co';
const SUPABASE_KEY='sb_publishable_lS_d8jGZc9ioVDVy_NYHfA_MCnDGmY-';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const ROLE_LABELS={pasteur:'Pasteur',super_admin:'Super Admin',responsable_fi:'Responsable FI',responsable_fij:'Responsable FIJ',coordinateur_fi:'Coordinateur FI',coordinateur_fij:'Coordinateur FIJ',pilote:'Pilote',copilote:'Copilote'};
const items=['Tableau de bord','Planning','FI & FIJ','Membres','Rencontres','Programmes & événements','Reporting','Carte','Pilotage','Paramètres'];
const icons=['▦','▣','⌂','♙','◷','◆','✓','⌖','⌁','⚙'];
const SECTEURS=['Centre-ville','Gare','Miroir','Bollée','Glonnières','Sablons','Université','Heuzé - Saint-Georges','Maillets - Bellevue','Villaret - Madeleine','Pontlieue','Batignolles','Maroc - Pavoine','Riffaudières','Banjan - Fontenelles','Gallière','Vauguyon','Oasis','Allonnes','Arnage','Coulaines','Yvré-l’Évêque','Rouillon','La Chapelle-Saint-Aubin','Saint-Saturnin'];
const SECTOR_COORDS={Gare:[47.995,0.192],Miroir:[47.989,0.188],'Bollée':[48.002,0.218],'Glonnières':[47.975,0.205],Sablons:[47.990,0.224],'Université':[48.019,0.155],Allonnes:[47.968,0.160],Arnage:[47.926,0.188],Heuzé:[48.011,0.229],'Heuzé - Saint-Georges':[48.011,0.229]};
let current='Tableau de bord',familyTab='FI',session=null,profile=null,roles=[],allRoles=[],mapInstance=null,calDate=new Date(),realtimeChannel=null;
let db={families:[],members:[],assignments:[],meetings:[],programs:[],reports:[],followups:[],templates:[],versions:[],pauses:[],programDays:[],changes:[],settings:[],attendance:[],targets:[],children:[],childGuardians:[],childAttendance:[],leadershipTraining:[],familyHosts:[]};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateISO=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const memberName=id=>{const m=db.members.find(x=>String(x.id)===String(id));return m?[m.first_name,m.last_name].filter(Boolean).join(' '):'—'};
const familyName=id=>db.families.find(x=>String(x.id)===String(id))?.name||'—';
function frenchError(e){const s=String(e?.message||e||'').toLowerCase();if(s.includes('schedule_changes_action_check'))return 'Cette modification de rencontre n’a pas pu être enregistrée. Réessayez après actualisation.';if(s.includes('no unique or exclusion constraint')||s.includes('on conflict'))return 'Cette rencontre n’a pas pu être préparée correctement. Actualisez puis réessayez.';if(s.includes('permission denied')||s.includes('row-level security')||s.includes('rls'))return 'Vous n’avez pas les droits nécessaires pour effectuer cette action.';if(s.includes('email not confirmed'))return 'Votre adresse e-mail n’est pas encore validée.';if(s.includes('invalid login credentials'))return 'Adresse e-mail ou mot de passe incorrect.';if(s.includes('user already registered'))return 'Un compte existe déjà avec cette adresse e-mail.';if(s.includes('password should be'))return 'Le mot de passe ne respecte pas les critères de sécurité.';if(s.includes('rate limit')||s.includes('too many requests'))return 'Trop de tentatives. Patientez quelques instants puis réessayez.';if(s.includes('failed to fetch')||s.includes('network'))return 'Connexion au serveur impossible. Vérifiez votre connexion internet puis réessayez.';return 'Une erreur est survenue. Réessayez ou contactez l’administration si le problème persiste.'}
function showAuth(mode,btn){document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');authForm.innerHTML=mode==='login'?`<div class="form-stack"><input id="loginEmail" type="email" placeholder="Adresse e-mail"><input id="loginPassword" type="password" placeholder="Mot de passe"><button class="primary" onclick="login()">Se connecter</button><button class="ghost" onclick="showAuth('forgot')">Mot de passe oublié ?</button></div>`:mode==='signup'?`<div class="form-stack"><input id="signupName" placeholder="Prénom et nom"><input id="signupEmail" type="email" placeholder="Adresse e-mail"><input id="signupPassword" type="password" placeholder="Mot de passe"><button class="primary" onclick="signup()">Créer mon compte</button></div>`:`<div class="form-stack"><input id="forgotEmail" type="email" placeholder="Adresse e-mail"><button class="primary" onclick="forgot()">Envoyer le lien</button><button class="ghost" onclick="showAuth('login')">Retour</button></div>`}
async function signup(){const {data,error}=await sb.auth.signUp({email:signupEmail.value.trim().toLowerCase(),password:signupPassword.value,options:{data:{full_name:signupName.value.trim()},emailRedirectTo:location.origin+location.pathname}});if(error)return alert(frenchError(error));if(data.session)boot();else{alert('Compte créé. Vous pouvez maintenant vous connecter.');showAuth('login')}}
async function login(){const {error}=await sb.auth.signInWithPassword({email:loginEmail.value.trim().toLowerCase(),password:loginPassword.value});if(error)return alert(frenchError(error));boot()}
async function forgot(){const {error}=await sb.auth.resetPasswordForEmail(forgotEmail.value.trim().toLowerCase(),{redirectTo:location.origin+location.pathname});if(error)return alert(frenchError(error));alert('Lien de réinitialisation envoyé.');showAuth('login')}
async function logout(){await sb.auth.signOut();location.reload()}
function isDirection(){return roles.some(r=>['pasteur','super_admin'].includes(r.role))}
function allowedItems(){return isDirection()?items:items.filter(x=>x!=='Paramètres')}
async function loadProfile(){const {data:p,error}=await sb.from('app_profiles').select('*').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(!p)throw Error('Cette adresse e-mail n’est pas associée à un accès autorisé.');const [{data:m,error:me},{data:r,error:re}]=await Promise.all([sb.from('members').select('*').eq('id',p.member_id).single(),sb.from('role_assignments').select('*').eq('member_id',p.member_id).eq('active',true)]);if(me)throw me;if(re)throw re;profile={...p,member:m};roles=r||[]}
async function loadData(){const qs=await Promise.all([sb.from('families').select('*').order('name'),sb.from('members').select('*').order('last_name'),sb.from('member_assignments').select('*'),sb.from('meetings').select('*').order('scheduled_date'),sb.from('programs').select('*').order('scheduled_date'),sb.from('reporting').select('*'),sb.from('followups').select('*'),sb.from('meeting_templates').select('*').order('family_type'),sb.from('meeting_template_versions').select('*').order('effective_from'),sb.from('calendar_pauses').select('*').eq('active',true),sb.from('program_days').select('*'),sb.from('schedule_changes').select('*'),sb.from('app_settings').select('*'),sb.from('attendance').select('*'),sb.from('program_family_targets').select('*'),sb.from('child_dependents').select('*'),sb.from('child_guardians').select('*'),sb.from('child_attendance').select('*'),sb.from('leadership_training').select('*'),sb.from('family_hosts').select('*')]);const er=qs.find(q=>q.error)?.error;if(er)throw er;[db.families,db.members,db.assignments,db.meetings,db.programs,db.reports,db.followups,db.templates,db.versions,db.pauses,db.programDays,db.changes,db.settings,db.attendance,db.targets,db.children,db.childGuardians,db.childAttendance,db.leadershipTraining,db.familyHosts]=qs.map(q=>q.data||[]);{const {data,error}=await sb.from('role_assignments').select('*').eq('active',true);if(error)throw error;allRoles=data||[]}}
async function boot(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(!s){authGate.classList.remove('hidden');workspace.classList.add('hidden');showAuth('login');return}try{await loadProfile();await loadData();authGate.classList.add('hidden');workspace.classList.remove('hidden');const n=[profile.member.first_name,profile.member.last_name].filter(Boolean).join(' ')||s.user.email;userName.textContent=n;userRole.textContent=ROLE_LABELS[roles[0]?.role]||'Accès FI';avatar.textContent=n[0]?.toUpperCase()||'A';navMenu();render();subscribeRealtime()}catch(e){console.error(e);alert(frenchError(e))}}
function subscribeRealtime(){if(realtimeChannel)return;realtimeChannel=sb.channel('fi-live');['families','members','member_assignments','meetings','programs','reporting','meeting_templates','meeting_template_versions','calendar_pauses','program_days','schedule_changes','app_settings','role_assignments','attendance','program_family_targets','child_dependents','child_guardians','child_attendance','family_hosts'].forEach(table=>realtimeChannel.on('postgres_changes',{event:'*',schema:'public',table},async()=>{await loadData();render()}));realtimeChannel.subscribe()}
function navMenu(){nav.innerHTML=allowedItems().map(x=>`<button class="${x===current?'active':''}" onclick="go('${x}')">${icons[items.indexOf(x)]} &nbsp;<span>${x}</span></button>`).join('')}
function go(x){const canOpen=items.includes(x)&&(x!=='Paramètres'||isDirection());current=canOpen?x:'Tableau de bord';pageTitle.textContent=current;navMenu();closeModal();render()}
function closeModal(){modal.classList.add('hidden');modal.innerHTML=''}
function modalForm(title,fields,save){modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>${title}</h2><div class="form-stack">${fields}<button class="primary" id="modalSave">Enregistrer</button></div></div>`;modal.classList.remove('hidden');modalSave.onclick=async()=>{modalSave.disabled=true;try{await save();closeModal();await loadData();render()}catch(e){console.error(e);alert(frenchError(e))}finally{if(window.modalSave)modalSave.disabled=false}}}
const famOpts=(type='')=>`<option value="">Sans FI/FIJ</option>`+db.families.filter(f=>!type||f.family_type===type).map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');
function dashboard(){return `<div class="grid"><div class="card metric"><span>FI</span><strong>${db.families.filter(f=>f.family_type==='FI').length}</strong></div><div class="card metric"><span>FIJ</span><strong>${db.families.filter(f=>f.family_type==='FIJ').length}</strong></div><div class="card metric"><span>Membres</span><strong>${db.members.length}</strong></div><div class="card metric clickable" onclick="openDashboardAttendanceV214()"><span>Présences enregistrées</span><strong>${db.attendance.filter(a=>a.present&&a.meeting_id).length}</strong></div></div><div class="section-grid"><div class="card"><h2>Modèles hebdomadaires</h2>${db.templates.map(t=>`<div class="family-row clickable" onclick="openTemplate(${t.id})"><div><b>${esc(t.name)}</b><div class="muted">Configurer et consulter l’historique</div></div><span class="pill ${t.family_type.toLowerCase()}">${t.family_type}</span></div>`).join('')}</div><div class="card clickable" onclick="go('Planning')"><h2>Planning</h2><p class="muted">Rencontres, programmes, événements et pauses.</p></div></div>`}
function familyPage(){const list=db.families.filter(f=>f.family_type===familyTab);return `<div class="card page-card"><div class="toolbar"><div class="subtabs"><button class="${familyTab==='FI'?'active':''}" onclick="familyTab='FI';render()">FI</button><button class="${familyTab==='FIJ'?'active':''}" onclick="familyTab='FIJ';render()">FIJ</button></div>${isDirection()?`<button class="primary" onclick="formFamily('${familyTab}')">＋ Nouvelle ${familyTab}</button>`:''}</div>${list.map(f=>`<div class="family-row clickable" onclick="openFamily(${f.id})"><div><b>${esc(f.name)}</b><div class="muted">${esc(f.neighborhood||'Secteur à préciser')} · ${esc(f.status||'Active')}</div></div><span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span></div>`).join('')}</div>`}
function openFamily(id){const f=db.families.find(x=>x.id===id),aa=db.assignments.filter(a=>a.family_id===id&&!a.ends_at),rr=allRoles.filter(r=>r.family_id===id);modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span><h2>${esc(f.name)}</h2><p>${esc(f.address||f.neighborhood||'Localisation à préciser')}</p><h3>Responsables</h3><p>Pilote : <b>${memberName(rr.find(r=>r.role==='pilote')?.member_id)}</b><br>Copilote 1 : <b>${memberName(rr.find(r=>r.role==='copilote'&&r.copilot_slot===1)?.member_id)}</b><br>Copilote 2 : <b>${memberName(rr.find(r=>r.role==='copilote'&&r.copilot_slot===2)?.member_id)}</b></p><h3>Membres (${aa.length})</h3>${aa.map(a=>`<div>${esc(memberName(a.member_id))}</div>`).join('')||'<p class="muted">Aucun membre</p>'}</div>`;modal.classList.remove('hidden')}
function formFamily(type){modalForm(`Nouvelle ${type}`,`<input id="fName" placeholder="Nom"><input id="fHost" placeholder="Hôte"><input id="fAddress" placeholder="Adresse"><select id="fSector"><option value="">Secteur</option>${SECTEURS.map(s=>`<option>${s}</option>`).join('')}</select>`,async()=>{const {error}=await sb.from('families').insert({name:fName.value.trim(),family_type:type,host_name:fHost.value.trim()||null,address:fAddress.value.trim()||null,neighborhood:fSector.value||null,status:'Active'});if(error)throw error})}
function membersPage(){
 const active=db.members.filter(m=>m.active!==false);
 const groups=new Map();
 active.forEach(m=>{const fid=typeof memberFamilyId==='function'?memberFamilyId(m.id):activeAssignmentFor(m.id)?.family_id||0;if(!groups.has(fid))groups.set(fid,[]);groups.get(fid).push(m)});
 const groupEntries=[...groups.entries()].sort((x,y)=>{
   const an=x[0]?familyName(x[0]):'Sans FI/FIJ',bn=y[0]?familyName(y[0]):'Sans FI/FIJ';
   return an.localeCompare(bn,'fr',{sensitivity:'base'});
 });
 const groupHtml=groupEntries.map(([fid,ms])=>{
   ms.sort((x,y)=>memberName(x.id).localeCompare(memberName(y.id),'fr',{sensitivity:'base'}));
   const f=fid?db.families.find(x=>+x.id===+fid):null;
   const type=f?.family_type||'';
   return '<section class="member-family-group-v236">'+
     '<div class="member-family-group-head-v236"><div><span class="pill '+(type?type.toLowerCase():'')+'">'+esc(type||'Sans rattachement')+'</span><h3>'+esc(f?.name||'Membres sans FI/FIJ')+'</h3></div><strong>'+ms.length+' membre'+(ms.length>1?'s':'')+'</strong></div>'+
     '<div class="member-family-list-v236">'+ms.map(m=>{
       const bd=typeof birthdayParts==='function'?birthdayParts(m):[];
       return '<div class="family-row clickable member-row-v236" onclick="openMember('+m.id+')"><div><b>'+esc(memberName(m.id))+'</b><div class="muted">'+esc(m.email||'')+'</div></div>'+
         (bd?.[0]?'<span>🎂 '+String(bd[1]).padStart(2,'0')+'/'+String(bd[0]).padStart(2,'0')+'</span>':'')+
       '</div>';
     }).join('')+'</div></section>';
 }).join('');
 return '<div class="card page-card"><div class="toolbar"><div><h2>Membres</h2><p class="muted">'+active.length+' membre'+(active.length>1?'s':'')+' · classés par FI/FIJ</p></div>'+
   (isDirection()?'<button class="primary" onclick="formMember()">＋ Nouveau membre</button>':'')+
   '</div>'+(groupHtml||'<p class="muted">Aucun membre actif.</p>')+'</div>';
}

function activeVersion(t,date){return db.versions.filter(v=>v.template_id===t.id&&v.effective_from<=date&&(!v.effective_to||v.effective_to>=date)).sort((a,b)=>b.effective_from.localeCompare(a.effective_from))[0]}
function isPaused(type,date){return db.pauses.some(p=>(p.scope==='BOTH'||p.scope===type)&&p.starts_on<=date&&p.ends_on>=date)}
function weeklyVirtualEvents(start,end){const out=[];for(const t of db.templates.filter(x=>x.active)){for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const iso=dateISO(d),v=activeVersion(t,iso);if(v&&d.getDay()===(v.weekday%7)&&!isPaused(t.family_type,iso))out.push({date:iso,type:t.family_type,title:v.title||t.name,time:(v.start_time||'').slice(0,5),virtual:true,template:t})}}return out}
function calMove(n){calDate=new Date(calDate.getFullYear(),calDate.getMonth()+n,1);render()}
function calToday(){calDate=new Date();render()}
function planning(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));const end=new Date(last);end.setDate(last.getDate()+(6-((last.getDay()+6)%7)));const ev=(typeof virtualOccurrences==='function'?virtualOccurrences(start,end):weeklyVirtualEvents(start,end));db.meetings.filter(x=>!x.template_version_id).forEach(x=>ev.push({date:x.scheduled_date,type:'meeting',title:x.title,status:x.status,id:x.id}));db.programs.forEach(p=>{const days=db.programDays.filter(d=>d.program_id===p.id);(days.length?days:[{program_date:p.scheduled_date}]).forEach(d=>ev.push({date:d.program_date,type:'program',title:p.title,status:p.status,id:p.id}))});let cells='';for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const iso=dateISO(d),inMonth=d.getMonth()===m,dayEv=ev.filter(e=>e.date===iso);cells+=`<div class="cal-cell ${inMonth?'':'outside'}"><b>${d.getDate()}</b>${dayEv.map(e=>`<div class="cal-event ${e.type==='FI'?'ev-fi':e.type==='FIJ'?'ev-fij':e.type==='program'?'ev-program':'ev-meeting'} ${e.status==='cancelled'?'ev-cancelled':''}" onclick="event.stopPropagation();${e.type==='program'?`openProgram(${e.id})`:e.id?`openMeeting(${e.id})`:`openTemplate(${e.template.id})`}">${e.time?e.time+' ':''}${esc(e.title)}</div>`).join('')}${db.pauses.filter(p=>p.starts_on<=iso&&p.ends_on>=iso).map(p=>`<div class="cal-event ev-pause">Pause ${p.scope}</div>`).join('')}</div>`}return `<div class="card"><div class="toolbar"><div><button class="ghost" onclick="calMove(-1)">‹</button> <button class="ghost" onclick="calToday()">Aujourd’hui</button> <button class="ghost" onclick="calMove(1)">›</button></div><h2>${calDate.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2></div><div class="legend"><span class="leg fi">FI</span><span class="leg fij">FIJ</span><span class="leg prog">Programme / événement</span><span class="leg meet">Rencontre exceptionnelle</span><span class="leg pause">Pause / vacances</span></div><div class="cal-head">${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<b>${x}</b>`).join('')}</div><div class="calendar">${cells}</div></div>`}
function formMeeting(){modalForm('Nouvelle rencontre',`<input id="rTitle" placeholder="Titre"><select id="rFamily">${famOpts()}</select><input id="rDate" type="date"><input id="rTime" type="time">`,async()=>{const {error}=await sb.from('meetings').insert({title:rTitle.value.trim(),meeting_kind:'Rencontre',family_id:rFamily.value?+rFamily.value:null,scheduled_date:rDate.value,planned_start:rTime.value?new Date(rDate.value+'T'+rTime.value).toISOString():null,status:'scheduled'});if(error)throw error})}
function openMeeting(id){const m=db.meetings.find(x=>x.id===id);modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>${esc(m.title)}</h2><p>${m.scheduled_date} · ${familyName(m.family_id)}</p><div class="row-actions"><button class="primary" onclick="openAttendance('meeting',${id})">✓ Gérer les présences</button><button class="ghost" onclick="scheduleChange('meeting',${id},'postponed')">Reporter</button><button class="ghost" onclick="scheduleChange('meeting',${id},'cancelled')">Annuler</button></div></div>`;modal.classList.remove('hidden')}
function programTargetFamilies(p){if(p.direction_only||p.leaders_only)return [];if(p.target_scope==='SELECTED')return db.targets.filter(t=>t.program_id===p.id).map(t=>db.families.find(f=>f.id===t.family_id)).filter(Boolean);return db.families.filter(f=>(p.include_fi&&f.family_type==='FI')||(p.include_fij&&f.family_type==='FIJ'))}
function formProgram(){modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>Nouveau programme / événement</h2><div class="form-stack"><input id="pTitle" placeholder="Titre"><select id="pKind"><option>Programme</option><option>Événement</option><option>Formation</option><option>Réunion</option></select><label><input type="checkbox" id="pDirectionOnly" onchange="syncProgramScope()"> Direction uniquement</label><label><input type="checkbox" id="pLeaders" onchange="syncProgramScope()"> Pilotes + Copilotes</label><div id="familyScope"><b>Périmètre familles</b><label><input type="checkbox" id="pFI" checked onchange="syncFamilyChoices()"> FI</label><label><input type="checkbox" id="pFIJ" checked onchange="syncFamilyChoices()"> FIJ</label><select id="pScope" onchange="syncFamilyChoices()"><option value="ALL_FAMILIES">Toutes les familles du périmètre</option><option value="SELECTED">Une ou plusieurs familles</option></select><div id="familyChoices"></div></div><input id="pStart" type="date"><input id="pEnd" type="date"><textarea id="pNotes" placeholder="Notes"></textarea><small class="muted">La Direction est toujours invitée. Pilotes et Copilotes sont gérés ensemble.</small><button class="primary" id="saveProgram">Enregistrer</button></div></div>`;modal.classList.remove('hidden');syncFamilyChoices();saveProgram.onclick=async()=>{if(saveProgram.dataset.busy==='1')return;saveProgram.dataset.busy='1';saveProgram.disabled=true;const oldText=saveProgram.textContent;saveProgram.textContent='Enregistrement…';try{if(!pTitle.value.trim()||!pStart.value)throw Error('Titre et date requis.');const direction=pDirectionOnly.checked,leaders=pLeaders.checked;const {data,error}=await sb.from('programs').insert({title:pTitle.value.trim(),kind:pKind.value,scheduled_date:pStart.value,end_date:pEnd.value||pStart.value,notes:pNotes.value.trim()||null,target_scope:direction||leaders?'NONE':pScope.value,include_fi:pFI.checked,include_fij:pFIJ.checked,leaders_only:leaders,direction_only:direction,status:'scheduled',audience:direction?'Direction':leaders?'Pilotes + Copilotes':'Familles'}).select('id').single();if(error)throw error;const dates=[];for(let d=new Date(pStart.value+'T12:00:00');d<=new Date((pEnd.value||pStart.value)+'T12:00:00');d.setDate(d.getDate()+1))dates.push({program_id:data.id,program_date:dateISO(d)});if(dates.length){const {error:e}=await sb.from('program_days').insert(dates);if(e)throw e}if(!direction&&!leaders&&pScope.value==='SELECTED'){const ids=[...document.querySelectorAll('.target-family:checked')].map(x=>+x.value);if(ids.length){const {error:e}=await sb.from('program_family_targets').insert(ids.map(family_id=>({program_id:data.id,family_id})));if(e)throw e}}closeModal();await loadData();render()}catch(e){alert(e.message)}finally{saveProgram.dataset.busy='0';saveProgram.disabled=false;saveProgram.textContent=oldText}}}
function syncProgramScope(){familyScope.style.display=(pDirectionOnly.checked||pLeaders.checked)?'none':'block';if(pDirectionOnly.checked)pLeaders.checked=false;else if(pLeaders.checked)pDirectionOnly.checked=false}
function syncFamilyChoices(){if(!window.familyChoices)return;const show=pScope.value==='SELECTED';familyChoices.style.display=show?'grid':'none';familyChoices.innerHTML=show?db.families.filter(f=>(pFI.checked&&f.family_type==='FI')||(pFIJ.checked&&f.family_type==='FIJ')).map(f=>`<label><input class="target-family" type="checkbox" value="${f.id}"> ${esc(f.name)}</label>`).join(''):''}
function openProgram(id){const p=db.programs.find(x=>x.id===id),families=programTargetFamilies(p);modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>${esc(p.title)}</h2><p>${p.scheduled_date}${p.end_date&&p.end_date!==p.scheduled_date?' → '+p.end_date:''}</p><p class="muted">${p.direction_only?'Direction uniquement':p.leaders_only?'Pilotes + Copilotes + Direction':families.length?families.map(f=>f.name).join(', '):'Toutes les familles concernées'}.</p><div class="row-actions"><button class="primary" onclick="openAttendance('program',${id})">✓ Gérer les présences</button>${isDirection()?`<button class="ghost" onclick="scheduleChange('program',${id},'postponed')">Reporter</button><button class="ghost" onclick="scheduleChange('program',${id},'cancelled')">Annuler</button>`:''}</div></div>`;modal.classList.remove('hidden')}
function myManagedFamilyIds(){if(isDirection())return db.families.map(f=>f.id);return [...new Set(roles.filter(r=>['pilote','copilote'].includes(r.role)&&r.family_id).map(r=>r.family_id))]}
function eligibleMembers(kind,id){if(kind==='meeting'){const m=db.meetings.find(x=>x.id===id);if(m.family_id)return db.assignments.filter(a=>a.family_id===m.family_id&&!a.ends_at).map(a=>db.members.find(x=>x.id===a.member_id)).filter(Boolean);return db.members}const p=db.programs.find(x=>x.id===id);if(p.direction_only)return isDirection()?db.members.filter(m=>allRoles.some(r=>r.member_id===m.id&&['pasteur','super_admin','responsable_fi','responsable_fij','coordinateur_fi','coordinateur_fij'].includes(r.role))):[];if(p.leaders_only)return isDirection()?db.members.filter(m=>allRoles.some(r=>r.member_id===m.id&&['pilote','copilote','pasteur','super_admin','responsable_fi','responsable_fij','coordinateur_fi','coordinateur_fij'].includes(r.role))):[];let fams=programTargetFamilies(p).map(f=>f.id);if(!isDirection())fams=fams.filter(id=>myManagedFamilyIds().includes(id));return db.assignments.filter(a=>fams.includes(a.family_id)&&!a.ends_at).map(a=>db.members.find(m=>m.id===a.member_id)).filter(Boolean)}
function memberFamilyId(memberId){return db.assignments.find(a=>a.member_id===memberId&&!a.ends_at)?.family_id||null}
async function scheduleChange(kind,id,action){const reason=prompt(action==='cancelled'?'Motif de l’annulation :':'Motif du report :');if(!reason)return;const table=kind==='meeting'?'meetings':'programs',obj=db[kind==='meeting'?'meetings':'programs'].find(x=>x.id===id);let newDate=null;if(action==='postponed'){newDate=prompt('Nouvelle date (AAAA-MM-JJ) :',obj.scheduled_date);if(!newDate)return}const change={[`${kind}_id`]:id,action,old_date:obj.scheduled_date,new_date:newDate,reason};const {error:e}=await sb.from('schedule_changes').insert(change);if(e)throw e;const {error}=await sb.from(table).update({status:action==='cancelled'?'cancelled':'postponed',...(newDate?{scheduled_date:newDate}: {})}).eq('id',id);if(error)throw error;closeModal();await loadData();render()}
function attendanceBlock(kind,id){const aa=db.attendance.filter(a=>a[`${kind}_id`]===id&&a.present);return `<div class="card"><h3>Présences (${aa.length})</h3>${aa.map(a=>`<div class="family-row"><span>${esc(memberName(a.member_id))}<small class="muted"> · ${esc(familyName(a.family_id))}</small></span><b>${a.arrival_unknown?'Heure non connue':a.arrival_time?.slice(0,5)||'Heure non renseignée'}</b></div>`).join('')||'<p class="muted">Aucune présence enregistrée.</p>'}<button class="ghost" onclick="openAttendance('${kind}',${id})">Gérer les présences</button></div>`}
function openReporting(id){const m=db.meetings.find(x=>x.id===id),r=db.reports.find(x=>x.meeting_id===id);modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><h2>Reporting — ${esc(m.title)}</h2>${attendanceBlock('meeting',id)}<div class="form-stack"><label>Programme respecté ?<select id="repRespected"><option value="true" ${r?.program_respected===true?'selected':''}>Oui</option><option value="false" ${r?.program_respected===false?'selected':''}>Configuration différente</option></select></label><select id="repAtmos"><option>Excellente</option><option>Bonne</option><option>Correcte</option><option>Mitigée</option><option>Difficile</option></select><select id="repUnderstand"><option>Très bon</option><option>Bon</option><option>Moyen</option><option>Difficile</option></select><textarea id="repNotes" placeholder="Notes">${esc(r?.notes||'')}</textarea><button class="primary" onclick="saveReporting(${id})">Enregistrer le Reporting</button></div></div>`;modal.classList.remove('hidden')}
async function saveReporting(id){const payload={meeting_id:id,status:'Validé',program_respected:repRespected.value==='true',atmosphere:repAtmos.value,understanding:repUnderstand.value,notes:repNotes.value.trim()||null};const existing=db.reports.find(r=>r.meeting_id===id);const q=existing?sb.from('reporting').update(payload).eq('id',existing.id):sb.from('reporting').insert(payload);const {error}=await q;if(error)throw error;closeModal();await loadData();render()}
function openTemplate(id){const t=db.templates.find(x=>x.id===id),vs=db.versions.filter(v=>v.template_id===id).sort((a,b)=>b.effective_from.localeCompare(a.effective_from));modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>${esc(t.name)}</h2><p class="muted">Une nouvelle configuration prend effet à une date donnée sans modifier l’historique.</p>${vs.map(v=>`<div class="family-row"><span>À partir du ${v.effective_from}</span><b>Jour ${v.weekday} · ${v.start_time?.slice(0,5)||''}</b></div>`).join('')||'<p class="muted">Aucun horaire configuré.</p>'}${isDirection()?`<button class="primary" onclick="formTemplateVersion(${id})">Nouvelle configuration</button>`:''}</div>`;modal.classList.remove('hidden')}
function formTemplateVersion(id){modalForm('Nouvelle configuration du modèle',`<input id="tvDate" type="date"><select id="tvDay"><option value="1">Lundi</option><option value="2">Mardi</option><option value="3">Mercredi</option><option value="4">Jeudi</option><option value="5">Vendredi</option><option value="6">Samedi</option><option value="7">Dimanche</option></select><input id="tvStart" type="time"><input id="tvEnd" type="time">`,async()=>{const previous=db.versions.filter(v=>v.template_id===id&&!v.effective_to&&v.effective_from<tvDate.value).sort((a,b)=>b.effective_from.localeCompare(a.effective_from))[0];if(previous){const d=new Date(tvDate.value+'T12:00:00');d.setDate(d.getDate()-1);await sb.from('meeting_template_versions').update({effective_to:dateISO(d)}).eq('id',previous.id)}const {error}=await sb.from('meeting_template_versions').insert({template_id:id,effective_from:tvDate.value,weekday:+tvDay.value,start_time:tvStart.value,end_time:tvEnd.value||null});if(error)throw error})}
function mapPage(){setTimeout(initMap,30);return `<div class="card"><div class="legend"><span class="leg fi">FI</span><span class="leg fij">FIJ</span></div><div id="lemansMap" style="height:620px;border-radius:14px"></div></div>`}
function initMap(){if(!document.getElementById('lemansMap'))return;if(mapInstance)mapInstance.remove();mapInstance=L.map('lemansMap').setView([48.006,0.199],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(mapInstance);db.families.forEach((f,i)=>{let pos=f.latitude&&f.longitude?[f.latitude,f.longitude]:SECTOR_COORDS[f.neighborhood]||[48.006+(i%5)*.003,0.199+Math.floor(i/5)*.004];const color=f.family_type==='FI'?'#4f46e5':'#be185d';L.circleMarker(pos,{radius:9,color,fillColor:color,fillOpacity:.85}).addTo(mapInstance).bindPopup(`<b>${esc(f.name)}</b><br>${f.family_type}<br>${esc(f.neighborhood||'Localisation à préciser')}`)})}
function settingsPage(){if(!isDirection())return '<div class="card">Accès réservé.</div>';const timing=db.settings.find(s=>s.key==='timing')?.value||{};return `<div class="section-grid"><div class="card"><h2>Calendrier & périodes</h2><button class="primary" onclick="formPause()">＋ Période de pause</button>${db.pauses.map(p=>`<div class="family-row"><span><b>${esc(p.name)}</b><small class="muted"> ${p.starts_on} → ${p.ends_on}</small></span><span>${p.scope}</span></div>`).join('')}</div><div class="card"><h2>Marges horaires</h2><p>Retard : <b>${timing.late_grace_minutes??5} min</b><br>Dépassement : <b>${timing.meeting_overrun_grace_minutes??10} min</b></p></div><div class="card"><h2>Administration & rôles</h2><p class="muted">Les droits sont déterminés par les responsabilités actives et sécurisés en base.</p>${allRoles.slice(0,20).map(r=>`<div class="family-row"><span>${esc(memberName(r.member_id))}</span><b>${ROLE_LABELS[r.role]||r.role}</b></div>`).join('')}</div><div class="card"><h2>Modèles</h2>${db.templates.map(t=>`<div class="family-row clickable" onclick="openTemplate(${t.id})"><b>${esc(t.name)}</b><span>${t.family_type}</span></div>`).join('')}</div></div>`}
function formPause(){modalForm('Période de pause / vacances',`<input id="paName" placeholder="Nom"><input id="paStart" type="date"><input id="paEnd" type="date"><select id="paScope"><option value="BOTH">FI + FIJ</option><option>FI</option><option>FIJ</option></select><textarea id="paReason" placeholder="Motif"></textarea>`,async()=>{const {error}=await sb.from('calendar_pauses').insert({name:paName.value.trim(),starts_on:paStart.value,ends_on:paEnd.value,scope:paScope.value,reason:paReason.value.trim()||null});if(error)throw error})}
function pilotage(){return `<div class="grid"><div class="card metric"><span>Présences</span><strong>${db.attendance.filter(a=>a.present).length}</strong></div><div class="card metric"><span>Reporting</span><strong>${db.reports.length}</strong></div><div class="card metric"><span>FI</span><strong>${db.families.filter(f=>f.family_type==='FI').length}</strong></div><div class="card metric"><span>FIJ</span><strong>${db.families.filter(f=>f.family_type==='FIJ').length}</strong></div></div>`}
function openQuick(){modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>Nouvelle action</h2><div class="action-grid"><button onclick="closeModal();formMeeting()">Rencontre</button>${isDirection()?'<button onclick="closeModal();formProgram()">Programme / événement</button>':''}<button onclick="closeModal();go('Planning')">Planning</button><button onclick="closeModal();go('Reporting')">Reporting</button></div></div>`;modal.classList.remove('hidden')}
function render(){const pages={'Tableau de bord':dashboard,'Planning':planning,'FI & FIJ':familyPage,'Membres':membersPage,'Rencontres':meetingsPage,'Programmes & événements':programsPage,'Reporting':reportingPage,'Carte':mapPage,'Pilotage':pilotage,'Paramètres':settingsPage};app.innerHTML='';try{app.innerHTML=(pages[current]||dashboard)()}catch(e){console.error('Rendu '+current,e);app.innerHTML='<div class="card"><h2>'+esc(current)+'</h2><p class="muted">Une erreur empêche momentanément l’affichage de ce module.</p></div>'}}
showAuth('login');boot();
function openDashboardAttendanceV214(){
 const groups=new Map();
 (db.attendance||[]).filter(a=>a.present&&a.meeting_id).forEach(a=>{const m=db.meetings.find(x=>+x.id===+a.meeting_id);if(!m)return;const fid=+a.family_id||+m.family_id||0,key=m.id+':'+fid;if(!groups.has(key))groups.set(key,{m:m,fid:fid,count:0});groups.get(key).count++});
 const rows=[...groups.values()].sort((a,b)=>(b.m.scheduled_date||'').localeCompare(a.m.scheduled_date||'')||familyName(a.fid).localeCompare(familyName(b.fid),'fr'));
 if(!rows.length){modal.innerHTML='<div class="modal-card"><button class="close" onclick="closeModal()">×</button><p class="eyebrow">PRÉSENCES ENREGISTRÉES</p><h2>Aucune feuille de présence</h2><p class="muted">Aucune présence de rencontre FI/FIJ n’a encore été enregistrée. Le compteur du tableau de bord n’inclut désormais que les présences de rencontres.</p><button class="primary" onclick="closeModal();go(\'Rencontres\')">Voir les rencontres</button></div>';modal.classList.remove('hidden');return}
 if(rows.length===1)return openAttendanceReadV214('meeting',rows[0].m.id,rows[0].fid);
 modal.innerHTML='<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><p class="eyebrow">PRÉSENCES ENREGISTRÉES</p><h2>Feuilles de présence</h2><div class="pilot-compact-list">'+rows.map(x=>'<div class="family-row clickable" onclick="openAttendanceReadV214(\'meeting\','+x.m.id+','+x.fid+')"><div><b>'+esc(familyName(x.fid))+'</b><div class="muted">'+esc(x.m.title)+' · '+new Date(x.m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')+'</div></div><span class="pill">'+x.count+' présent'+(x.count>1?'s':'')+' →</span></div>').join('')+'</div></div>';modal.classList.remove('hidden')
}
