// Présences + périmètres programmes FI/FIJ
const _baseLoadData=loadData;
loadData=async function(){await _baseLoadData();const [a,t]=await Promise.all([sb.from('attendance').select('*'),sb.from('program_family_targets').select('*')]);if(a.error)throw a.error;if(t.error)throw t.error;db.attendance=a.data||[];db.programTargets=t.data||[];};
// Dates locales : évite le décalage d'un jour lié à UTC dans le calendrier.
dateISO=function(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;};
function memberFamilyId(memberId){return db.assignments.find(a=>String(a.member_id)===String(memberId)&&!a.ends_at)?.family_id||null;}
function canManageAttendanceFamily(fid){return isDirection()||roles.some(r=>['pilote','copilote'].includes(r.role)&&String(r.family_id)===String(fid));}
function attendanceFor(kind,id){return (db.attendance||[]).filter(a=>String(a[kind+'_id'])===String(id));}
function attendanceMembers(kind,id,familyId=null){let ids=[];if(familyId)ids=db.assignments.filter(a=>String(a.family_id)===String(familyId)&&!a.ends_at).map(a=>a.member_id);else ids=db.members.map(m=>m.id);return db.members.filter(m=>ids.includes(m.id)).map(m=>{const a=attendanceFor(kind,id).find(x=>String(x.member_id)===String(m.id));return {m,a};});}
function attendanceBlock(kind,id,familyId=null,editable=true){
 const rows=attendanceMembers(kind,id,familyId);
 const present=rows.filter(x=>x.a?.present);
 const canEdit=!!editable&&(!familyId||canManageAttendanceFamily(familyId)||isDirection());
 return '<div class="attendance-block"><div class="toolbar"><div><h3>Présences</h3><p class="muted">Les présences sont consultables ici. La gestion détaillée se fait dans la fiche dédiée.</p></div><span class="pill">'+present.length+' présent(s)</span></div>'+
 (present.length?'<div class="report-present-list">'+present.slice(0,8).map(({m,a})=>'<span class="report-person">'+esc(memberName(m.id))+(a.arrival_time?' · '+String(a.arrival_time).slice(0,5):'')+'</span>').join('')+(present.length>8?'<span class="report-person">+ '+(present.length-8)+' autre(s)</span>':''):'<p class="muted">Aucune présence enregistrée.</p>')+
 (canEdit?'<div class="row-actions"><button class="primary" onclick="openAttendance(\''+kind+'\','+id+')">Gérer les présences</button></div>':'')+
 '</div>'+(typeof childrenAttendanceBlockV217==='function'?childrenAttendanceBlockV217(kind,id,familyId,editable):'');
}
const _oldOpenMeeting=openMeeting;
openMeeting=function(id){const m=db.meetings.find(x=>x.id===id);if(!m)return;const editable=!m.family_id||canManageAttendanceFamily(m.family_id);modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><h2>${esc(m.title)}</h2><p>${m.scheduled_date}${m.planned_start?' · '+new Date(m.planned_start).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}${m.planned_end?' → '+new Date(m.planned_end).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}</p><p>Statut : <b>${m.status==='scheduled'?'Prévue':m.status==='cancelled'?'Annulée':m.status==='postponed'?'Reportée':esc(m.status||'Prévue')}</b></p>${attendanceBlock('meeting',id,m.family_id,editable)}<div class="row-actions"><button class="ghost" onclick="changeSchedule(${id},'postpone')">Reporter</button><button class="danger" onclick="changeSchedule(${id},'cancel')">Annuler</button></div><h3>Historique</h3>${db.changes.filter(c=>c.meeting_id===id).map(c=>`<div class="meeting"><span>${new Date(c.changed_at).toLocaleString('fr-FR')} · ${c.action}</span><small>${esc(c.reason)}</small></div>`).join('')||'<p class="muted">Aucune modification.</p>'}</div>`;modal.classList.remove('hidden');};
const _oldOpenVirtual=openVirtual;
openVirtual=function(date,familyId,templateId){const f=db.families.find(x=>x.id===familyId),t=db.templates.find(x=>x.id===templateId),v=activeVersion(t,date);modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span><h2>${esc(f.name)} · ${date}</h2><p>Modèle : <b>${esc(t.name)}</b></p><p>Horaire prévu : <b>${(v.start_time||'').slice(0,5)}${v.end_time?' → '+v.end_time.slice(0,5):''}</b></p><p class="muted">Pour gérer les présences et le Reporting, ouvrez cette occurrence : elle sera enregistrée sans modifier le modèle hebdomadaire.</p><div class="row-actions"><button class="primary" onclick="openVirtualAttendance('${date}',${familyId},${templateId})">Gérer les présences</button><button class="ghost" onclick="materializeMeeting('${date}',${familyId},${templateId},'postpone')">Reporter</button><button class="danger" onclick="materializeMeeting('${date}',${familyId},${templateId},'cancel')">Annuler</button></div></div>`;modal.classList.remove('hidden');};
async function openVirtualAttendance(date,familyId,templateId){const existing=db.meetings.find(m=>String(m.family_id)===String(familyId)&&(m.original_scheduled_date===date||m.scheduled_date===date)&&m.template_version_id);if(existing)return openMeeting(existing.id);const t=db.templates.find(x=>x.id===templateId),v=activeVersion(t,date),f=db.families.find(x=>x.id===familyId);const {data,error}=await sb.from('meetings').insert({title:`${t.name} — ${f.name}`,meeting_kind:'Rencontre hebdomadaire',scheduled_date:date,original_scheduled_date:date,planned_start:new Date(`${date}T${v.start_time}`).toISOString(),planned_end:v.end_time?new Date(`${date}T${v.end_time}`).toISOString():null,family_id:familyId,template_version_id:v.id,status:'scheduled'}).select('id').single();if(error)return alert(typeof frenchError==='function'?frenchError(error):'Une erreur est survenue.');await loadData();openMeeting(data.id);}
function programAudienceLabel(p){if(p.direction_only)return 'Direction uniquement';if(p.leaders_only)return `${p.include_fi&&p.include_fij?'FI + FIJ':p.include_fi?'FI':'FIJ'} · Pilotes + copilotes`;if(p.target_scope==='SELECTED_FAMILIES')return 'Une ou plusieurs familles';return `${p.include_fi&&p.include_fij?'Toutes les FI + FIJ':p.include_fi?'Toutes les FI':'Toutes les FIJ'}`;}
function toggleProgramScope(){const selected=document.getElementById('pTarget')?.value==='SELECTED_FAMILIES';document.getElementById('pFamiliesBox')?.classList.toggle('hidden',!selected);}
formProgram=function(){modalForm('Nouveau programme / événement',`<input id="pTitle" placeholder="Titre"><select id="pKind"><option>Programme spécial</option><option>Formation</option><option>Réunion</option><option>Rencontre commune</option><option>Temps de prière</option><option>Événement</option></select><div class="form-row"><input id="pStart" type="date"><input id="pEnd" type="date"></div><div class="scope-box"><b>Périmètre</b><div class="check-row"><label><input id="pFI" type="checkbox" checked> FI</label><label><input id="pFIJ" type="checkbox" checked> FIJ</label></div><select id="pTarget" onchange="toggleProgramScope()"><option value="ALL_FAMILIES">Toutes les familles du périmètre</option><option value="SELECTED_FAMILIES">Une ou plusieurs familles</option><option value="LEADERS_ONLY">Pilotes + copilotes du périmètre</option><option value="DIRECTION_ONLY">Direction uniquement</option></select><div id="pFamiliesBox" class="family-checks hidden">${db.families.map(f=>`<label data-type="${f.family_type}"><input type="checkbox" name="pFamily" value="${f.id}"> ${esc(f.name)} <span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span></label>`).join('')}</div><small class="muted">La Direction est toujours invitée. Pilotes et copilotes sont gérés ensemble.</small></div><textarea id="pNotes" placeholder="Notes"></textarea>`,async()=>{if(!pTitle.value.trim()||!pStart.value)throw Error('Titre et date de début obligatoires.');const fi=pFI.checked,fij=pFIJ.checked,target=pTarget.value;if(target!=='DIRECTION_ONLY'&&!fi&&!fij)throw Error('Choisissez FI, FIJ ou les deux.');const {data,error}=await sb.from('programs').insert({title:pTitle.value.trim(),kind:pKind.value,scheduled_date:pStart.value,end_date:pEnd.value||pStart.value,audience:target==='DIRECTION_ONLY'?'Direction':target==='LEADERS_ONLY'?'Pilotes + copilotes':'Familles',target_scope:target,include_fi:target==='DIRECTION_ONLY'?false:fi,include_fij:target==='DIRECTION_ONLY'?false:fij,leaders_only:target==='LEADERS_ONLY',direction_only:target==='DIRECTION_ONLY',notes:pNotes.value.trim()||null,status:'scheduled'}).select('id').single();if(error)throw error;if(target==='SELECTED_FAMILIES'){const ids=[...document.querySelectorAll('input[name=pFamily]:checked')].map(x=>+x.value).filter(id=>{const f=db.families.find(z=>z.id===id);return f&&(f.family_type==='FI'?fi:fij);});if(!ids.length)throw Error('Sélectionnez au moins une famille.');const {error:e}=await sb.from('program_family_targets').insert(ids.map(family_id=>({program_id:data.id,family_id})));if(e)throw e;}const end=new Date((pEnd.value||pStart.value)+'T12:00:00');for(let d=new Date(pStart.value+'T12:00:00');d<=end;d.setDate(d.getDate()+1)){const {error:e}=await sb.from('program_days').insert({program_id:data.id,program_date:dateISO(d)});if(e)throw e;}});};
function programFamilyIds(p){if(p.direction_only||p.leaders_only)return [];if(p.target_scope==='SELECTED_FAMILIES')return (db.programTargets||[]).filter(x=>x.program_id===p.id).map(x=>x.family_id);return db.families.filter(f=>(p.include_fi&&f.family_type==='FI')||(p.include_fij&&f.family_type==='FIJ')).map(f=>f.id);}
openProgram=function(id){const p=db.programs.find(x=>x.id===id),days=db.programDays.filter(d=>d.program_id===id).sort((a,b)=>a.program_date.localeCompare(b.program_date)),fids=programFamilyIds(p);let presence='';if(p.direction_only||p.leaders_only){presence=isDirection()?attendanceBlock('program',id,null,true):'<p class="muted">Les présences de cette réunion sont gérées par la Direction.</p>';}else if(isDirection()){presence=fids.map(fid=>`<details class="family-att"><summary>${esc(familyName(fid))}</summary>${attendanceBlock('program',id,fid,true)}</details>`).join('');}else{const mine=fids.filter(fid=>canManageAttendanceFamily(fid));presence=mine.map(fid=>attendanceBlock('program',id,fid,true)).join('')||'<p class="muted">Aucune présence à gérer dans votre périmètre.</p>';}modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><h2>${esc(p.title)}</h2><p>${esc(p.kind||'Programme')} · <b>${esc(programAudienceLabel(p))}</b></p><h3>Jours & horaires</h3>${days.map(d=>`<div class="family-row"><b>${d.program_date}</b><span>${d.starts_at?d.starts_at.slice(0,5):'Horaire non connu'}${d.ends_at?' → '+d.ends_at.slice(0,5):''}</span></div>`).join('')}<hr>${presence}</div>`;modal.classList.remove('hidden');};
reportingPage=function(){const reports=db.reports||[];const meetings=db.meetings.filter(m=>attendanceFor('meeting',m.id).some(a=>a.present)||reports.some(r=>r.meeting_id===m.id));return `<div class="card page-card"><h2>Reporting</h2><p class="muted">Chaque Reporting reprend automatiquement les présences déjà pointées pour la rencontre.</p>${meetings.map(m=>{const at=attendanceFor('meeting',m.id).filter(a=>a.present);const r=reports.find(x=>x.meeting_id===m.id);return `<div class="report-card clickable" onclick="openMeeting(${m.id})"><div class="toolbar"><div><b>${esc(m.title)}</b><div class="muted">${m.scheduled_date} · ${familyName(m.family_id)}</div></div><span class="pill">${r?.status||'Brouillon'}</span></div><div class="presence-summary"><b>Présences : ${at.length}</b>${at.slice(0,6).map(a=>`<span>${esc(memberName(a.member_id))} · ${a.arrival_unknown?'heure non connue':(a.arrival_time||'heure non connue').slice(0,5)}</span>`).join('')}${at.length>6?`<span>+ ${at.length-6} autre(s)</span>`:''}</div></div>`;}).join('')||'<div class="empty">Aucun Reporting ou pointage pour le moment.</div>'}</div>`;};
// Le temps réel recharge aussi les présences et les périmètres ciblés.
if(realtimeChannel){try{sb.removeChannel(realtimeChannel);}catch{}realtimeChannel=null;}
subscribeRealtime=function(){if(realtimeChannel)return;realtimeChannel=sb.channel('fi-live-v2');['families','members','member_assignments','meetings','programs','reporting','meeting_templates','meeting_template_versions','calendar_pauses','program_days','schedule_changes','app_settings','role_assignments','attendance','program_family_targets'].forEach(table=>realtimeChannel.on('postgres_changes',{event:'*',schema:'public',table},async()=>{await loadData();render();}));realtimeChannel.subscribe();};
setTimeout(async()=>{if(session){try{await loadData();render();subscribeRealtime();}catch(e){console.error(e);}}},500);

