/* Enfants accompagnants — entité distincte des membres, rattachement aux responsables et présences. */
function childNameV217(c){return [c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Enfant'}
function childAgeV217(c){if(!c?.birth_date)return'';const b=new Date(c.birth_date+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a>=0?a+' an'+(a>1?'s':''):''}
function childGuardiansV217(cid){return (db.childGuardians||[]).filter(g=>+g.child_id===+cid)}
function childGuardianLabelV217(g){if(g.member_id)return memberName(g.member_id);const p=(db.people||[]).find(x=>+x.id===+g.person_id);return p?[p.first_name,p.last_name].filter(Boolean).join(' '):'Responsable'}
function childGuardianNamesV217(cid){return childGuardiansV217(cid).map(childGuardianLabelV217).filter(Boolean).join(' · ')}
function childrenForFamilyV217(fid){return (db.children||[]).filter(c=>c.active!==false&&!c.converted_member_id&&+c.family_id===+fid).sort((a,b)=>childNameV217(a).localeCompare(childNameV217(b),'fr',{sensitivity:'base'}))}
function childrenForMemberV217(mid){const ids=new Set((db.childGuardians||[]).filter(g=>+g.member_id===+mid).map(g=>+g.child_id));return (db.children||[]).filter(c=>ids.has(+c.id)&&c.active!==false&&!c.converted_member_id)}
function canManageChildV217(c){return isDirection()||(+c.family_id&&canManageAttendanceFamily(c.family_id))}
function childGuardianOptionsV217(selectedMember=0){const members=(db.members||[]).filter(m=>m.active!==false).map(m=>'<option value="m:'+m.id+'" '+(+m.id===+selectedMember?'selected':'')+'>'+esc(memberName(m.id))+' · membre</option>');const people=(db.people||[]).filter(p=>!p.linked_member_id).map(p=>'<option value="p:'+p.id+'">'+esc([p.first_name,p.last_name].filter(Boolean).join(' '))+' · fréquentant/visiteur</option>');return '<option value="">Choisir le parent / responsable</option>'+members.concat(people).join('')}
function childFamilyOptionsV217(fid=0){return '<option value="">FI/FIJ à préciser</option>'+db.families.map(f=>'<option value="'+f.id+'" '+(+f.id===+fid?'selected':'')+'>'+esc(f.name)+' · '+esc(f.family_type)+'</option>').join('')}
function formChildV217(fid=0,memberId=0){
 modalForm('Nouvel enfant accompagnant','<div class="form-row"><input id="chFirst" placeholder="Prénom"><input id="chLast" placeholder="Nom (facultatif)"></div><label>Date de naissance <span class="muted">(facultative)</span><input id="chBirth" type="date"></label><label>Parent / responsable principal<select id="chGuardian">'+childGuardianOptionsV217(memberId)+'</select></label><label>FI/FIJ habituelle<select id="chFamily">'+childFamilyOptionsV217(fid)+'</select></label><textarea id="chNotes" placeholder="Note facultative"></textarea><p class="muted">Cet enfant sera enregistré comme accompagnant : il ne sera pas compté dans l’effectif des membres.</p>',async()=>{
  if(!chFirst.value.trim())throw Error('Le prénom est requis.');
  if(!chGuardian.value)throw Error('Choisissez au moins un parent ou responsable.');
  const family=chFamily.value?+chFamily.value:null;if(!family)throw Error('Choisissez la FI/FIJ habituelle.');
  if(!isDirection()&&!canManageAttendanceFamily(family))throw Error('Vous ne pouvez ajouter un enfant que dans votre FI/FIJ.');
  const {data:c,error}=await sb.from('child_dependents').insert({first_name:chFirst.value.trim(),last_name:chLast.value.trim()||null,birth_date:chBirth.value||null,family_id:family,notes:chNotes.value.trim()||null}).select('id').single();if(error)throw error;
  const [kind,id]=chGuardian.value.split(':');const payload={child_id:c.id,is_primary:true};if(kind==='m')payload.member_id=+id;else payload.person_id=+id;
  const {error:e}=await sb.from('child_guardians').insert(payload);if(e)throw e;
 })
}
function openChildV217(id){
 const c=(db.children||[]).find(x=>+x.id===+id);if(!c)return;const gs=childGuardiansV217(id),att=(db.childAttendance||[]).filter(a=>+a.child_id===+id&&a.present),can=canManageChildV217(c);
 modal.innerHTML='<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><div class="toolbar"><div><p class="eyebrow">ENFANT ACCOMPAGNANT</p><h2>'+esc(childNameV217(c))+'</h2><p class="muted">'+esc([childAgeV217(c),familyName(c.family_id)].filter(Boolean).join(' · '))+'</p></div><div class="row-actions">'+(can?'<button class="ghost" onclick="editChildV217('+id+')">Modifier</button>':'')+(isDirection()?'<button class="primary" onclick="convertChildV217('+id+')">Créer une fiche membre</button>':'')+'</div></div><div class="card"><h3>Parent(s) / responsable(s)</h3>'+(gs.map(g=>'<div class="family-row"><b>'+esc(childGuardianLabelV217(g))+'</b><span>'+esc(g.relationship|| (g.is_primary?'Responsable principal':'Responsable'))+'</span></div>').join('')||'<p class="muted">Aucun responsable rattaché.</p>')+(can?'<button class="ghost" onclick="addChildGuardianV217('+id+')">＋ Ajouter un responsable</button>':'')+'</div><div class="grid"><div class="card metric"><span>Présences enregistrées</span><strong>'+att.length+'</strong></div><div class="card metric"><span>Statut</span><strong style="font-size:18px">Accompagnant</strong></div></div><p class="muted">Cette fiche est distincte des membres et n’augmente pas l’effectif officiel de la FI/FIJ.</p></div>';modal.classList.remove('hidden')
}
function editChildV217(id){const c=db.children.find(x=>+x.id===+id);if(!c||!canManageChildV217(c))return;modalForm('Modifier l’enfant accompagnant','<div class="form-row"><input id="echFirst" placeholder="Prénom" value="'+esc(c.first_name||'')+'"><input id="echLast" placeholder="Nom" value="'+esc(c.last_name||'')+'"></div><label>Date de naissance<input id="echBirth" type="date" value="'+esc(c.birth_date||'')+'"></label><label>FI/FIJ habituelle<select id="echFamily">'+childFamilyOptionsV217(c.family_id)+'</select></label><textarea id="echNotes" placeholder="Note facultative">'+esc(c.notes||'')+'</textarea>',async()=>{if(!echFirst.value.trim())throw Error('Le prénom est requis.');const fid=+echFamily.value;if(!isDirection()&&!canManageAttendanceFamily(fid))throw Error('Périmètre non autorisé.');const {error}=await sb.from('child_dependents').update({first_name:echFirst.value.trim(),last_name:echLast.value.trim()||null,birth_date:echBirth.value||null,family_id:fid||null,notes:echNotes.value.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error})}
function addChildGuardianV217(id){const c=db.children.find(x=>+x.id===+id);if(!c||!canManageChildV217(c))return;modalForm('Ajouter un parent / responsable','<select id="cgGuardian">'+childGuardianOptionsV217()+'</select><input id="cgRelation" placeholder="Lien (ex. mère, père, tuteur)"><label class="check-row"><input id="cgPrimary" type="checkbox"> Responsable principal</label>',async()=>{if(!cgGuardian.value)throw Error('Choisissez une personne.');const [kind,gid]=cgGuardian.value.split(':'),payload={child_id:id,relationship:cgRelation.value.trim()||null,is_primary:cgPrimary.checked};if(kind==='m')payload.member_id=+gid;else payload.person_id=+gid;const {error}=await sb.from('child_guardians').insert(payload);if(error)throw error})}
async function convertChildV217(id){const c=db.children.find(x=>+x.id===+id);if(!c||!isDirection())return;if(!confirm('Créer une vraie fiche membre pour '+childNameV217(c)+' ? La fiche enfant sera conservée dans l’historique mais ne sera plus proposée comme accompagnant.'))return;const {data:newId,error}=await sb.rpc('create_member_with_assignment',{p_first_name:c.first_name,p_last_name:c.last_name||'À compléter',p_email:null,p_phone:null,p_address:null,p_neighborhood:null,p_area:null,p_birth_month:c.birth_date?+c.birth_date.slice(5,7):null,p_birth_day:c.birth_date?+c.birth_date.slice(8,10):null,p_family_id:c.family_id,p_joined_on:null,p_notes:c.notes||null});if(error)return alert(error.message);const {error:e}=await sb.from('child_dependents').update({active:false,converted_member_id:newId,updated_at:new Date().toISOString()}).eq('id',id);if(e)return alert(e.message);await loadData();openMember(+newId)}
function familyChildrenBlockV217(fid){const cs=childrenForFamilyV217(fid),can=isDirection()||canManageAttendanceFamily(fid);return '<div class="card"><div class="toolbar"><div><h3>Enfants accompagnants ('+cs.length+')</h3><p class="muted">Suivis séparément des membres.</p></div>'+(can?'<button class="primary" onclick="formChildV217('+fid+')">＋ Enfant</button>':'')+'</div>'+(cs.map(c=>'<div class="family-row clickable" onclick="openChildV217('+c.id+')"><div><b>'+esc(childNameV217(c))+'</b><div class="muted">'+esc([childAgeV217(c),childGuardianNamesV217(c.id)].filter(Boolean).join(' · '))+'</div></div><span class="pill">Enfant</span></div>').join('')||'<p class="muted">Aucun enfant accompagnant enregistré.</p>')+'</div>'}
function memberChildrenV217(mid){const cs=childrenForMemberV217(mid),fid=memberFamilyId(mid);return '<div class="card"><div class="toolbar"><h3>Enfants / personnes à charge</h3>'+(fid&&(isDirection()||canManageAttendanceFamily(fid))?'<button class="ghost" onclick="formChildV217('+fid+','+mid+')">＋ Ajouter un enfant</button>':'')+'</div>'+(cs.map(c=>'<div class="family-row clickable" onclick="openChildV217('+c.id+')"><div><b>'+esc(childNameV217(c))+'</b><div class="muted">'+esc([childAgeV217(c),familyName(c.family_id)].filter(Boolean).join(' · '))+'</div></div><span class="pill">Accompagnant</span></div>').join('')||'<p class="muted">Aucun enfant rattaché.</p>')+'</div>'}
function childAttendanceForV217(kind,id,fid){return (db.childAttendance||[]).filter(a=>+a[kind+'_id']===+id&&(!fid||+a.family_id===+fid))}
function childrenAttendanceBlockV217(kind,id,fid,editable=true){if(!fid)return'';const cs=childrenForFamilyV217(fid),ats=childAttendanceForV217(kind,id,fid);if(!cs.length)return'';return '<div class="attendance-block child-attendance"><div class="toolbar"><div><h3>Enfants accompagnants</h3><p class="muted">Cochez uniquement l’enfant réellement présent, indépendamment de son parent.</p></div><span class="pill">'+ats.filter(a=>a.present).length+' enfant(s)</span></div>'+cs.map(c=>{const a=ats.find(x=>+x.child_id===+c.id);return '<div class="attendance-row"><label class="attendance-person"><input type="checkbox" '+(a?.present?'checked':'')+' '+(editable?'':'disabled')+' onchange="markChildAttendanceV217(\''+kind+'\','+id+','+c.id+','+fid+',this.checked)"><span><b>'+esc(childNameV217(c))+'</b><small>'+esc(childGuardianNamesV217(c.id)||'Responsable à préciser')+'</small></span></label><div class="attendance-time"><span class="muted">'+(a?.present?'Présent':'Absent / non pointé')+'</span></div></div>'}).join('')+'</div>'}
async function markChildAttendanceV217(kind,id,cid,fid,present){if(!canManageAttendanceFamily(fid)&&!isDirection())return alert('Vous ne pouvez gérer que les présences de votre FI/FIJ.');const existing=childAttendanceForV217(kind,id,fid).find(a=>+a.child_id===+cid);if(existing){const {error}=await sb.from('child_attendance').update({present:!!present,marked_at:new Date().toISOString()}).eq('id',existing.id);if(error)return alert(error.message)}else if(present){const payload={child_id:cid,family_id:fid,present:true};payload[kind+'_id']=id;const {error}=await sb.from('child_attendance').insert(payload);if(error)return alert(error.message)}await loadData();reopenAttendanceContext(kind,id)}
