// Géographie détaillée Le Mans / métropole
const LE_MANS_AREAS={
'Centre / Cœur de ville':['République','Jacobins','Cité Plantagenêt','Préfecture','Mission','Éperon','Gambetta','Halles'],
'Gare / Centre sud':['Gare Nord','Gare Sud','Novaxis','Novaxud','Washington','Jean-Jaurès','Saint-Martin','Miroir','Gué-de-Maulny'],
'Est':['Bollée','Gazonfier','Yzeuville','Jaurès-Bollée','Jardin des Plantes'],
'Sablons / Est':['Sablons','Épau','Newton','Espal','Bords de l’Huisne'],
'Sud':['Pontlieue','Ronceray','Glonnières','Maroc','Pavoine','Bruyères','Vauguyon','Cité des Pins','Batignolles'],
'Nord-Est':['Heuzé','Saint-Georges','Maillets','Bellevue','Banjan','Fontenelles','Villaret','Madeleine'],
'Nord-Ouest':['Université','Ribay','Chasse-Royale','Épine','Hôpital','Saulnières','Gallière'],
'Ouest':['Pâtis Saint-Lazare','Riffaudières','Oasis','Ardriers'],
'Communes proches':['Allonnes','Arnage','Coulaines','Yvré-l’Évêque','Rouillon','La Chapelle-Saint-Aubin','Saint-Saturnin']};
const LE_MANS_GRANDS_SECTEURS=Object.keys(LE_MANS_AREAS);
function geoLabel(o){return [o.neighborhood,o.area].filter(Boolean).join(' · ')||'Localisation à préciser'}
function areaOptions(group){return `<option value="">Sous-quartier / secteur précis</option>`+(LE_MANS_AREAS[group]||[]).map(a=>`<option>${esc(a)}</option>`).join('')}
function syncGeoAreas(prefix='f'){const s=document.getElementById(prefix+'GrandSector'),a=document.getElementById(prefix+'Area');if(!s||!a)return;const current=a.dataset.current||a.value;a.innerHTML=areaOptions(s.value);if(current&&[...a.options].some(o=>o.value===current))a.value=current;a.dataset.current=''}
function geoSelectFields(prefix,neighborhood='',area=''){return '<div class="form-row"><label>Grand secteur / quartier<select id="'+prefix+'GrandSector" onchange="syncGeoAreas(\''+prefix+'\')"><option value="">Grand secteur / quartier</option>'+LE_MANS_GRANDS_SECTEURS.map(s=>'<option '+(s===neighborhood?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>Sous-quartier / secteur précis<select id="'+prefix+'Area" data-current="'+esc(area||'')+'">'+areaOptions(neighborhood)+'</select></label></div>'}
function addressField(prefix,value='',placeholder='Adresse exacte'){return '<div class="smart-address-field" data-address-prefix="'+prefix+'"><input id="'+prefix+'Address" placeholder="'+esc(placeholder)+'" value="'+esc(value||'')+'" autocomplete="off"><div id="'+prefix+'AddressSuggest" class="address-suggest-v11 hidden"></div></div>'}
let smartAddressTimers={},smartAddressAborts={},smartAddressSeq={};
function smartAddressLabel(f){const p=f.properties||{},n=p.housenumber||'',street=p.street||p.name||'',city=p.city||p.municipality||'';return {main:[n,street].filter(Boolean).join(' ')||p.label||'',city}}
function smartAddressScore(f){const p=f.properties||{},city=(p.city||p.municipality||'').toLowerCase(),pc=String(p.postcode||'');if(city==='le mans'||pc.startsWith('72'))return city==='le mans'?0:1;return 2}
async function smartAddressSuggest(prefix,q){const box=document.getElementById(prefix+'AddressSuggest');if(!box)return;const seq=(smartAddressSeq[prefix]||0)+1;smartAddressSeq[prefix]=seq;if(smartAddressAborts[prefix])smartAddressAborts[prefix].abort();const ac=new AbortController();smartAddressAborts[prefix]=ac;try{const queries=[q+' Le Mans',q+' Sarthe',q],res=[];for(const query of queries){const r=await fetch('https://data.geopf.fr/geocodage/search/?q='+encodeURIComponent(query)+'&limit=10&autocomplete=1',{signal:ac.signal});if(r.ok){const j=await r.json();res.push(...(j.features||[]))}}if(seq!==smartAddressSeq[prefix])return;const seen=new Set(),rows=res.sort((a,b)=>smartAddressScore(a)-smartAddressScore(b)).filter(f=>{const x=smartAddressLabel(f),k=(x.main+'|'+x.city).toLowerCase();if(!x.main||seen.has(k))return false;seen.add(k);return true}).slice(0,10);box.innerHTML=rows.map((f,i)=>{const x=smartAddressLabel(f);return '<button type="button" data-address-index="'+i+'"><b>'+esc(x.main)+'</b>'+(x.city?'<small>'+esc(x.city)+'</small>':'')+'</button>'}).join('')||(q.length>=5?'<span class="address-empty-v181">Aucune adresse proposée.</span>':'');box._rows=rows;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const x=smartAddressLabel(rows[+b.dataset.addressIndex]),input=document.getElementById(prefix+'Address');input.value=[x.main,x.city].filter(Boolean).join(', ');box.classList.add('hidden')});box.classList.remove('hidden')}catch(e){if(e.name!=='AbortError'&&seq===smartAddressSeq[prefix]&&q.length>=5){box.innerHTML='<span class="address-empty-v181">Recherche momentanément indisponible.</span>';box.classList.remove('hidden')}}}
function initSmartAddressFields(root=document){root.querySelectorAll('.smart-address-field').forEach(w=>{if(w.dataset.ready)return;w.dataset.ready='1';const p=w.dataset.addressPrefix,input=document.getElementById(p+'Address'),box=document.getElementById(p+'AddressSuggest');input.addEventListener('input',()=>{clearTimeout(smartAddressTimers[p]);const q=input.value.trim();if(q.length<3){box.classList.add('hidden');return}smartAddressTimers[p]=setTimeout(()=>smartAddressSuggest(p,q),180)});input.addEventListener('focus',()=>{if(box.innerHTML&&input.value.trim().length>=3)box.classList.remove('hidden')})})}
const _geoModalForm=modalForm;modalForm=function(title,fields,save){_geoModalForm(title,fields,save);setTimeout(()=>initSmartAddressFields(modal),0)}
formFamily=function(type){modalForm('Nouvelle '+type,'<input id="fName" placeholder="Nom"><input id="fHost" placeholder="Hôte">'+addressField('f')+geoSelectFields('f')+'<small class="muted">L’adresse exacte alimente automatiquement la carte. Le Mans et la Sarthe sont proposés en priorité.</small>',async()=>{const {error}=await sb.from('families').insert({name:fName.value.trim(),family_type:type,host_name:fHost.value.trim()||null,address:fAddress.value.trim()||null,neighborhood:fGrandSector.value||null,area:fArea.value||null,status:'Active'});if(error)throw error})};
const _geoOpenFamily=openFamily;
openFamily=function(id){_geoOpenFamily(id);const f=db.families.find(x=>x.id===id),card=modal.querySelector('.modal-card');if(!f||!card)return;const h=card.querySelector('h2');if(h)h.insertAdjacentHTML('afterend',`<p class="muted"><b>Localisation :</b> ${esc(geoLabel(f))}${f.address?`<br>${esc(f.address)}`:''}</p>`)};
const _geoFormMemberMove=formMemberMove;
formMemberMove=function(memberId,forcedType=''){_geoFormMemberMove(memberId,forcedType);setTimeout(()=>{if(!window.mvTo)return;[...mvTo.options].forEach(o=>{const f=db.families.find(x=>x.id===+o.value);if(f)o.textContent=`${f.name} · ${geoLabel(f)}`})},0)};