/* Notifications v4 — préférences détaillées, relances Reporting, suivis Direction et navigation actionnable. */
const NOTIF_MODULES={
 'Rencontres':[['meeting.reminder_1d','Rappel 1 jour avant une rencontre'],['meeting.changed','Rencontre modifiée, reportée ou annulée']],
 'Reporting':[['reporting.expected','Reporting attendu'],['reporting.reminder','Relance de Reporting reçue']],
 'Suivis':[['reporting.followup_required','Reporting avec nécessité de suivi'],['followup.changed','Suivi attribué, modifié ou clôturé']],
 'Programmes':[['program.changed','Programme ou événement modifié']],
 'Prière':[['prayer.changed','Programme / Reporting de prière']],
 'Membres':[['member.changed','Mouvement ou changement important d’un membre']],
 'Administration':[['admin.access','Rôle, permission ou accès modifié']]
};
let notificationPrefsV4=[],notificationCatalogV4=[];
const _loadNotificationsV4=loadData;loadData=async function(){await _loadNotificationsV4();if(!profile?.member?.id)return;const [p,c]=await Promise.all([sb.from('notification_preferences').select('*').eq('member_id',profile.member.id),sb.from('notification_event_catalog').select('*')]);notificationPrefsV4=p.data||[];notificationCatalogV4=c.data||[]};
function notifPref(key){return notificationPrefsV4.find(x=>x.category===key)||{push_enabled:true,in_app_enabled:true}}
function notifAllowed(key){const c=notificationCatalogV4.find(x=>x.key===key);return !(c?.direction_only)&&!isDirection()?false:true}
async function saveNotifPref(key,channel,on){const old=notifPref(key),payload={member_id:profile.member.id,category:key,push_enabled:channel==='push'?on:old.push_enabled,in_app_enabled:channel==='inapp'?on:old.in_app_enabled,scope:'my_perimeter',updated_at:new Date().toISOString()};const q=await sb.from('notification_preferences').upsert(payload,{onConflict:'member_id,category'});if(q.error)return alert(q.error.message);await loadData();render()}
function notificationPreferencesV4(){return `<div class="card"><h2>Mes notifications</h2><p class="muted">Choisissez précisément ce que vous souhaitez recevoir. Les alertes proposées respectent vos responsabilités.</p>${Object.entries(NOTIF_MODULES).map(([mod,rows])=>{const allowed=rows.filter(([k])=>notifAllowed(k));if(!allowed.length)return'';return `<details class="notif-module" open><summary><b>${mod}</b><span>${allowed.length} alerte(s)</span></summary>${allowed.map(([k,l])=>{const p=notifPref(k);return `<div class="notif-pref-row"><div><b>${l}</b><small>${k==='meeting.reminder_1d'?'Inclut la date, l’heure et le thème lorsqu’il est renseigné.':''}</small></div><label><input type="checkbox" ${p.in_app_enabled?'checked':''} onchange="saveNotifPref('${k}','inapp',this.checked)"> Dans l’app</label><label><input type="checkbox" ${p.push_enabled?'checked':''} onchange="saveNotifPref('${k}','push',this.checked)"> Push</label></div>`}).join('')}</details>`}).join('')}</div>`}
function openNotificationTarget(n){if(n.action_key==='open_reporting'&&n.target_id)return openReporting(n.target_id);if(n.action_key==='open_meeting'&&n.target_id)return openMeeting(n.target_id);if(n.action_key==='open_followup'){go('Pilotage');setTimeout(()=>openFollowupPilotage(n.action_payload?.followup_id),80);return}if(n.target_module&&allowedItems().includes(n.target_module))go(n.target_module)}
async function remindReporting(mid){const q=await sb.rpc('remind_reporting',{p_meeting:mid});if(q.error)return alert(q.error.message);alert(q.data?`Relance envoyée à ${q.data} responsable(s).`:'Aucune relance nécessaire.');await loadData();render()}
async function remindAllMissingReporting(){const [s,e]=typeof pilotRange==='function'?pilotRange():['1900-01-01','2999-12-31'];const missing=db.meetings.filter(m=>m.reporting_required!==false&&m.status!=='cancelled'&&m.scheduled_date>=s&&m.scheduled_date<=e&&!db.reports.some(r=>+r.meeting_id===+m.id));if(!missing.length)return alert('Aucun Reporting en attente sur cette période.');if(!confirm(`Envoyer une relance pour ${missing.length} Reporting en attente ?`))return;let total=0;for(const m of missing){const q=await sb.rpc('remind_reporting',{p_meeting:m.id});if(!q.error)total+=Number(q.data||0)}alert(`${total} relance(s) envoyée(s).`)}
function followupPilotageV4(){if(!isDirection())return'';const rows=(db.followups||[]).filter(x=>x.status!=='Clôturé');return `<div class="card"><div class="toolbar"><div><p class="eyebrow">SUIVIS</p><h3>Reporting avec nécessité de suivi</h3></div><strong>${rows.length}</strong></div>${rows.map(x=>{const m=db.meetings.find(y=>+y.id===+x.meeting_id);return `<div class="family-row clickable" onclick="openFollowupPilotage(${x.id})"><div><b>${esc(memberName(x.member_id))}</b><div class="muted">${esc(familyName(x.family_id))} · ${m?.scheduled_date||''}</div><small>${esc(x.details||'Suivi à préciser')}</small></div><span class="pill">${esc(x.status)}</span></div>`}).join('')||'<p class="muted">Aucun suivi ouvert.</p>'}</div>`}
function openFollowupPilotage(id){const x=(db.followups||[]).find(y=>+y.id===+id);if(!x)return;const m=db.meetings.find(y=>+y.id===+x.meeting_id);modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><p class="eyebrow">SUIVI DIRECTION</p><h2>${esc(memberName(x.member_id))}</h2><p><b>${esc(familyName(x.family_id))}</b> · ${m?.scheduled_date||''}</p><div class="card"><b>Sujet signalé</b><p>${esc(x.details||'—')}</p></div><div class="row-actions">${m?`<button class="ghost" onclick="closeModal();openReporting(${m.id})">Ouvrir le Reporting</button>`:''}</div></div>`;modal.classList.remove('hidden')}
function reportingMissingActionsV4(){if(!isDirection())return'';const [s,e]=typeof pilotRange==='function'?pilotRange():['1900-01-01','2999-12-31'];const rows=db.meetings.filter(m=>m.reporting_required!==false&&m.status!=='cancelled'&&m.scheduled_date>=s&&m.scheduled_date<=e&&!db.reports.some(r=>+r.meeting_id===+m.id));return `<div class="card"><div class="toolbar"><div><p class="eyebrow">REPORTING</p><h3>Reporting en attente</h3></div>${rows.length?`<button class="ghost" onclick="remindAllMissingReporting()">Relancer tous</button>`:''}</div>${rows.slice(0,12).map(m=>`<div class="family-row"><div class="clickable" onclick="openMeeting(${m.id})"><b>${esc(m.title)}</b><div class="muted">${m.scheduled_date} · ${esc(familyName(m.family_id))}</div></div><button class="ghost" onclick="remindReporting(${m.id})">Relancer</button></div>`).join('')||'<p class="muted">Aucun Reporting en attente.</p>'}</div>`}
const _pilotageNotifV4=pilotage;pilotage=function(){return _pilotageNotifV4()+reportingMissingActionsV4()+followupPilotageV4()};
const _dashboardNotifV4=dashboard;dashboard=function(){let html=_dashboardNotifV4();html=html.replace('class="card metric"><span>FI</span>','class="card metric clickable" onclick="familyTab=\'FI\';go(\'FI & FIJ\')"><span>FI</span>').replace('class="card metric"><span>FIJ</span>','class="card metric clickable" onclick="familyTab=\'FIJ\';go(\'FI & FIJ\')"><span>FIJ</span>').replace('class="card metric"><span>Membres</span>','class="card metric clickable" onclick="go(\'Membres\')"><span>Membres</span>').replace('class="card metric"><span>Présences enregistrées</span>','class="card metric clickable" onclick="go(\'Rencontres\')"><span>Présences enregistrées</span>');return html};
