/* v11 — organisation UX. L'espace FI/FIJ est défini uniquement dans family-workspace.js. */
(function(){
const coll=new Intl.Collator('fr',{sensitivity:'base',numeric:true}),alpha=(a,b)=>coll.compare(String(a||''),String(b||''));window.fiAlphaV11=alpha;window.memberGroupV11=window.memberGroupV11||'family';window.memberSortV11=window.memberSortV11||'last';window.pilotTabV11=window.pilotTabV11||'overview';
function sortMembers(rows){return [...rows].sort((a,b)=>memberSortV11==='first'?(alpha(a.first_name,b.first_name)||alpha(a.last_name,b.last_name)):(alpha(a.last_name,b.last_name)||alpha(a.first_name,b.first_name)))}
function row(m){const a=activeAssignmentFor(m.id),b=birthdayParts(m);return `<div class="family-row clickable" onclick="openMember(${m.id})"><div><b>${esc(memberName(m.id))}</b><div class="muted">${esc(familyName(a?.family_id))}</div></div>${b[0]?`<span>🎂 ${String(b[1]).padStart(2,'0')}/${String(b[0]).padStart(2,'0')}</span>`:''}</div>`}
window.setMemberGroupV11=v=>{memberGroupV11=v;render()};window.setMemberSortV11=v=>{memberSortV11=v;render()};
membersPage=function(){const rows=sortMembers(db.members.filter(m=>m.active!==false));let body;if(memberGroupV11==='family'){const g=new Map();rows.forEach(m=>{const fid=activeAssignmentFor(m.id)?.family_id||0;if(!g.has(fid))g.set(fid,[]);g.get(fid).push(m)});body=[...g.entries()].sort((a,b)=>alpha(a[0]?familyName(a[0]):'Sans FI/FIJ',b[0]?familyName(b[0]):'Sans FI/FIJ')).map(([fid,ms])=>`<section class="member-group-v11"><div class="member-group-head"><div><h3>${esc(fid?familyName(fid):'Sans FI/FIJ')}</h3></div><b>${ms.length} membre${ms.length>1?'s':''}</b></div>${ms.map(row).join('')}</section>`).join('')}else body=rows.map(row).join('');return `<div class="card page-card"><div class="toolbar"><div><h2>Membres</h2><p class="muted">${rows.length} membre(s) actif(s)</p></div><button class="primary" onclick="formMember()">＋ Nouveau membre</button></div><div class="member-controls-v11"><label>Regrouper par<select onchange="setMemberGroupV11(this.value)"><option value="family" ${memberGroupV11==='family'?'selected':''}>FI / FIJ</option><option value="none" ${memberGroupV11==='none'?'selected':''}>Aucun regroupement</option></select></label><label>Trier par<select onchange="setMemberSortV11(this.value)"><option value="last" ${memberSortV11==='last'?'selected':''}>Nom A → Z</option><option value="first" ${memberSortV11==='first'?'selected':''}>Prénom A → Z</option></select></label></div>${body||'<p class="muted">Aucun membre.</p>'}</div>`};
if(typeof roleMemberOptions==='function')roleMemberOptions=function(){return `<option value="">— Non renseigné —</option>`+sortMembers(db.members.filter(m=>m.active!==false)).map(m=>`<option value="${m.id}">${esc(memberName(m.id))}</option>`).join('')};if(typeof LE_MANS_GRANDS_SECTEURS!=='undefined')LE_MANS_GRANDS_SECTEURS.sort(alpha);if(typeof LE_MANS_AREAS!=='undefined')Object.values(LE_MANS_AREAS).forEach(a=>a.sort(alpha));if(typeof areaOptions==='function')areaOptions=function(group){return `<option value="">Sous-quartier / secteur précis</option>`+[...(LE_MANS_AREAS[group]||[])].sort(alpha).map(a=>`<option>${esc(a)}</option>`).join('')};
window.setPilotTabV11=t=>{pilotTabV11=t;render()};
function pilotCompareLabelV12(s,e){const [ps,pe]=previousRange(s,e);return statsCompare?'<div class="compare-note-v12"><b>Comparaison activée</b><span>Période affichée : '+s+' → '+e+'</span><span>comparée à : '+ps+' → '+pe+'</span></div>':''}
function pilotTabsV12(){return '<div class="pilot-tabs-v11">'+[['overview','Vue d’ensemble'],['attendance','Rencontres & assiduité'],['reporting','Reporting'],['members','Membres & mouvements'],['new','Nouveaux'],['families','FI & FIJ']].map(([k,l])=>'<button class="'+(pilotTabV11===k?'active':'')+'" onclick="setPilotTabV11(\''+k+'\')">'+l+'</button>').join('')+'</div>'}
function pilotControlsV12(s,e){const label={week:'Semaine',month:'Mois',quarter:'Trimestre',semester:'Semestre',season:'Saison FI',year:'Année',custom:'Personnalisée'}[statsPeriod]||'Période';return `<div class="card pilot-head-v189"><div class="pilot-toolbar-v189"><div><h2>Pilotage & statistiques</h2><p class="muted">${label} · ${s} → ${e}</p></div><div class="pilot-actions-v189"><button class="ghost" onclick="document.getElementById('pilotFiltersV189').classList.toggle('hidden')">☰ Filtres</button><button class="ghost" onclick="exportPilotageExcel()">Excel</button><button class="ghost" onclick="exportPilotagePDF()">PDF</button></div></div><div id="pilotFiltersV189" class="pilot-filter-panel-v189 hidden"><label>Période<select onchange="setStatsPeriod(this.value)">${[['week','Semaine'],['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['season','Saison FI'],['year','Année'],['custom','Personnalisée']].map(([v,l])=>`<option value="${v}" ${statsPeriod===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="compare-toggle-v12"><input type="checkbox" ${statsCompare?'checked':''} onchange="statsCompare=this.checked;render()"> Comparer à la période précédente</label><div id="customStats" class="pilot-custom-v189 ${statsPeriod==='custom'?'':'hidden'}"><label>Du<input id="statsStart" type="date" value="${statsCustomStart||s}"></label><label>Au<input id="statsEnd" type="date" value="${statsCustomEnd||e}"></label><button class="primary" onclick="setCustomStats()">Appliquer</button></div></div>${pilotCompareLabelV12(s,e)}<div class="pilot-nav-wrap-v189">${pilotTabsV12()}</div></div>`})();
