/* Recherche de proximité FI/FIJ + itinéraires multimodaux. Transit: MOTIS/Transitous (GTFS/GTFS-RT). */
let proximityOrigin=null, proximityMap=null;
const km=(a,b,c,d)=>{const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const familyPos=f=>f.latitude&&f.longitude?[+f.latitude,+f.longitude]:(SECTOR_COORDS[f.neighborhood]||null);
function finderType(){return document.querySelector('input[name="finderType"]:checked')?.value||'ALL'}
function finderFamilies(){const t=finderType();return db.families.filter(f=>(t==='ALL'||f.family_type===t)&&!['Fermée','Fermée / Archivée'].includes(f.status));}
async function geocodeFinder(){const q=(finderAddress.value||'').trim();if(!q)return alert('Saisissez une adresse de départ.');finderStatus.textContent='Recherche de l’adresse…';try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q=${encodeURIComponent(q+', Le Mans')}`,{headers:{'Accept-Language':'fr'}});const j=await r.json();if(!j.length)throw Error('Adresse introuvable.');proximityOrigin=[+j[0].lat,+j[0].lon];finderStatus.textContent=j[0].display_name;renderFinderResults();}catch(e){finderStatus.textContent='';alert(e.message)}}
function useMemberAddress(){const m=db.members.find(x=>x.id===profile?.member?.id);if(!m?.address)return alert('Aucune adresse renseignée sur votre fiche.');finderAddress.value=m.address;geocodeFinder()}
function renderFinderResults(){if(!proximityOrigin)return;const fs=finderFamilies().map(f=>{const p=familyPos(f);return {...f,_pos:p,_km:p?km(proximityOrigin[0],proximityOrigin[1],p[0],p[1]):999}}).sort((a,b)=>a._km-b._km);finderResults.innerHTML=fs.map(f=>`<div class="finder-result"><div><span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span> <b>${esc(f.name)}</b><div class="muted">${esc(f.neighborhood_detail||f.neighborhood||'Secteur à préciser')} · ${f._pos?(f._km.toFixed(1)+' km à vol d’oiseau'):'adresse à géolocaliser'}${f.status&&f.status!=='Active'?' · '+esc(f.status):''}</div></div><div class="row-actions"><button class="ghost" onclick="openFamily(${f.id})">Voir la FI</button>${f._pos?`<button class="primary" onclick="openRoutes(${f.id})">Comparer les trajets</button>`:''}</div></div>`).join('')||'<p class="muted">Aucune famille correspondante.</p>';drawFinderMap(fs)}
function baseMap(el,center=[48.006,0.199],zoom=11){if(proximityMap)proximityMap.remove();proximityMap=L.map(el).setView(center,zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(proximityMap);return proximityMap}
function drawFinderMap(fs){if(!document.getElementById('finderMap'))return;baseMap('finderMap',proximityOrigin||[48.006,0.199],12);L.marker(proximityOrigin).addTo(proximityMap).bindPopup('<b>Départ</b>');fs.filter(f=>f._pos).forEach(f=>{const color=f.family_type==='FI'?'#0369a1':'#be185d';L.circleMarker(f._pos,{radius:9,color,fillColor:color,fillOpacity:.9}).addTo(proximityMap).bindPopup(`<b>${esc(f.name)}</b><br>${esc(f.neighborhood_detail||f.neighborhood||'')}`)});}
function finderPanel(){return `<div class="card finder"><div class="toolbar"><div><h2>📍 Trouver une FI / FIJ proche</h2><p class="muted">Comparez la proximité et les trajets selon la date et l’heure de la rencontre.</p></div><div class="finder-types"><label><input type="radio" name="finderType" value="ALL" checked onchange="renderFinderResults()"> Tout</label><label><input type="radio" name="finderType" value="FI" onchange="renderFinderResults()"> FI</label><label><input type="radio" name="finderType" value="FIJ" onchange="renderFinderResults()"> FIJ</label></div></div><div class="finder-search"><input id="finderAddress" placeholder="Adresse de départ"><input id="finderDate" type="date" value="${dateISO(new Date())}"><input id="finderTime" type="time" value="19:00"><button class="primary" onclick="geocodeFinder()">Rechercher</button></div><div class="row-actions"><button class="ghost" onclick="useMemberAddress()">Utiliser mon adresse enregistrée</button><span id="finderStatus" class="muted"></span></div><div id="finderMap" class="finder-map"></div><div id="finderResults"></div><p class="muted finder-credit">Transports publics : données ouvertes GTFS/GTFS-RT, calcul Transitous/MOTIS · Carte © OpenStreetMap.</p></div>`}
mapPage=function(){setTimeout(()=>{const el=document.getElementById('finderMap');if(!el)return;if(proximityOrigin)renderFinderResults();else{baseMap('finderMap');db.families.filter(f=>familyPos(f)).forEach(f=>L.circleMarker(familyPos(f),{radius:8,color:f.family_type==='FI'?'#0369a1':'#be185d'}).addTo(proximityMap).bindPopup(esc(f.name))) }},50);return finderPanel()};
async function motisRoute(dest,modes,transit=true){const dt=`${finderDate.value}T${finderTime.value}:00+02:00`;const u=new URL('https://api.transitous.org/api/v6/plan');u.searchParams.set('fromPlace',proximityOrigin.join(','));u.searchParams.set('toPlace',dest.join(','));u.searchParams.set('time',dt);u.searchParams.set('arriveBy','true');u.searchParams.set('numItineraries','3');u.searchParams.set('detailedLegs','true');u.searchParams.set('detailedTransfers','true');u.searchParams.set('language','fr');u.searchParams.set('maxDirectTime','7200');if(transit){u.searchParams.set('transitModes','TRANSIT');u.searchParams.set('directModes','');u.searchParams.set('preTransitModes','WALK');u.searchParams.set('postTransitModes','WALK')}else{u.searchParams.set('transitModes','');u.searchParams.set('directModes',modes)}const r=await fetch(u);if(!r.ok)throw Error('Calcul indisponible');return r.json()}
function durationText(sec){if(sec==null)return '—';const m=Math.round(sec/60);return m>=60?`${Math.floor(m/60)} h ${m%60} min`:`${m} min`}
function legName(l){return l.routeShortName||l.route?.shortName||l.route?.short_name||l.mode||''}
function placeName(p){return p?.name||p?.stop?.name||p?.vertexType||''}
function fmtTime(x){if(!x)return '';const d=new Date(x);return isNaN(d)?'':d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function itineraryCard(it){const legs=it.legs||[];const dep=fmtTime(it.startTime||legs[0]?.startTime),arr=fmtTime(it.endTime||legs.at(-1)?.endTime);return `<div class="route-itinerary"><div class="toolbar"><b>${dep||'Départ'} → ${arr||'Arrivée'}</b><span class="pill">${durationText(it.duration)}</span></div>${legs.map(l=>{const mode=(l.mode||'').toUpperCase(),trans=!['WALK','FOOT','BIKE','CAR'].includes(mode),from=placeName(l.from),to=placeName(l.to),line=legName(l),head=l.headsign||l.trip?.headsign||'';return `<div class="route-leg"><span class="route-icon">${mode.includes('TRAM')?'🚋':mode.includes('BUS')?'🚌':mode==='CAR'?'🚗':mode.includes('BIKE')?'🚲':'🚶'}</span><div><b>${trans?(line?`Ligne ${esc(line)}`:'Transport SETRAM'):(mode==='CAR'?'Voiture':mode.includes('BIKE')?'Vélo':'Marche')}</b>${head?` <span class="muted">direction ${esc(head)}</span>`:''}<div>${from?`${fmtTime(l.startTime)} · ${esc(from)}`:''}${to?`<br>${fmtTime(l.endTime)} · ${esc(to)}`:''}</div>${l.intermediateStops?.length?`<small class="muted">${l.intermediateStops.length} arrêt(s) intermédiaire(s)</small>`:''}</div></div>`}).join('')}</div>`}
async function openRoutes(id){const f=db.families.find(x=>x.id===id),dest=familyPos(f);if(!proximityOrigin||!dest)return;modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><h2>Itinéraires — ${esc(f.name)}</h2><p class="muted">Arrivée souhaitée le ${finderDate.value} à ${finderTime.value}. Les transports sont calculés pour cette période.</p><div class="route-tabs"><button class="ghost" onclick="loadRouteMode(${id},'TRANSIT')">🚌🚋 SETRAM</button><button class="ghost" onclick="loadRouteMode(${id},'WALK')">🚶 À pied</button><button class="ghost" onclick="loadRouteMode(${id},'BIKE')">🚲 Vélo</button><button class="ghost" onclick="loadRouteMode(${id},'CAR')">🚗 Voiture</button></div><div id="routeDetail"><p>Calcul de l’itinéraire…</p></div></div>`;modal.classList.remove('hidden');loadRouteMode(id,'TRANSIT')}
async function loadRouteMode(id,mode){const f=db.families.find(x=>x.id===id),dest=familyPos(f);routeDetail.innerHTML='<p class="muted">Calcul en cours…</p>';try{const j=await motisRoute(dest,mode,mode==='TRANSIT');const its=(j.itineraries||j.direct||[]);if(!its.length)throw Error('Aucun itinéraire trouvé pour cette date et cette heure.');routeDetail.innerHTML=its.slice(0,3).map(itineraryCard).join('')}catch(e){routeDetail.innerHTML=`<div class="alert"><b>Itinéraire détaillé indisponible</b><div class="muted">${esc(e.message)}. Aucune durée n’est inventée : réessayez ou changez la date/heure.</div></div>`}}
