/* Recherche de proximité FI/FIJ + itinéraires multimodaux. Transit: MOTIS/Transitous (GTFS/GTFS-RT). */
let proximityOrigin=null, proximityMap=null;
const km=(a,b,c,d)=>{const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const familyPos=f=>f?._mapPos||(f.latitude&&f.longitude?[+f.latitude,+f.longitude]:(SECTOR_COORDS[f.neighborhood]||null));
async function geocodeFamilyAddress(f){if(familyPos(f)||!f?.address)return familyPos(f);try{const r=await fetch('https://data.geopf.fr/geocodage/search/?q='+encodeURIComponent(f.address)+'&limit=1&autocomplete=0');if(!r.ok)return null;const j=await r.json(),x=j.features?.[0];if(!x)return null;f._mapPos=[+x.geometry.coordinates[1],+x.geometry.coordinates[0]];return f._mapPos}catch(e){return null}}
async function ensureAllFamilyPositions(){const physical=db.families.filter(f=>!f.is_online&&!['Fermée','Fermée / Archivée','Fermée-Archivée'].includes(f.status));await Promise.all(physical.map(geocodeFamilyAddress));return physical}
function finderType(){return document.querySelector('input[name="finderType"]:checked')?.value||'ALL'}
function finderFamilies(){const t=finderType();return db.families.filter(f=>(t==='ALL'||f.family_type===t)&&!['Fermée','Fermée / Archivée'].includes(f.status));}
async function geocodeFinder(){const q=(finderAddress.value||'').trim();if(!q)return alert('Saisissez une adresse de départ.');finderStatus.textContent='Recherche de l’adresse…';try{const r=await fetch('https://data.geopf.fr/geocodage/search/?q='+encodeURIComponent(q)+'&limit=1&autocomplete=0');if(!r.ok)throw Error('Recherche indisponible');const j=await r.json(),x=j.features?.[0];if(!x)throw Error('Adresse introuvable.');const a=compactBanAddress(x),label=[a.main,a.city].filter(Boolean).join(', ');proximityOrigin=[+x.geometry.coordinates[1],+x.geometry.coordinates[0]];finderAddress.value=label;finderStatus.textContent=label;renderFinderResults()}catch(e){finderStatus.textContent='';alert(e.message)}}
let finderSuggestTimer=null,finderSuggestAbort=null,finderSuggestRows=[],finderSuggestSeq=0;
function compactBanAddress(f){const p=f.properties||{},num=p.housenumber||'',street=p.street||p.name||'',city=p.city||p.municipality||'';return {main:[num,street].filter(Boolean).join(' ')||p.label||'',city:city||''}}
async function fetchFinderSuggestions(q){const seq=++finderSuggestSeq;if(finderSuggestAbort)finderSuggestAbort.abort();finderSuggestAbort=new AbortController();const box=document.getElementById('finderAddressSuggest');if(!box)return;try{const r=await fetch('https://data.geopf.fr/geocodage/search/?q='+encodeURIComponent(q)+'&limit=8&autocomplete=1',{signal:finderSuggestAbort.signal});if(!r.ok)throw Error('Recherche indisponible');const j=await r.json();if(seq!==finderSuggestSeq)return;finderSuggestRows=(j.features||[]).map(f=>({lat:+f.geometry.coordinates[1],lon:+f.geometry.coordinates[0],...compactBanAddress(f)}));if(finderSuggestRows.length)box.innerHTML=finderSuggestRows.map((x,i)=>'<button type="button" onclick="chooseFinderSuggestion('+i+')"><b>'+esc(x.main)+'</b>'+(x.city?'<small>'+esc(x.city)+'</small>':'')+'</button>').join('');else if(q.length>=5)box.innerHTML='<span class="address-empty-v181">Aucune adresse proposée.</span>';box.classList.remove('hidden')}catch(e){if(e.name!=='AbortError'&&seq===finderSuggestSeq&&q.length>=5){box.innerHTML='<span class="address-empty-v181">Recherche momentanément indisponible.</span>';box.classList.remove('hidden')}}}
function setupFinderAutocomplete(){const input=document.getElementById('finderAddress'),box=document.getElementById('finderAddressSuggest');if(!input||!box||input.dataset.autocompleteReady)return;input.dataset.autocompleteReady='1';input.addEventListener('input',()=>{clearTimeout(finderSuggestTimer);const q=input.value.trim();if(q.length<3){finderSuggestRows=[];box.classList.add('hidden');return}finderSuggestTimer=setTimeout(()=>fetchFinderSuggestions(q),180)});input.addEventListener('focus',()=>{if(finderSuggestRows.length&&input.value.trim().length>=3)box.classList.remove('hidden')});document.addEventListener('click',e=>{if(!e.target.closest('.finder-address-wrap'))box.classList.add('hidden')})}
function chooseFinderSuggestion(i){const x=finderSuggestRows[i];if(!x)return;const label=[x.main,x.city].filter(Boolean).join(', ');finderAddress.value=label;proximityOrigin=[x.lat,x.lon];finderStatus.textContent=label;document.getElementById('finderAddressSuggest')?.classList.add('hidden');renderFinderResults()}
function useMemberAddress(){const m=db.members.find(x=>x.id===profile?.member?.id);if(!m?.address)return alert('Aucune adresse renseignée sur votre fiche.');finderAddress.value=m.address;geocodeFinder()}
function renderFinderResults(){if(!proximityOrigin)return;const fs=finderFamilies().map(f=>{const p=familyPos(f);return {...f,_pos:p,_km:p?km(proximityOrigin[0],proximityOrigin[1],p[0],p[1]):999}}).sort((a,b)=>a._km-b._km);finderResults.innerHTML=fs.map(f=>`<div class="finder-result"><div><span class="pill ${f.family_type.toLowerCase()}">${f.family_type}</span> <b>${esc(f.name)}</b><div class="muted">${esc(f.neighborhood_detail||f.neighborhood||'Secteur à préciser')} · ${f._pos?(f._km.toFixed(1)+' km à vol d’oiseau'):'adresse à géolocaliser'}${f.status&&f.status!=='Active'?' · '+esc(f.status):''}</div></div><div class="row-actions"><button class="ghost" onclick="openFamily(${f.id})">Voir la FI</button>${f._pos?`<button class="primary" onclick="openRoutes(${f.id})">Comparer les trajets</button>`:''}</div></div>`).join('')||'<p class="muted">Aucune famille correspondante.</p>';drawFinderMap(fs)}
function baseMap(el,center=[48.006,0.199],zoom=11){if(proximityMap)proximityMap.remove();proximityMap=L.map(el).setView(center,zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(proximityMap);return proximityMap}
function drawFinderMap(fs){if(!document.getElementById('finderMap'))return;baseMap('finderMap',proximityOrigin||[48.006,0.199],12);if(proximityOrigin)L.marker(proximityOrigin).addTo(proximityMap).bindPopup('<b>Départ</b>');fs.filter(f=>f._pos||familyPos(f)).forEach(f=>{const p=f._pos||familyPos(f),color=f.family_type==='FI'?'#0369a1':'#be185d';L.circleMarker(p,{radius:9,color,fillColor:color,fillOpacity:.9}).addTo(proximityMap).bindPopup('<b>'+esc(f.name)+'</b><br>'+esc(f.address||f.area||f.neighborhood||'')+'<br><button class="ghost" onclick="openFamilyMapCard('+f.id+')">Voir la FI</button>')});}
function familyLeaderNames(fid,role){const ids=(db.role_assignments||[]).filter(r=>+r.family_id===+fid&&r.active&&r.role===role).map(r=>+r.member_id);return ids.map(id=>{const m=db.members.find(x=>+x.id===id);return m?[m.first_name,m.last_name].filter(Boolean).join(' '):''}).filter(Boolean).join(', ')}
function openFamilyMapCard(id){const f=db.families.find(x=>+x.id===+id);if(!f)return;const count=(db.family_memberships||db.family_members||[]).filter(x=>+x.family_id===+id&&(x.active!==false)).length;modal.innerHTML='<div class="modal-card map-family-card"><button class="close" onclick="closeModal()">×</button><span class="pill '+f.family_type.toLowerCase()+'">'+esc(f.family_type)+'</span><h2>'+esc(f.name)+'</h2><div class="detail-grid"><div><small>Adresse</small><b>'+esc(f.address||'À préciser')+'</b></div><div><small>Pilote</small><b>'+esc(familyLeaderNames(id,'pilote')||'À préciser')+'</b></div><div><small>Copilote</small><b>'+esc(familyLeaderNames(id,'copilote')||'À préciser')+'</b></div><div><small>Hôte</small><b>'+esc(f.host_name||'À préciser')+'</b></div><div><small>Rencontre</small><b>'+esc([f.regular_day,f.regular_start?.slice?.(0,5)+(f.regular_end?' → '+f.regular_end.slice(0,5):'')].filter(Boolean).join(' · ')||'À préciser')+'</b></div><div><small>Membres</small><b>'+count+'</b></div></div></div>';modal.classList.remove('hidden')}
function finderPanel(){return `<div class="card finder"><div class="toolbar"><div><h2>📍 Trouver une FI / FIJ proche</h2><p class="muted">Comparez la proximité et les trajets selon la date et l’heure de la rencontre.</p></div><div class="finder-types"><label><input type="radio" name="finderType" value="ALL" checked onchange="renderFinderResults()"> Tout</label><label><input type="radio" name="finderType" value="FI" onchange="renderFinderResults()"> FI</label><label><input type="radio" name="finderType" value="FIJ" onchange="renderFinderResults()"> FIJ</label></div></div><div class="finder-search"><div class="finder-address-wrap"><input id="finderAddress" placeholder="Adresse de départ" autocomplete="off"><div id="finderAddressSuggest" class="address-suggest-v11 hidden"></div></div><input id="finderDate" type="date" value="${dateISO(new Date())}"><input id="finderTime" type="time" value="19:00"><button class="primary" onclick="geocodeFinder()">Rechercher</button></div><div class="row-actions"><button class="ghost" onclick="useMemberAddress()">Utiliser mon adresse enregistrée</button><span id="finderStatus" class="muted"></span></div><div id="finderMap" class="finder-map"></div><div id="finderResults"></div><p class="muted finder-credit">Transports publics : données ouvertes GTFS/GTFS-RT, calcul Transitous/MOTIS · Carte © OpenStreetMap.</p></div>`}
mapPage=function(){setTimeout(async()=>{setupFinderAutocomplete();const el=document.getElementById('finderMap');if(!el)return;const all=await ensureAllFamilyPositions();if(proximityOrigin)renderFinderResults();else drawFinderMap(all.map(f=>({...f,_pos:familyPos(f)})))},50);return finderPanel()};
async function motisRoute(dest,modes,transit=true){const dt=`${finderDate.value}T${finderTime.value}:00+02:00`;const u=new URL('https://api.transitous.org/api/v6/plan');u.searchParams.set('fromPlace',proximityOrigin.join(','));u.searchParams.set('toPlace',dest.join(','));u.searchParams.set('time',dt);u.searchParams.set('arriveBy','true');u.searchParams.set('numItineraries','3');u.searchParams.set('detailedLegs','true');u.searchParams.set('detailedTransfers','true');u.searchParams.set('language','fr');u.searchParams.set('maxDirectTime','7200');if(transit){u.searchParams.set('transitModes','TRANSIT');u.searchParams.set('directModes','');u.searchParams.set('preTransitModes','WALK');u.searchParams.set('postTransitModes','WALK')}else{u.searchParams.set('transitModes','');u.searchParams.set('directModes',modes)}const r=await fetch(u);if(!r.ok)throw Error('Calcul indisponible');return r.json()}
function durationText(sec){if(sec==null)return '—';const m=Math.round(sec/60);return m>=60?`${Math.floor(m/60)} h ${m%60} min`:`${m} min`}
function legName(l){return l.routeShortName||l.route?.shortName||l.route?.short_name||l.mode||''}
function placeName(p){return p?.name||p?.stop?.name||p?.vertexType||''}
function fmtTime(x){if(!x)return '';const d=new Date(x);return isNaN(d)?'':d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function itineraryCard(it){const legs=it.legs||[];const dep=fmtTime(it.startTime||legs[0]?.startTime),arr=fmtTime(it.endTime||legs.at(-1)?.endTime);return `<div class="route-itinerary"><div class="toolbar"><b>${dep||'Départ'} → ${arr||'Arrivée'}</b><span class="pill">${durationText(it.duration)}</span></div>${legs.map(l=>{const mode=(l.mode||'').toUpperCase(),trans=!['WALK','FOOT','BIKE','CAR'].includes(mode),from=placeName(l.from),to=placeName(l.to),line=legName(l),head=l.headsign||l.trip?.headsign||'';return `<div class="route-leg"><span class="route-icon">${mode.includes('TRAM')?'🚋':mode.includes('BUS')?'🚌':mode==='CAR'?'🚗':mode.includes('BIKE')?'🚲':'🚶'}</span><div><b>${trans?(line?`Ligne ${esc(line)}`:'Transport SETRAM'):(mode==='CAR'?'Voiture':mode.includes('BIKE')?'Vélo':'Marche')}</b>${head?` <span class="muted">direction ${esc(head)}</span>`:''}<div>${from?`${fmtTime(l.startTime)} · ${esc(from)}`:''}${to?`<br>${fmtTime(l.endTime)} · ${esc(to)}`:''}</div>${l.intermediateStops?.length?`<small class="muted">${l.intermediateStops.length} arrêt(s) intermédiaire(s)</small>`:''}</div></div>`}).join('')}</div>`}
async function openRoutes(id){const f=db.families.find(x=>x.id===id),dest=familyPos(f);if(!proximityOrigin||!dest)return;modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><h2>Itinéraires — ${esc(f.name)}</h2><p class="muted">Arrivée souhaitée le ${finderDate.value} à ${finderTime.value}. Les transports sont calculés pour cette période.</p><div class="route-tabs"><button class="ghost" onclick="loadRouteMode(${id},'TRANSIT')">🚌🚋 SETRAM</button><button class="ghost" onclick="loadRouteMode(${id},'WALK')">🚶 À pied</button><button class="ghost" onclick="loadRouteMode(${id},'BIKE')">🚲 Vélo</button><button class="ghost" onclick="loadRouteMode(${id},'CAR')">🚗 Voiture</button></div><div id="routeDetail"><p>Calcul de l’itinéraire…</p></div></div>`;modal.classList.remove('hidden');loadRouteMode(id,'TRANSIT')}
function decodePolyline6(s){let i=0,lat=0,lng=0,out=[];while(i<s.length){let b,shift=0,res=0;do{b=s.charCodeAt(i++)-63;res|=(b&31)<<shift;shift+=5}while(b>=32);lat+=(res&1)?~(res>>1):(res>>1);shift=0;res=0;do{b=s.charCodeAt(i++)-63;res|=(b&31)<<shift;shift+=5}while(b>=32);lng+=(res&1)?~(res>>1):(res>>1);out.push([lat/1e6,lng/1e6])}return out}
function legCoords(l){const g=l.legGeometry||l.geometry;if(g?.coordinates)return g.coordinates.map(x=>[x[1],x[0]]);if(typeof g?.points==='string'){try{return decodePolyline6(g.points)}catch(e){}}const a=l.from,b=l.to;if(a?.lat!=null&&a?.lon!=null&&b?.lat!=null&&b?.lon!=null)return [[+a.lat,+a.lon],[+b.lat,+b.lon]];return []}
function drawRouteMapV204(dest,route,transit=false){const el=document.getElementById('routeMapV204');if(!el)return;const m=L.map(el).setView(proximityOrigin,13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);L.marker(proximityOrigin).addTo(m).bindPopup('Départ');L.marker(dest).addTo(m).bindPopup('Arrivée');let lines=[];if(transit){for(const l of route.legs||[]){const pts=legCoords(l);if(pts.length>1){L.polyline(pts,{weight:5,opacity:.8,dashArray:(l.mode||'').toUpperCase()==='WALK'?'7 8':null}).addTo(m);lines.push(...pts)}}}else if(route.geometry?.coordinates){const pts=route.geometry.coordinates.map(x=>[x[1],x[0]]);L.polyline(pts,{weight:6,opacity:.85}).addTo(m);lines=pts}if(lines.length)m.fitBounds(L.latLngBounds(lines.concat([proximityOrigin,dest])),{padding:[25,25]});setTimeout(()=>m.invalidateSize(),50)}
async function directRouteV204(dest,mode){const p=mode==='CAR'?'car':mode==='BIKE'?'bike':'foot',coords=proximityOrigin[1]+','+proximityOrigin[0]+';'+dest[1]+','+dest[0],u='https://routing.openstreetmap.de/routed-'+p+'/route/v1/driving/'+coords+'?overview=full&geometries=geojson&steps=true';const r=await fetch(u);if(!r.ok)throw Error('Calcul indisponible');const j=await r.json();if(!j.routes?.length)throw Error('Aucun itinéraire trouvé');return j.routes[0]}
async function loadRouteMode(id,mode){const f=db.families.find(x=>x.id===id),dest=familyPos(f);routeDetail.innerHTML='<p class="muted">Calcul en cours…</p>';try{if(mode!=='TRANSIT'){const r=await directRouteV204(dest,mode),label=mode==='CAR'?'🚗 Voiture':mode==='BIKE'?'🚲 Vélo':'🚶 À pied';routeDetail.innerHTML='<div class="route-summary-v204"><b>'+label+'</b><span class="pill">'+durationText(r.duration)+'</span><span>'+((r.distance||0)/1000).toFixed(1)+' km</span></div><div id="routeMapV204" class="route-map-v204"></div>';drawRouteMapV204(dest,r,false);return}const j=await motisRoute(dest,mode,true),its=(j.itineraries||j.direct||[]);if(!its.length)throw Error('Aucun itinéraire SETRAM trouvé pour cette date et cette heure.');routeDetail.innerHTML='<div id="routeMapV204" class="route-map-v204"></div>'+its.slice(0,3).map((it,i)=>'<div class="transit-option-v204"><div class="option-title-v204">Option '+(i+1)+'</div>'+itineraryCard(it)+'</div>').join('');drawRouteMapV204(dest,its[0],true)}catch(e){routeDetail.innerHTML='<div class="alert"><b>Itinéraire indisponible</b><div class="muted">'+esc(e.message)+'. Aucune durée n’est inventée.</div></div>'}}
