/* Push v4 — PWA/iPhone/desktop : permission, service worker, appareils. */
let pushRegV4=null;
function pushSupportedV4(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function deviceInfoV4(){const ua=navigator.userAgent;let browser=/Edg/i.test(ua)?'Edge':/CriOS|Chrome/i.test(ua)?'Chrome':/FxiOS|Firefox/i.test(ua)?'Firefox':/Safari/i.test(ua)?'Safari':'Navigateur';let type=/iPhone/i.test(ua)?'iPhone':/iPad/i.test(ua)?'iPad':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Macintosh/i.test(ua)?'Mac':'Appareil';return{device_name:`${type} · ${browser}`,device_type:type,browser}}
async function initPushV4(){if(!pushSupportedV4())return null;pushRegV4=await navigator.serviceWorker.register('./sw.js',{scope:'./'});return pushRegV4}
async function registerDeviceV4(){if(!profile?.user?.id)return;const info=deviceInfoV4(),perm=pushSupportedV4()?Notification.permission:'unsupported';const payload={user_id:profile.user.id,...info,permission_state:perm,push_enabled:perm==='granted',last_seen_at:new Date().toISOString()};const existing=(db.devices||[]).find(d=>d.device_name===info.device_name);const q=existing?await sb.from('user_devices').update(payload).eq('id',existing.id):await sb.from('user_devices').insert(payload);if(q.error)console.warn('device registration',q.error.message)}
async function enablePushV4(){if(!pushSupportedV4())return alert('Les notifications push ne sont pas prises en charge par ce navigateur.');await initPushV4();const p=await Notification.requestPermission();if(p!=='granted'){await registerDeviceV4();return alert('Les notifications ne sont pas autorisées sur cet appareil. Vous pouvez les réactiver dans les réglages du navigateur ou de l’app.')};await registerDeviceV4();alert('Notifications activées sur cet appareil. Le canal système est prêt ; la livraison distante sera activée dès que la clé Web Push serveur est configurée.');await loadData();render()}
async function disablePushDeviceV4(id){const q=await sb.from('user_devices').update({push_enabled:false,permission_state:Notification.permission,last_seen_at:new Date().toISOString()}).eq('id',id);if(q.error)return alert(q.error.message);await loadData();render()}
async function removePushDeviceV4(id){if(!confirm('Déconnecter cet appareil des notifications ?'))return;const q=await sb.from('user_devices').delete().eq('id',id);if(q.error)return alert(q.error.message);await loadData();render()}
function pushDevicePanelV4(){const devices=(db.devices||[]).filter(d=>d.user_id===profile?.user?.id);return `<div class="card"><div class="toolbar"><div><p class="eyebrow">APPAREILS & PUSH</p><h3>Mes appareils</h3></div><button class="primary" onclick="enablePushV4()">Activer sur cet appareil</button></div><p class="muted">Un appareil reste enregistré jusqu’à sa suppression. Vous pouvez désactiver le push appareil par appareil.</p>${devices.map(d=>`<div class="family-row"><div><b>${esc(d.device_name||d.device_type||'Appareil')}</b><div class="muted">${esc(d.browser||'')} · ${d.permission_state||'permission inconnue'} · vu ${new Date(d.last_seen_at).toLocaleString('fr-FR')}</div></div><div class="row-actions"><span class="pill ${d.push_enabled?'ok':''}">${d.push_enabled?'Push actif':'Push désactivé'}</span>${d.push_enabled?`<button class="ghost" onclick="disablePushDeviceV4(${d.id})">Désactiver</button>`:''}<button class="ghost danger" onclick="removePushDeviceV4(${d.id})">Supprimer</button></div></div>`).join('')||'<p class="muted">Aucun appareil enregistré.</p>'}</div>`}
const _settingsNotificationsPushV4=typeof settingsNotifications==='function'?settingsNotifications:null;if(_settingsNotificationsPushV4)settingsNotifications=function(){return _settingsNotificationsPushV4()+notificationPreferencesV4()+pushDevicePanelV4()};
const _bootPushV4=typeof boot==='function'?boot:null;if(_bootPushV4)boot=async function(){const out=await _bootPushV4();try{await initPushV4();await registerDeviceV4()}catch(e){console.warn(e)}return out};
