/* Push v4 — abonnement Web Push réel + gestion sécurisée des appareils. */
let pushRegV4=null;
function pushSupportedV4(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function deviceInfoV4(){const ua=navigator.userAgent;let browser=/Edg/i.test(ua)?'Edge':/CriOS|Chrome/i.test(ua)?'Chrome':/FxiOS|Firefox/i.test(ua)?'Firefox':/Safari/i.test(ua)?'Safari':'Navigateur';let type=/iPhone/i.test(ua)?'iPhone':/iPad/i.test(ua)?'iPad':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Macintosh/i.test(ua)?'Mac':'Appareil';return{device_name:`${type} · ${browser}`,device_type:type,browser}}
function vapidBytesV4(s){const pad='='.repeat((4-s.length%4)%4),b64=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function initPushV4(){if(!pushSupportedV4())return null;pushRegV4=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;return pushRegV4}
async function fingerprintV4(){const i=deviceInfoV4();return [i.device_type,i.browser,navigator.platform||'',navigator.language||''].join('|')}
async function saveDeviceV4(subscription,enabled){const i=deviceInfoV4(),fp=await fingerprintV4();const q=await sb.rpc('save_my_push_device',{p_device_name:i.device_name,p_device_type:i.device_type,p_browser:i.browser,p_permission_state:Notification.permission,p_subscription:subscription?subscription.toJSON():null,p_fingerprint:fp,p_enabled:!!enabled});if(q.error)throw q.error;return q.data}
async function registerDeviceV4(){if(!session?.user||!pushSupportedV4())return;await initPushV4();const sub=await pushRegV4.pushManager.getSubscription();await saveDeviceV4(sub,Notification.permission==='granted'&&!!sub)}
async function enablePushV4(){if(!pushSupportedV4())return alert('Les notifications push ne sont pas prises en charge par ce navigateur.');try{await initPushV4();const p=await Notification.requestPermission();if(p!=='granted'){await saveDeviceV4(null,false);return alert('Les notifications ne sont pas autorisées sur cet appareil.')}const k=await sb.rpc('get_push_public_key');if(k.error||!k.data)throw Error('Clé Web Push publique indisponible.');let sub=await pushRegV4.pushManager.getSubscription();if(!sub)sub=await pushRegV4.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidBytesV4(k.data)});await saveDeviceV4(sub,true);alert('Notifications push activées sur cet appareil.');await loadData();render()}catch(e){console.error('push',e);alert('Activation Push impossible : '+(e.message||e))}}
async function disablePushDeviceV4(id){const q=await sb.rpc('disable_my_push_device',{p_id:id});if(q.error)return alert(q.error.message);await loadData();render()}
async function removePushDeviceV4(id){if(!confirm('Déconnecter cet appareil des notifications ?'))return;const q=await sb.rpc('delete_my_push_device',{p_id:id});if(q.error)return alert(q.error.message);await loadData();render()}
function pushDevicePanelV4(){const devices=(db.devices||[]).filter(d=>d.user_id===session?.user?.id);return `<div class="card"><div class="toolbar"><div><p class="eyebrow">APPAREILS & PUSH</p><h3>Mes appareils</h3></div><button class="primary" onclick="enablePushV4()">Activer sur cet appareil</button></div><p class="muted">Le Push doit être autorisé séparément sur chaque appareil.</p>${devices.map(d=>`<div class="family-row"><div><b>${esc(d.device_name||d.device_type||'Appareil')}</b><div class="muted">${esc(d.browser||'')} · ${d.permission_state||'permission inconnue'}</div></div><div class="row-actions"><span class="pill ${d.push_enabled&&d.push_subscription?'ok':''}">${d.push_enabled&&d.push_subscription?'Push actif':'Push désactivé'}</span>${d.push_enabled?`<button class="ghost" onclick="disablePushDeviceV4(${d.id})">Désactiver</button>`:''}<button class="ghost danger" onclick="removePushDeviceV4(${d.id})">Supprimer</button></div></div>`).join('')||'<p class="muted">Aucun appareil enregistré.</p>'}</div>`}
const _settingsNotificationsPushV4=typeof settingsNotifications==='function'?settingsNotifications:null;if(_settingsNotificationsPushV4)settingsNotifications=function(){return _settingsNotificationsPushV4()+notificationPreferencesV4()+pushDevicePanelV4()};
const _bootPushV4=typeof boot==='function'?boot:null;if(_bootPushV4)boot=async function(){const out=await _bootPushV4();try{if(session?.user&&Notification.permission==='granted')await registerDeviceV4()}catch(e){console.warn('push registration',e)}return out};