/* Push v4 — chaque appareil est recensé dès la connexion ; le Push reste un choix séparé. */
let pushRegV4=null;
function pushSupportedV4(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function deviceInfoV4(){const ua=navigator.userAgent;let browser=/Edg/i.test(ua)?'Edge':/CriOS|Chrome/i.test(ua)?'Chrome':/FxiOS|Firefox/i.test(ua)?'Firefox':/Safari/i.test(ua)?'Safari':'Navigateur';let type=/iPhone/i.test(ua)?'iPhone':/iPad/i.test(ua)?'iPad':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Macintosh/i.test(ua)?'Mac':'Appareil';return{device_name:`${type} · ${browser}`,device_type:type,browser}}
function vapidBytesV4(s){const pad='='.repeat((4-s.length%4)%4),b64=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function initPushV4(){if(!pushSupportedV4())return null;pushRegV4=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;return pushRegV4}
async function fingerprintV4(){return await new Promise((resolve,reject)=>{try{const req=indexedDB.open('fi-device-identity',1);req.onupgradeneeded=()=>{try{req.result.createObjectStore('identity')}catch(_){}};req.onsuccess=()=>{const db=req.result;try{const tx=db.transaction('identity','readwrite'),store=tx.objectStore('identity'),get=store.get('device_id');get.onsuccess=()=>{if(get.result){resolve(get.result);return}const id=crypto.randomUUID?crypto.randomUUID():`1790144775526-${Math.random().toString(36).slice(2)}`;store.put(id,'device_id');tx.oncomplete=()=>resolve(id);tx.onerror=()=>resolve(id)}}catch(e){reject(e)}};req.onerror=()=>reject(req.error||new Error('IndexedDB indisponible'))}catch(e){reject(e)}})}
async function saveDeviceV4(subscription,enabled){const i=deviceInfoV4(),fp=await fingerprintV4(),permission=pushSupportedV4()?Notification.permission:'unsupported';const q=await sb.rpc('save_my_push_device',{p_device_name:i.device_name,p_device_type:i.device_type,p_browser:i.browser,p_permission_state:permission,p_subscription:subscription?subscription.toJSON():null,p_fingerprint:fp,p_enabled:!!enabled});if(q.error)throw q.error;return q.data}
async function registerDeviceV4(){if(!session?.user)return;let sub=null;if(pushSupportedV4()){try{await initPushV4();sub=await pushRegV4.pushManager.getSubscription();if(!sub&&Notification.permission==='granted'){const k=await sb.rpc('get_push_public_key');if(!k.error&&k.data){const keyBytes=vapidBytesV4(String(k.data).trim());if(keyBytes.length===65&&keyBytes[0]===4)sub=await pushRegV4.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes.buffer})}}}catch(e){console.warn('service worker/push subscription',e)}}await saveDeviceV4(sub,!!sub&&Notification.permission==='granted')}
async function enablePushV4(){if(!pushSupportedV4())return alert('Les notifications push ne sont pas prises en charge par ce navigateur.');const isiOS=/iPhone|iPad|iPod/i.test(navigator.userAgent);const standalone=window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;if(isiOS&&!standalone)return alert("Sur iPhone/iPad, installez d’abord l’application sur l’écran d’accueil, puis activez le Push depuis l’application.");try{await initPushV4();const p=await Notification.requestPermission();if(p!=='granted'){await saveDeviceV4(null,false);return alert('Les notifications ne sont pas autorisées sur cet appareil.')}const k=await sb.rpc('get_push_public_key');if(k.error||!k.data)throw Error('Clé Web Push publique indisponible.');const keyBytes=vapidBytesV4(String(k.data).trim());if(keyBytes.length!==65||keyBytes[0]!==4)throw Error('La clé Web Push publique est invalide.');try{await crypto.subtle.importKey('raw',keyBytes,{name:'ECDSA',namedCurve:'P-256'},false,['verify'])}catch(_){throw Error('La clé Web Push publique est invalide.')}let sub=await pushRegV4.pushManager.getSubscription();if(!sub)sub=await pushRegV4.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes.buffer});await saveDeviceV4(sub,true);alert('Notifications push activées sur cet appareil.');await loadData();render()}catch(e){console.error('push',e);alert('Activation Push impossible : '+(e.message||e))}}
async function disablePushDeviceV4(id){const q=await sb.rpc('disable_my_push_device',{p_id:id});if(q.error)return alert(q.error.message);await loadData();render()}
async function removePushDeviceV4(id){if(!confirm('Retirer cet appareil de votre liste ?'))return;const q=await sb.rpc('delete_my_push_device',{p_id:id});if(q.error)return alert(q.error.message);await loadData();render()}
function pushDevicePanelV4(){const devices=(adminData?.devices||[]).filter(d=>d.user_id===session?.user?.id);return `<div class="card"><div class="toolbar"><div><p class="eyebrow">MES APPAREILS</p><h3>Appareils connectés</h3></div><button class="primary" onclick="enablePushV4()">Activer le Push ici</button></div><p class="muted">Chaque téléphone, tablette ou ordinateur est recensé automatiquement à la connexion. Le Push est ensuite activé séparément sur les appareils où vous le souhaitez.</p>${devices.map(d=>`<div class="family-row"><div><b>${esc(d.device_name||d.device_type||'Appareil')}</b><div class="muted">${esc(d.browser||'')} · dernière activité ${d.last_seen_at?new Date(d.last_seen_at).toLocaleString('fr-FR'):'—'}</div></div><div class="row-actions"><span class="pill ${d.push_enabled&&d.push_subscription?'ok':''}">${d.push_enabled&&d.push_subscription?'Push actif':'Push non activé'}</span>${d.push_enabled?`<button class="ghost" onclick="disablePushDeviceV4(${d.id})">Désactiver Push</button>`:''}<button class="ghost danger" onclick="removePushDeviceV4(${d.id})">Retirer</button></div></div>`).join('')||'<p class="muted">Aucun appareil recensé pour ce compte.</p>'}</div>`}
const _bootPushV4=typeof boot==='function'?boot:null;if(_bootPushV4)boot=async function(){const out=await _bootPushV4();try{if(session?.user){await registerDeviceV4();if(typeof loadAdminSettings==='function')await loadAdminSettings()}}catch(e){console.warn('device registration',e)}return out};