/* Correctifs de régression : fonctionnalités déjà décidées doivent rester accessibles. */
function programsPageCore(){return `<div class="card page-card"><div class="toolbar"><div><h2>Programmes & événements</h2><p class="muted">Programmes, événements, formations et visites pastorales FI/FIJ Tour.</p></div><div class="row-actions">${isDirection()?`<button class="ghost" onclick="fiTourForm()">＋ FI/FIJ Tour</button><button class="primary" onclick="formProgram()">＋ Nouveau programme / événement</button>`:''}</div></div>${db.programs.map(p=>`<div class="family-row clickable" onclick="openProgram(${p.id})"><div><b>${esc(p.title)}</b><div class="muted">${p.kind==='FI/FIJ Tour'?'FI/FIJ Tour · ':''}${p.scheduled_date}${p.end_date&&p.end_date!==p.scheduled_date?' → '+p.end_date:''} · ${esc(p.audience||'')}</div></div><span class="pill">${p.status||'scheduled'}</span></div>`).join('')||'<p class="muted">Aucun programme ou événement.</p>'}</div>`}
programsPage=programsPageCore;
openFamily=function(id){familySpace(id,'overview')};
function templateSettingsCard(t){const v=db.versions.filter(x=>x.template_id===t.id).sort((a,b)=>(b.effective_from||'').localeCompare(a.effective_from||''))[0];return `<div class="family-row"><div class="clickable" onclick="openTemplate(${t.id})"><b>${esc(t.name)}</b><div class="muted">${v?weekdayLabel(v.weekday)+' · '+(v.start_time||'').slice(0,5)+'–'+(v.end_time||'').slice(0,5):'Horaire à configurer'} · Reporting ${t.reporting_required?'requis':'facultatif'}</div></div><div class="row-actions"><span class="pill ${t.family_type.toLowerCase()}">${t.family_type}</span>${isDirection()?`<button class="ghost" onclick="editTemplateDirect(${t.id})">Modifier le modèle</button>`:''}</div></div>`}
settingsMeetings=function(){const timing=settingValue('timing',{}),aw=settingValue('attendance_window',{});return `<div class="section-grid"><div class="card"><h3>Présences & ponctualité</h3><div class="form-stack"><label>Ouverture des présences avant le début (min)<input id="stOpen" type="number" min="0" value="${timing.attendance_open_minutes_before??aw.opens_before_minutes??20}"></label><label>Fermeture de la saisie en direct avant la fin (min)<input id="stClose" type="number" min="0" value="${timing.attendance_close_minutes_before_end??aw.closes_before_end_minutes??15}"></label><label>Tolérance avant retard (min)<input id="stLate" type="number" min="0" value="${timing.late_grace_minutes??5}"></label><label>Tolérance dépassement rencontre (min)<input id="stOver" type="number" min="0" value="${timing.meeting_overrun_grace_minutes??10}"></label><button class="primary" onclick="saveTimingSettings()">Enregistrer</button></div></div><div class="card"><h3>Modèles de rencontres</h3><p class="muted">Modifier corrige le modèle. « Nouvelle configuration » est réservée à un changement réel de planning.</p>${db.templates.map(templateSettingsCard).join('')}</div></div>`};

/* Une séance récurrente FI/FIJ est globale : une annulation/un report concerne toutes les familles de ce type pour cette date. */
function occurrenceGlobalChange(o){return db.changes.find(c=>+c.template_version_id===+o.version?.id&&c.old_date===o.date&&['cancelled','postponed'].includes(c.action))}
async function globalOccurrenceChange(tid,date,action){const t=db.templates.find(x=>+x.id===+tid),v=t&&activeVersion(t,date);if(!t||!v)return alert('Séance introuvable.');const label=action==='cancelled'?'annulation':'report';const raw=prompt(`Motif de l’${label} de la séance ${t.family_type} du ${new Date(date+'T12:00').toLocaleDateString('fr-FR')} (obligatoire) :`);if(raw===null)return;const reason=raw.trim();if(!reason)return alert(`Le motif de l’${label} est obligatoire.`);let newDate=null;if(action==='postponed'){newDate=prompt('Nouvelle date de la séance (AAAA-MM-JJ) :',date);if(newDate===null)return;newDate=newDate.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(newDate)||newDate===date)return alert('Indiquez une nouvelle date valide, différente de la date initiale.')}try{const {error}=await sb.from('schedule_changes').insert({template_version_id:v.id,action,old_date:date,new_date:newDate,reason});if(error)throw error;const existing=db.meetings.filter(m=>m.template_version_id===v.id&&m.scheduled_date===date);for(const m of existing){const patch={status:action==='cancelled'?'cancelled':'postponed'};if(newDate)patch.scheduled_date=newDate;const {error:e}=await sb.from('meetings').update(patch).eq('id',m.id);if(e)throw e}closeModal();await loadData();render()}catch(e){alert(e.message||'Modification impossible.')}}

/* Les occurrences virtuelles tiennent compte de la décision globale. Un report recrée la séance à la nouvelle date, une annulation reste visible comme annulée. */
const _virtualOccurrencesGlobal=virtualOccurrences;virtualOccurrences=function(start,end){const base=_virtualOccurrencesGlobal(start,end),out=[];for(const o of base){const ch=occurrenceGlobalChange(o);if(!ch){out.push(o);continue}if(ch.action==='cancelled'){out.push({...o,globalStatus:'cancelled',globalReason:ch.reason});continue}if(ch.action==='postponed'){if(ch.new_date){const nd=new Date(ch.new_date+'T12:00');if(nd>=start&&nd<=end)out.push({...o,date:ch.new_date,originalDate:o.date,globalStatus:'postponed',globalReason:ch.reason})}}}return out};

openOccurrence=function(o){const ch=occurrenceGlobalChange({...o,date:o.originalDate||o.date});const status=o.globalStatus||ch?.action;modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><span class="pill ${o.type.toLowerCase()}">${o.type}</span><h2>${esc(o.title)}</h2><p>${new Date(o.date+'T12:00').toLocaleDateString('fr-FR')} · ${esc(o.time||'Horaire à préciser')}</p>${o.originalDate?`<p class="muted">Reportée depuis le ${new Date(o.originalDate+'T12:00').toLocaleDateString('fr-FR')}.</p>`:''}${status==='cancelled'?`<div class="notice danger"><b>Séance annulée pour toutes les ${o.type}</b><br>${esc(o.globalReason||ch?.reason||'')}</div>`:`<p class="muted">Cette séance est commune à toutes les ${o.type}. Reporter ou annuler agit donc sur toutes les ${o.type} concernées par cette date, jamais sur une famille isolée.</p><div class="row-actions"><button class="ghost" onclick="globalOccurrenceChange(${o.template.id},'${o.originalDate||o.date}','postponed')">Reporter toute la séance</button><button class="ghost danger" onclick="globalOccurrenceChange(${o.template.id},'${o.originalDate||o.date}','cancelled')">Annuler toute la séance</button></div>`}</div>`;modal.classList.remove('hidden')};

meetingsPage=function(){const [s,e]=periodBounds(),virtual=virtualOccurrences(s,e),dated=db.meetings.filter(m=>m.scheduled_date>=dateISO(s)&&m.scheduled_date<=dateISO(e)&&!m.template_version_id);const rows=[...virtual.map(o=>({date:o.date,html:`<div class="family-row ${o.globalStatus==='cancelled'?'is-cancelled':''}"><div class="clickable" onclick="openOccurrenceBy(${o.template.id},'${o.originalDate||o.date}')"><b>${esc(o.title)}</b><div class="muted">${new Date(o.date+'T12:00').toLocaleDateString('fr-FR')} · ${o.time||'Horaire à préciser'} · Toutes les ${o.type}${o.globalStatus==='cancelled'?' · Annulée':o.originalDate?' · Reportée':''}</div></div><div class="row-actions"><span class="pill ${o.type.toLowerCase()}">${o.globalStatus==='cancelled'?'ANNULÉE':o.originalDate?'REPORTÉE':o.type}</span>${!o.globalStatus?`<button class="ghost" onclick="globalOccurrenceChange(${o.template.id},'${o.date}','postponed')">Reporter</button><button class="ghost danger" onclick="globalOccurrenceChange(${o.template.id},'${o.date}','cancelled')">Annuler</button>`:`<button class="ghost" onclick="openOccurrenceBy(${o.template.id},'${o.originalDate||o.date}')">Voir</button>`}</div></div>`})),...dated.map(m=>({date:m.scheduled_date,html:`<div class="family-row"><div class="clickable" onclick="openMeeting(${m.id})"><b>${esc(m.title)}</b><div class="muted">${new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')} · ${familyName(m.family_id)}</div></div><span class="pill">${m.status||'scheduled'}</span></div>`}))].sort((a,b)=>a.date.localeCompare(b.date));return `<div class="card page-card"><div class="toolbar"><div><h2>Rencontres</h2><p class="muted">Une séance FI ou FIJ est commune à toutes les familles du type concerné. Un report ou une annulation s’applique à toute la séance.</p></div><button class="primary" onclick="formMeeting()">＋ Rencontre exceptionnelle</button></div><div class="period-tabs">${[['week','Semaine'],['month','Mois'],['quarter','Trimestre'],['semester','Semestre'],['year','Année']].map(([v,l])=>`<button class="${meetingPeriod===v?'active':''}" onclick="setMeetingPeriod('${v}')">${l}</button>`).join('')}</div>${rows.map(x=>x.html).join('')||`<p class="muted">Aucune rencontre sur cette période (${meetingPeriodLabel().toLowerCase()}).</p>`}</div>`};
