/* Correctifs de régression : fonctionnalités déjà décidées doivent rester accessibles. */
function programsPageCore(){return `<div class="card page-card"><div class="toolbar"><div><h2>Programmes & événements</h2><p class="muted">Programmes, événements, formations et visites pastorales FI/FIJ Tour.</p></div><div class="row-actions">${isDirection()?`<button class="ghost" onclick="fiTourForm()">＋ FI/FIJ Tour</button><button class="primary" onclick="formProgram()">＋ Nouveau programme / événement</button>`:''}</div></div>${db.programs.map(p=>`<div class="family-row clickable" onclick="openProgram(${p.id})"><div><b>${esc(p.title)}</b><div class="muted">${p.kind==='FI/FIJ Tour'?'FI/FIJ Tour · ':''}${p.scheduled_date}${p.end_date&&p.end_date!==p.scheduled_date?' → '+p.end_date:''} · ${esc(p.audience||'')}</div></div><span class="pill">${p.status||'scheduled'}</span></div>`).join('')||'<p class="muted">Aucun programme ou événement.</p>'}</div>`}
programsPage=programsPageCore;

/* Ouvrir une FI = véritable espace FI/FIJ, jamais l'ancienne fiche modale simplifiée. */
openFamily=function(id){familySpace(id,'overview')};

/* Les modèles sont modifiables directement depuis Paramètres, sans créer un changement de planning. */
function templateSettingsCard(t){const v=db.versions.filter(x=>x.template_id===t.id).sort((a,b)=>(b.effective_from||'').localeCompare(a.effective_from||''))[0];return `<div class="family-row"><div class="clickable" onclick="openTemplate(${t.id})"><b>${esc(t.name)}</b><div class="muted">${v?weekdayLabel(v.weekday)+' · '+(v.start_time||'').slice(0,5)+'–'+(v.end_time||'').slice(0,5):'Horaire à configurer'} · Reporting ${t.reporting_required?'requis':'facultatif'}</div></div><div class="row-actions"><span class="pill ${t.family_type.toLowerCase()}">${t.family_type}</span>${isDirection()?`<button class="ghost" onclick="editTemplateDirect(${t.id})">Modifier le modèle</button>`:''}</div></div>`}
const _settingsMeetingsRegression=settingsMeetings;settingsMeetings=function(){const timing=settingValue('timing',{}),aw=settingValue('attendance_window',{});return `<div class="section-grid"><div class="card"><h3>Présences & ponctualité</h3><div class="form-stack"><label>Ouverture des présences avant le début (min)<input id="stOpen" type="number" min="0" value="${timing.attendance_open_minutes_before??aw.opens_before_minutes??20}"></label><label>Fermeture de la saisie en direct avant la fin (min)<input id="stClose" type="number" min="0" value="${timing.attendance_close_minutes_before_end??aw.closes_before_end_minutes??15}"></label><label>Tolérance avant retard (min)<input id="stLate" type="number" min="0" value="${timing.late_grace_minutes??5}"></label><label>Tolérance dépassement rencontre (min)<input id="stOver" type="number" min="0" value="${timing.meeting_overrun_grace_minutes??10}"></label><button class="primary" onclick="saveTimingSettings()">Enregistrer</button></div></div><div class="card"><div class="toolbar"><div><h3>Modèles de rencontres</h3><p class="muted">Modifier corrige le modèle. « Nouvelle configuration » reste réservé à un véritable changement de planning à partir d'une date.</p></div></div>${db.templates.map(templateSettingsCard).join('')}</div></div>`};

/* Une occurrence récurrente doit pouvoir être gérée avant même d'avoir été matérialisée. */
function occurrenceManagementButtons(o,f){const m=materializedFor(o,f.id);if(m)return `<button class="ghost" onclick="openMeeting(${m.id})">Gérer</button>`;return `<button class="ghost" onclick="openOccurrenceFamily(${o.template.id},'${o.date}',${f.id})">Gérer</button>`}
openOccurrence=function(o){const past=isOccurrencePast(o),fams=occurrenceFamilies(o);modal.innerHTML=`<div class="modal-card wide"><button class="close" onclick="closeModal()">×</button><span class="pill ${o.type.toLowerCase()}">${o.type}</span><h2>${esc(o.title)}</h2><p>${new Date(o.date+'T12:00').toLocaleDateString('fr-FR')} · ${esc(o.time||'Horaire à préciser')}</p><p class="muted">Choisissez la FI/FIJ concernée pour gérer cette occurrence : ouverture, report ou annulation. Une action sur une occurrence ne modifie pas le modèle hebdomadaire.</p>${fams.map(f=>{const m=materializedFor(o,f.id);return `<div class="family-row"><div><b>${esc(f.name)}</b><div class="muted">${m?esc(m.status||'scheduled'):'Prévue par le modèle'}</div></div><div class="row-actions">${occurrenceManagementButtons(o,f)}</div></div>`}).join('')||'<p class="muted">Aucune famille active concernée.</p>'}</div>`;modal.classList.remove('hidden')};

/* Report / annulation : motif obligatoire et, pour un report, nouvelle date obligatoire. */
scheduleChange=async function(kind,id,action){const table=kind==='meeting'?'meetings':'programs',collection=kind==='meeting'?db.meetings:db.programs,obj=collection.find(x=>+x.id===+id);if(!obj)return alert('Élément introuvable.');const label=action==='cancelled'?'annulation':'report';const raw=prompt(`Motif de l’${label} (obligatoire) :`);if(raw===null)return;const reason=raw.trim();if(!reason)return alert(`Le motif de l’${label} est obligatoire.`);let newDate=null;if(action==='postponed'){newDate=prompt('Nouvelle date (AAAA-MM-JJ) :',obj.scheduled_date||'');if(newDate===null)return;newDate=newDate.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(newDate))return alert('La nouvelle date est obligatoire au format AAAA-MM-JJ.')}try{const change={[`${kind}_id`]:id,action,old_date:obj.scheduled_date,new_date:newDate,reason};const {error:e}=await sb.from('schedule_changes').insert(change);if(e)throw e;const {error}=await sb.from(table).update({status:action==='cancelled'?'cancelled':'postponed',...(newDate?{scheduled_date:newDate}: {})}).eq('id',id);if(error)throw error;closeModal();await loadData();render()}catch(e){alert(e.message||'Modification impossible.')}};

/* Garde Reporter / Annuler explicitement accessibles dans toute rencontre matérialisée. */
const _openMeetingRegression=openMeeting;openMeeting=function(id){const m=db.meetings.find(x=>+x.id===+id);if(!m)return;const past=new Date((m.planned_end||m.planned_start||`${m.scheduled_date}T23:59:59`)).getTime()<=Date.now();modal.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>${esc(m.title)}</h2><p>${new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')} · ${esc(familyName(m.family_id))}</p><span class="pill">${m.status||'scheduled'}</span><div class="row-actions" style="margin-top:18px">${past&&m.status!=='cancelled'?`<button class="primary" onclick="openAttendance('meeting',${id})">✓ Présences</button>${m.reporting_required!==false?`<button class="ghost" onclick="openReporting(${id})">Reporting</button>`:''}`:'<span class="muted">Présences et Reporting disponibles après la rencontre.</span>'}${m.status!=='cancelled'?`<button class="ghost" onclick="scheduleChange('meeting',${id},'postponed')">Reporter</button><button class="ghost danger" onclick="scheduleChange('meeting',${id},'cancelled')">Annuler</button>`:''}</div></div>`;modal.classList.remove('hidden')};
