/* v6 — corrections anti-régression : auth, modèles incomplets, droits réels et menu mobile. */
function validTemplateVersionV6(v){return !!v&&v.weekday!==null&&v.weekday!==undefined&&v.start_time&&v.end_time}
const _activeVersionV6=activeVersion;activeVersion=function(t,date){const v=_activeVersionV6(t,date);return validTemplateVersionV6(v)?v:null}
function effectiveActionScopeV6(key,fid=null){if(isDirection())return'all';const f=fid?db.families.find(x=>+x.id===+fid):null;for(const r of roles){const s=(typeof actionPerms!=='undefined'?actionPerms:[])?.find(x=>x.role===r.role&&x.action_key===key)?.scope||'none';if(s==='all'||(s==='fi'&&(!f||f.family_type==='FI'))||(s==='fij'&&(!f||f.family_type==='FIJ'))||(s==='mine'&&fid&&+r.family_id===+fid))return s}return'none'}
function canActionV6(key,fid=null){return effectiveActionScopeV6(key,fid)!=='none'}
function pageAllowedV6(page){if(isDirection())return true;const map={'Tableau de bord':['dashboard.view'],'FI & FIJ':['fi.view','fij.view'],'Membres':['members.view'],'Rencontres':['meetings.fi.view','meetings.fij.view'],'Programmes & événements':['programs.view'],'Reporting':['reporting.fi.view','reporting.fij.view','reporting.fi.create','reporting.fij.create'],'Pilotage':['pilotage.fi.view','pilotage.fij.view'],'Paramètres':['settings.view']};const keys=map[page];if(keys&&keys.some(k=>canActionV6(k)))return true;return typeof permissionForModule==='function'&&typeof PAGE_MODULE!=='undefined'&&PAGE_MODULE?.[page]?permissionForModule(PAGE_MODULE[page]):true}
allowedItems=function(){if(isDirection())return items.slice();return items.filter(x=>{if(typeof deniedModule==='function'&&typeof PAGE_MODULE!=='undefined'&&deniedModule(PAGE_MODULE[x]))return false;return pageAllowedV6(x)})}
const _goRightsV6=go;go=function(x){if(x!=='Accueil'&&!pageAllowedV6(x)){alert('Vous n’avez pas accès à ce module avec vos permissions actuelles.');return}return _goRightsV6(x)}
function forceAuthVisibilityV6(){const logged=!!session?.user;const ag=document.getElementById('authGate'),ws=document.getElementById('workspace'),side=document.querySelector('#workspace .sidebar'),main=document.querySelector('#workspace main');ag?.classList.toggle('hidden',logged);ws?.classList.toggle('hidden',!logged);document.body.classList.toggle('fi-authenticated',logged);if(logged&&innerWidth>820){if(ws){ws.style.setProperty('display','block','important');ws.style.setProperty('visibility','visible','important')}if(side){side.style.setProperty('display','flex','important');side.style.setProperty('visibility','visible','important');side.style.setProperty('opacity','1','important');side.style.setProperty('width','255px','important');side.style.setProperty('transform','none','important')}if(main){main.style.setProperty('margin-left','255px','important')}}}
function refreshNavigationV6(){const n=document.getElementById('nav');if(!n)return;if(isDirection()){n.innerHTML=items.map(x=>`<button class="${x===current?'active':''}" onclick="go('${x.replace(/'/g,"\\'")}')">${icons[items.indexOf(x)]} &nbsp;<span>${x}</span></button>`).join('')}else navMenu();bindHomeBrand?.()}
const _bootVisibilityV6=boot;boot=async function(){const out=await _bootVisibilityV6();forceAuthVisibilityV6();setupMobileMenuV6();refreshNavigationV6();setTimeout(()=>{forceAuthVisibilityV6();refreshNavigationV6()},100);return out}
const _logoutVisibilityV6=logout;logout=async function(){document.body.classList.remove('fi-authenticated');return _logoutVisibilityV6()}
sb.auth.onAuthStateChange((_event,s)=>{session=s;setTimeout(()=>{forceAuthVisibilityV6();if(s)refreshNavigationV6()},0)});
function setupMobileMenuV6(){const ws=document.getElementById('workspace');if(!ws||document.getElementById('fiMobileMenuBtn'))return;const btn=document.createElement('button');btn.id='fiMobileMenuBtn';btn.className='fi-mobile-menu-btn';btn.setAttribute('aria-label','Ouvrir le menu');btn.innerHTML='☰';btn.onclick=()=>document.body.classList.toggle('fi-mobile-nav-open');document.querySelector('main header')?.prepend(btn);const shade=document.createElement('div');shade.className='fi-mobile-nav-shade';shade.onclick=()=>document.body.classList.remove('fi-mobile-nav-open');ws.appendChild(shade)}
const _navMobileV6=navMenu;navMenu=function(){_navMobileV6();document.getElementById('nav')?.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>document.body.classList.remove('fi-mobile-nav-open')))}
const _goMobileV6=go;go=function(x){const out=_goMobileV6(x);document.body.classList.remove('fi-mobile-nav-open');return out}
window.addEventListener('resize',()=>{if(innerWidth>820){document.body.classList.remove('fi-mobile-nav-open');forceAuthVisibilityV6()}});