/* Reporting v2 — fiche complète de rencontre FI/FIJ. */
function reportTimeValue(v){if(!v)return '';try{return new Date(v).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}catch{return ''}}
function reportBreakdown(r){return Array.isArray(r?.time_breakdown)?r.time_breakdown:[]}
function reportingAttendanceSummary(id){const aa=db.attendance.filter(a=>+a.meeting_id===+id&&a.present);return `<div class="report-section"><div class="report-section-head"><div><p class="eyebrow">PRÉSENCES</p><h3>${aa.length} présent${aa.length>1?'s':''}</h3></div><button type="button" class="ghost" onclick="openAttendance('meeting',${id})">Gérer les présences</button></div>${aa.length?`<div class="report-present-list">${aa.map(a=>`<span class="report-person">${esc(memberName(a.member_id))}${a.arrival_time?` <small>· ${String(a.arrival_time).slice(0,5)}</small>`:a.arrival_unknown?' <small>· heure inconnue</small>':''}</span>`).join('')}</div>`:'<p class="muted">Aucune présence enregistrée. Enregistrez d’abord les présences pour retrouver ici les noms des membres présents.</p>'}</div>`}
function addReportSlot(data={}){const box=document.getElementById('repSlots');if(!box)return;const row=document.createElement('div');row.className='report-slot';row.innerHTML=`<input class="rep-slot-start" type="time" value="${esc(data.start||'')}" onchange="updateReportDuration()"><span class="slot-arrow">→</span><input class="rep-slot-end" type="time" value="${esc(data.end||'')}" onchange="updateReportDuration()"><input class="rep-slot-activity" placeholder="Ce qui a été fait (ex. accueil, partage, prière...)" value="${esc(data.activity||'')}"><input class="rep-slot-desc" placeholder="Description / précision (facultatif)" value="${esc(data.description||'')}"><button type="button" class="ghost danger" onclick="this.parentElement.remove();updateReportDuration()">×</button>`;box.appendChild(row);updateReportDuration()}
function reportSlotMinutes(){return [...document.querySelectorAll('.report-slot')].reduce((sum,row)=>{const a=row.querySelector('.rep-slot-start').value,b=row.querySelector('.rep-slot-end').value;if(!a||!b)return sum;const [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);let n=(bh*60+bm)-(ah*60+am);if(n<0)n+=1440;return sum+n},0)}
function formatReportMinutes(n){if(!n)return '0 min';const h=Math.floor(n/60),m=n%60;return h?`${h} h${m?' '+m+' min':''}`:`${m} min`}
function updateReportDuration(){const n=reportSlotMinutes(),el=document.getElementById('repDuration');if(el)el.textContent=formatReportMinutes(n);const first=document.querySelector('.report-slot .rep-slot-start'),last=[...document.querySelectorAll('.report-slot .rep-slot-end')].pop();if(window.repActualStart&&first?.value)repActualStart.value=first.value;if(window.repActualEnd&&last?.value)repActualEnd.value=last.value}
function toggleReportBreakdown(){const on=repBreakdownEnabled.checked;repBreakdownBox.classList.toggle('hidden',!on);if(on&&!document.querySelector('.report-slot'))addReportSlot()}
function reportSelect(id,label,options,value){return `<label>${label}<select id="${id}">${options.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></label>`}
function toggleMeetingHeldV13(){const yes=document.getElementById('repHeldYes')?.checked;document.getElementById('repHeldBody')?.classList.toggle('hidden',!yes);document.getElementById('repNotHeldBox')?.classList.toggle('hidden',yes)}
openReporting=function(id){const m=db.meetings.find(x=>+x.id===+id),r=db.reports.find(x=>+x.meeting_id===+id);if(!m)return;const held=r?.meeting_held!==false,slots=reportBreakdown(r);modal.innerHTML=`<div class="modal-card wide reporting-sheet"><button class="close" onclick="closeModal()">×</button><div class="report-hero"><div><p class="eyebrow">REPORTING DE RENCONTRE</p><h2>${esc(m.title)}</h2><p class="muted">${new Date(m.scheduled_date+'T12:00').toLocaleDateString('fr-FR')} · ${esc(familyName(m.family_id))}</p></div><span class="pill">${r?.status||'À compléter'}</span></div>${reportingAttendanceSummary(id)}<div class="report-section"><h3>La rencontre a-t-elle bien eu lieu ?</h3><div class="check-row"><label><input id="repHeldYes" name="repHeld" type="radio" ${held?'checked':''} onchange="toggleMeetingHeldV13()"> Oui</label><label><input id="repHeldNo" name="repHeld" type="radio" ${!held?'checked':''} onchange="toggleMeetingHeldV13()"> Non</label></div><div id="repNotHeldBox" class="${held?'hidden':''}"><label>Motif obligatoire<textarea id="repNotHeldReason" rows="4" placeholder="Précisez pourquoi la rencontre n’a pas eu lieu">${esc(r?.not_held_reason||'')}</textarea></label></div></div><div id="repHeldBody" class="${held?'':'hidden'}"><div class="report-section"><h3>Horaires réels</h3><div class="form-row"><label>Début réel<input id="repActualStart" type="time" value="${reportTimeValue(r?.actual_start)}"></label><label>Fin réelle<input id="repActualEnd" type="time" value="${reportTimeValue(r?.actual_end)}"></label></div><label>Notes complémentaires<textarea id="repNotes" rows="5">${esc(r?.notes||'')}</textarea></label></div></div><div class="report-savebar"><button class="primary" onclick="saveReporting(${id})">Enregistrer le Reporting</button></div></div>`;modal.classList.remove('hidden');if(held){slots.forEach(addReportSlot);}}
async function saveReporting(id){const m=db.meetings.find(x=>+x.id===+id);if(!m)throw Error('Rencontre introuvable.');const held=!!document.getElementById('repHeldYes')?.checked,reason=document.getElementById('repNotHeldReason')?.value.trim()||null;if(!held&&!reason)throw Error('Le motif est obligatoire lorsque la rencontre n’a pas eu lieu.');const stamp=t=>t?new Date(`${m.scheduled_date}T${t}:00`).toISOString():null;const payload={meeting_id:id,status:'Validé',meeting_held:held,not_held_reason:held?null:reason,actual_start:held?stamp(document.getElementById('repActualStart')?.value):null,actual_end:held?stamp(document.getElementById('repActualEnd')?.value):null,time_breakdown:[],notes:held?(document.getElementById('repNotes')?.value.trim()||null):null,followup_required:false,submitted_by:session.user.id,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()};const existing=db.reports.find(r=>+r.meeting_id===+id),q=existing?sb.from('reporting').update(payload).eq('id',existing.id):sb.from('reporting').insert(payload);const {error}=await q;if(error)throw error;closeModal();await loadData();render()}
