-- FI ICC Le Mans multi-user foundation
create table if not exists public.app_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  member_id bigint references public.members(id) on delete set null,
  role text not null default 'member' check (role in ('pasteur','super_admin','responsable_fi','responsable_fij','coordinateur_fi','coordinateur_fij','pilote','copilote','member')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.family_user_access (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  family_id bigint not null references public.families(id) on delete cascade,
  access_level text not null default 'manage' check (access_level in ('view','manage')),
  unique(user_id,family_id)
);
alter table public.app_profiles enable row level security;
alter table public.family_user_access enable row level security;

-- Never expose the automatic RLS helper to client roles.
revoke execute on function public.rls_auto_enable() from anon, authenticated;

-- Profiles: users can read their own profile. Direction can read all profiles.
create or replace function public.is_direction() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.app_profiles p where p.user_id=auth.uid() and p.active and p.role in ('pasteur','super_admin'));
$$;
revoke all on function public.is_direction() from public;
grant execute on function public.is_direction() to authenticated;

drop policy if exists profiles_self_read on public.app_profiles;
create policy profiles_self_read on public.app_profiles for select to authenticated using (user_id=auth.uid() or public.is_direction());
drop policy if exists profiles_direction_manage on public.app_profiles;
create policy profiles_direction_manage on public.app_profiles for all to authenticated using (public.is_direction()) with check (public.is_direction());

drop policy if exists family_access_self_read on public.family_user_access;
create policy family_access_self_read on public.family_user_access for select to authenticated using (user_id=auth.uid() or public.is_direction());
drop policy if exists family_access_direction_manage on public.family_user_access;
create policy family_access_direction_manage on public.family_user_access for all to authenticated using (public.is_direction()) with check (public.is_direction());

-- A signed-in account can see a family when explicitly assigned or when it has a global role.
create or replace function public.can_access_family(fid bigint) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.app_profiles p where p.user_id=auth.uid() and p.active and p.role in ('pasteur','super_admin','responsable_fi','responsable_fij','coordinateur_fi','coordinateur_fij'))
 or exists(select 1 from public.family_user_access a where a.user_id=auth.uid() and a.family_id=fid);
$$;
revoke all on function public.can_access_family(bigint) from public;
grant execute on function public.can_access_family(bigint) to authenticated;

-- Automatic account linking is intentionally driven by the member record and role assignments,
-- not by a public client choosing its own role. Auth trigger/RPC can be added after member role columns are normalized.


-- v199: modifications ponctuelles globales des rencontres, sans altérer le modèle hebdomadaire
alter table public.schedule_changes add column if not exists new_title text;
alter table public.schedule_changes add column if not exists new_theme text;
